export interface ComicBaseVideoRecord {
  id: string;
  title: string;
  series: string;
  issueNumber: string;
  publisher: string;
  creatorOrSubject: string;
  type: "interview" | "retrospective";
  duration: number; // in seconds
  resolution: string;
  path: string;
  videoUrl: string;
  headline: string;
  description: string;
}

export const COMICBASE_ARCHIVE_VIDEOS: ComicBaseVideoRecord[] = [
  {
    id: "cb-showcase-1",
    title: "Showcase #1 — The Dawn of the Silver Age",
    series: "Showcase",
    issueNumber: "1",
    publisher: "DC Comics",
    creatorOrSubject: "Julius Schwartz",
    type: "interview",
    duration: 109,
    resolution: "320x240",
    path: "D/DC/S/Showcase/1.m4v",
    videoUrl: "/api/video/comicbase/D/DC/S/Showcase/1.m4v",
    headline: "Julius Schwartz on Launching DC's Showcase and Rebuilding Superheroes",
    description: "Legendary DC editor Julius Schwartz recounts the origins of Showcase in 1956, conceived as a testing laboratory for new concepts that revived superhero comics and ignited the American Silver Age.",
  },
  {
    id: "cb-batman-dark-knight-1",
    title: "Batman: The Dark Knight Returns #1 — Frank Miller's Paradigm Shift",
    series: "Batman: The Dark Knight Returns",
    issueNumber: "1",
    publisher: "DC Comics",
    creatorOrSubject: "Frank Miller & Lynn Varley",
    type: "retrospective",
    duration: 112,
    resolution: "640x480",
    path: "D/DC/B/Batman- The Dark Knight/1.m4v",
    videoUrl: "/api/video/comicbase/D/DC/B/Batman-%20The%20Dark%20Knight/1.m4v",
    headline: "Archival Analysis: The Graphic Novel Revolution of 1986",
    description: "A forensic breakdown of Frank Miller, Klaus Janson, and Lynn Varley's 1986 masterpiece, examining its prestige format, widescreen 16-panel grids, and reinvention of Bruce Wayne as an aging sovereign vigilante.",
  },
  {
    id: "cb-preacher-1",
    title: "Preacher #1 — Garth Ennis on Vertigo & Jesse Custer",
    series: "Preacher",
    issueNumber: "1",
    publisher: "Vertigo / DC",
    creatorOrSubject: "Garth Ennis",
    type: "interview",
    duration: 133,
    resolution: "320x240",
    path: "V/Vertigo/Preacher/1.m4v",
    videoUrl: "/api/video/comicbase/V/Vertigo/Preacher/1.m4v",
    headline: "Garth Ennis on Religious Satire, Texas Mythology, and Steve Dillon",
    description: "Writer Garth Ennis discusses the inception of Preacher at DC Vertigo, his creative partnership with the late Steve Dillon, and navigating editorial boundaries to tell an unfiltered American Gothic epic.",
  },
  {
    id: "cb-hellblazer-1",
    title: "Hellblazer #1 — John Constantine's Occult London",
    series: "Hellblazer",
    issueNumber: "1",
    publisher: "Vertigo / DC",
    creatorOrSubject: "Garth Ennis",
    type: "interview",
    duration: 168,
    resolution: "320x240",
    path: "D/DC/H/Hellblazer/1.m4v",
    videoUrl: "/api/video/comicbase/D/DC/H/Hellblazer/1.m4v",
    headline: "Garth Ennis on John Constantine's Anti-Hero Cynicism",
    description: "Garth Ennis reflects on stepping onto John Constantine: Hellblazer, chronicling the working-class British occult detective created by Alan Moore and taking him through the seminal 'Dangerous Habits' storyline.",
  },
  {
    id: "cb-impulse-1",
    title: "Impulse #1 — Mark Waid on Bart Allen",
    series: "Impulse",
    issueNumber: "1",
    publisher: "DC Comics",
    creatorOrSubject: "Mark Waid",
    type: "interview",
    duration: 99,
    resolution: "320x240",
    path: "D/DC/I/Impulse/1.m4v",
    videoUrl: "/api/video/comicbase/D/DC/I/Impulse/1.m4v",
    headline: "Mark Waid on Speed-Force Physics and Teenage ADHD in Comics",
    description: "Writer Mark Waid breaks down the creation of Bart Allen (Impulse) alongside artist Humberto Ramos, exploring hyperactivity, generational legacy, and expanding the Flash mythology in the 1990s.",
  },
  {
    id: "cb-kingdom-come-1",
    title: "Kingdom Come #1 — Mark Waid & Alex Ross's Painted Prophecy",
    series: "Kingdom Come",
    issueNumber: "1",
    publisher: "DC Comics",
    creatorOrSubject: "Mark Waid & Alex Ross",
    type: "retrospective",
    duration: 80,
    resolution: "640x480",
    path: "D/DC/K/Kingdom Come/1.m4v",
    videoUrl: "/api/video/comicbase/D/DC/K/Kingdom%20Come/1.m4v",
    headline: "The Defining Elseworlds Epic: Alex Ross's Photorealistic Triumph",
    description: "An archival study of the 1996 prestige miniseries that countered 90s anti-hero cynicism with operatic moral heroism, featuring Alex Ross's fully gouache-painted artwork and biblical allegory.",
  },
  {
    id: "cb-sin-city-1",
    title: "Sin City #1 — Frank Miller's Noir Starkness",
    series: "Sin City",
    issueNumber: "1",
    publisher: "Dark Horse Comics",
    creatorOrSubject: "Frank Miller",
    type: "retrospective",
    duration: 159,
    resolution: "640x480",
    path: "D/Dark Horse/S/Sin City (Dark Horse)/1.m4v",
    videoUrl: "/api/video/comicbase/D/Dark%20Horse/S/Sin%20City%20(Dark%20Horse)/1.m4v",
    headline: "Pure High-Contrast Chiaroscuro: The Hard-Boiled Independent Renaissance",
    description: "Deep dive into Frank Miller's 1991 departure from mainstream superhero publishers to create Sin City at Dark Horse, leveraging stark negative space, black-and-white ink saturation, and pulp crime dialogue.",
  },
  {
    id: "cb-300-1",
    title: "300 #1 — Battle of Thermopylae in Landscape Format",
    series: "300",
    issueNumber: "1",
    publisher: "Dark Horse Comics",
    creatorOrSubject: "Frank Miller & Lynn Varley",
    type: "retrospective",
    duration: 59,
    resolution: "640x480",
    path: "D/Dark Horse/#/300/1.m4v",
    videoUrl: "/api/video/comicbase/D/Dark%20Horse/%23/300/1.m4v",
    headline: "Frank Miller's Horizontal Double-Page Splash Masterclass",
    description: "Retrospective examination of 300 #1, celebrated for its unique binding and oblong horizontal page format engineered specifically for sweeping panoramic combat double-splashes.",
  },
  {
    id: "cb-ronin-1",
    title: "Ronin #1 — The Cyberpunk Samurai Blueprint",
    series: "Ronin",
    issueNumber: "1",
    publisher: "DC Comics",
    creatorOrSubject: "Frank Miller",
    type: "retrospective",
    duration: 70,
    resolution: "640x480",
    path: "D/DC/R/Ronin/1.m4v",
    videoUrl: "/api/video/comicbase/D/DC/R/Ronin/1.m4v",
    headline: "Bridging Bande Dessinée, Manga, and American Comics in 1983",
    description: "A look back at Frank Miller's six-issue DC miniseries Ronin, blending Moebius, Goseki Kojima's Lone Wolf and Cub, and European color printing on heavy matte stock paper.",
  },
  {
    id: "cb-understanding-comics-1",
    title: "Understanding Comics: The Invisible Art",
    series: "Understanding Comics",
    issueNumber: "1",
    publisher: "Kitchen Sink / Paradox",
    creatorOrSubject: "Scott McCloud",
    type: "interview",
    duration: 74,
    resolution: "640x480",
    path: "P/Paradox/Understanding Comics/Bk 1.m4v",
    videoUrl: "/api/video/comicbase/P/Paradox/Understanding%20Comics/Bk%201.m4v",
    headline: "Scott McCloud on Sequential Art Theory, Closure, and Iconicity",
    description: "The seminal comic theorist Scott McCloud articulates how sequential narrative functions in human cognition, defining closure in the gutter and the universal amplification of simplistic cartoons.",
  },
  {
    id: "cb-reinventing-comics-1",
    title: "Reinventing Comics: The Digital Canvas",
    series: "Reinventing Comics",
    issueNumber: "1",
    publisher: "Paradox Press",
    creatorOrSubject: "Scott McCloud",
    type: "interview",
    duration: 122,
    resolution: "640x480",
    path: "P/Paradox/Reinventing Comics/1.m4v",
    videoUrl: "/api/video/comicbase/P/Paradox/Reinventing%20Comics/1.m4v",
    headline: "Scott McCloud on Infinite Canvas and the Evolution of Digital Mediums",
    description: "Scott McCloud prognosticates the future of digital comic distribution, micropayments, infinite web canvases, and creator independence ahead of the modern streaming era.",
  },
  {
    id: "cb-bone-1",
    title: "Bone #1 — Self-Publishing Fantasy Perfection",
    series: "Bone",
    issueNumber: "1",
    publisher: "Cartoon Books",
    creatorOrSubject: "Jeff Smith",
    type: "retrospective",
    duration: 88,
    resolution: "640x480",
    path: "C/Cartoon Books/Bone/1.m4v",
    videoUrl: "/api/video/comicbase/C/Cartoon%20Books/Bone/1.m4v",
    headline: "Jeff Smith's Independent Self-Publishing Phenomenon",
    description: "How Jeff Smith's Cartoon Books self-published Bone #1 in 1991, fusing classic Carl Barks Disney pacing with high Tolkien fantasy to create one of the most enduring indie properties in history.",
  },
  {
    id: "cb-savage-dragon-1",
    title: "The Savage Dragon #1 — The Image Comics Genesis",
    series: "Savage Dragon",
    issueNumber: "1",
    publisher: "Image Comics",
    creatorOrSubject: "Erik Larsen",
    type: "retrospective",
    duration: 81,
    resolution: "640x480",
    path: "I/Image/S/Savage Dragon, The/1.m4v",
    videoUrl: "/api/video/comicbase/I/Image/S/Savage%20Dragon,%20The/1.m4v",
    headline: "Erik Larsen on Creator Ownership and Unbroken Real-Time Continuity",
    description: "Exploring Erik Larsen's landmark 1992 Image Comics launch, notable for Larsen writing and drawing every single issue without reboots for more than 30 continuous years.",
  },
  {
    id: "cb-groo-1",
    title: "Groo the Wanderer #1 — Sergio Aragonés's Barbarian Parody",
    series: "Groo the Wanderer",
    issueNumber: "1",
    publisher: "Pacific Comics",
    creatorOrSubject: "Sergio Aragonés & Mark Evanier",
    type: "retrospective",
    duration: 122,
    resolution: "640x480",
    path: "P/Pacific/Groo the Wanderer (Sergio Aragones'-)/1.m4v",
    videoUrl: "/api/video/comicbase/P/Pacific/Groo%20the%20Wanderer%20(Sergio%20Aragones\x27-)/1.m4v",
    headline: "Sergio Aragonés & Mark Evanier on the Cheese Dip Chronicles",
    description: "The riotous comedy sword-and-sorcery parody created by MAD Magazine stalwart Sergio Aragonés, exploring Pacific Comics' direct-market indie royalty contract model.",
  },
  {
    id: "cb-daredevil-v2-1",
    title: "Daredevil (Vol. 2) #1 — Marvel Knights Rebirth",
    series: "Daredevil",
    issueNumber: "1",
    publisher: "Marvel Comics",
    creatorOrSubject: "Kevin Smith & Joe Quesada",
    type: "retrospective",
    duration: 73,
    resolution: "640x480",
    path: "M/Marvel/D/Daredevil (Vol. 2)/1.m4v",
    videoUrl: "/api/video/comicbase/M/Marvel/D/Daredevil%20(Vol.%202)/1.m4v",
    headline: "The 1998 Marvel Knights Imprint that Saved Marvel from Bankruptcy",
    description: "How filmmaker Kevin Smith and Event Comics' Joe Quesada and Jimmy Palmiotti revitalized the Man Without Fear, setting the tone for modern cinematic Marvel storytelling.",
  },
  {
    id: "cb-asm-v2-1",
    title: "The Amazing Spider-Man (Vol. 2) #1 — Late-90s Relaunch",
    series: "Amazing Spider-Man",
    issueNumber: "1",
    publisher: "Marvel Comics",
    creatorOrSubject: "Howard Mackie & John Byrne",
    type: "retrospective",
    duration: 83,
    resolution: "641x464",
    path: "M/Marvel/A/Amazing Spider-Man, The (Vol. 2)/1.m4v",
    videoUrl: "/api/video/comicbase/M/Marvel/A/Amazing%20Spider-Man,%20The%20(Vol.%202)/1.m4v",
    headline: "Howard Mackie and John Byrne's 1999 Wall-Crawler Reset",
    description: "Archival retrospective on Marvel's 1999 volume relaunch of Peter Parker following the Clone Saga, exploring direct market reception and modern holographic cover variants.",
  },
  {
    id: "cb-hitman-1",
    title: "Hitman #1 — Tommy Monaghan's Gotham Underworld",
    series: "Hitman",
    issueNumber: "1",
    publisher: "DC Comics",
    creatorOrSubject: "Garth Ennis & John McCrea",
    type: "retrospective",
    duration: 89,
    resolution: "640x480",
    path: "D/DC/H/Hitman/1.m4v",
    videoUrl: "/api/video/comicbase/D/DC/H/Hitman/1.m4v",
    headline: "Garth Ennis and John McCrea's Caustic Gotham City Mercenary",
    description: "Spun out of The Demon Annual #2, Tommy Monaghan and the regulars at Noonan's Sleazy Bar brought dark humor, military realism, and working-class camaraderie into Gotham's superhero landscape.",
  },
  {
    id: "cb-deadman-1",
    title: "Deadman #1 — Neal Adams's Phantasmagoric Line Work",
    series: "Deadman",
    issueNumber: "1",
    publisher: "DC Comics",
    creatorOrSubject: "Neal Adams & Arnold Drake",
    type: "retrospective",
    duration: 105,
    resolution: "640x480",
    path: "D/DC/D/Deadman (1st Series)/1.m4v",
    videoUrl: "/api/video/comicbase/D/DC/D/Deadman%20(1st%20Series)/1.m4v",
    headline: "Neal Adams Revolutionizes DC Comic Layouts & Anatomical Realism",
    description: "An archival study of Boston Brand's astral avenger, famous for Neal Adams's dizzying cinematic angles, bleed-edge page borders, and dynamic perspective.",
  },
  {
    id: "cb-green-lantern-1",
    title: "Green Lantern (1st Series) #1 — Hal Jordan Takes Flight",
    series: "Green Lantern",
    issueNumber: "1",
    publisher: "DC Comics",
    creatorOrSubject: "John Broome & Gil Kane",
    type: "retrospective",
    duration: 65,
    resolution: "640x480",
    path: "D/DC/G/Green Lantern (1st Series)/1.m4v",
    videoUrl: "/api/video/comicbase/D/DC/G/Green%20Lantern%20(1st%20Series)/1.m4v",
    headline: "The 1960 Launch of Hal Jordan's Cosmic Intergalactic Patrol",
    description: "Following his debut in Showcase #22, John Broome and Gil Kane launched Hal Jordan into his own title, expanding the mythology of Oa and the Guardians of the Universe.",
  },
  {
    id: "cb-green-lantern-arrow-1",
    title: "Green Lantern / Green Arrow #76 — Hard-Traveling Heroes",
    series: "Green Lantern-Green Arrow",
    issueNumber: "1",
    publisher: "DC Comics",
    creatorOrSubject: "Dennis O'Neil & Neal Adams",
    type: "retrospective",
    duration: 100,
    resolution: "640x480",
    path: "D/DC/G/Green Lantern-Green Arrow/1.m4v",
    videoUrl: "/api/video/comicbase/D/DC/G/Green%20Lantern-Green%20Arrow/1.m4v",
    headline: "Denny O'Neil and Neal Adams Inject Real-World Social Relevance",
    description: "The historic 1970 team-up pairing Hal Jordan's establishment lawman with Oliver Queen's progressive crusader to tackle racism, poverty, and corruption in mainstream comics.",
  },
  {
    id: "cb-hawkman-1",
    title: "Hawkman (1st Series) #1 — Silver Age Thanagarian Science",
    series: "Hawkman",
    issueNumber: "1",
    publisher: "DC Comics",
    creatorOrSubject: "Gardner Fox & Joe Kubert",
    type: "retrospective",
    duration: 100,
    resolution: "640x480",
    path: "D/DC/H/Hawkman (1st Series)/1.m4v",
    videoUrl: "/api/video/comicbase/D/DC/H/Hawkman%20(1st%20Series)/1.m4v",
    headline: "Katar Hol and Shayera Hol: Joe Kubert's Avian Masterclass",
    description: "Gardner Fox and Joe Kubert reinvisioned Hawkman from 1940s reincarnation archaeologist into alien Thanagarian police officers on Earth, featuring Kubert's gritty feather textures.",
  },
  {
    id: "cb-krazy-kat-1",
    title: "Krazy Kat #1 — George Herriman's Surrealist Comic Poetry",
    series: "Krazy Kat",
    issueNumber: "1",
    publisher: "Gold Key",
    creatorOrSubject: "George Herriman",
    type: "retrospective",
    duration: 204,
    resolution: "321x240",
    path: "G/Gold Key/Krazy Kat/1.m4v",
    videoUrl: "/api/video/comicbase/G/Gold%20Key/Krazy%20Kat/1.m4v",
    headline: "The Eternal Triangle: Krazy, Ignatz Mouse, and Officer Pupp",
    description: "A rich historical featurette on George Herriman's Coconino County masterpiece, hailed by critics from e.e. cummings to Art Spiegelman as the highest artistic pinnacle of the medium.",
  },
  {
    id: "cb-zot-1",
    title: "Zot! #1 — Scott McCloud's Retro-Futuristic Optimism",
    series: "Zot!",
    issueNumber: "1",
    publisher: "Eclipse Comics",
    creatorOrSubject: "Scott McCloud",
    type: "retrospective",
    duration: 77,
    resolution: "640x472",
    path: "E/Eclipse/Zot!/1.m4v",
    videoUrl: "/api/video/comicbase/E/Eclipse/Zot!/1.m4v",
    headline: "Scott McCloud's 1984 Antidote to Grim-and-Gritty Comics",
    description: "Zot! debuted at Eclipse Comics in 1984, combining golden age space hero exuberance with Osamu Tezuka manga pacing, preceding McCloud's theoretical landmark works.",
  },
  {
    id: "cb-stray-bullets-1",
    title: "Stray Bullets #1 — David Lapham's Neo-Noir Masterwork",
    series: "Stray Bullets",
    issueNumber: "1",
    publisher: "El Capitan",
    creatorOrSubject: "David Lapham",
    type: "retrospective",
    duration: 59,
    resolution: "640x480",
    path: "E/El Capitan/Stray Bullets/1.m4v",
    videoUrl: "/api/video/comicbase/E/El%20Capitan/Stray%20Bullets/1.m4v",
    headline: "David Lapham's Ruthless Crime Fiction & 8-Panel Precision",
    description: "The 1995 Eisner Award-winning crime anthology published by Lapham's own El Capitan imprint, known for its nonlinear timeline and unsparing Midwestern criminal tragedies.",
  },
  {
    id: "cb-cadillacs-1",
    title: "Cadillacs and Dinosaurs #1 — Mark Schultz's Xenozoic Tale",
    series: "Cadillacs & Dinosaurs",
    issueNumber: "1",
    publisher: "Epic Comics / Kitchen Sink",
    creatorOrSubject: "Mark Schultz",
    type: "retrospective",
    duration: 179,
    resolution: "319x194",
    path: "E/Epic/Cadillacs & Dinosaurs/1.m4v",
    videoUrl: "/api/video/comicbase/E/Epic/Cadillacs%20&%20Dinosaurs/1.m4v",
    headline: "Mark Schultz's Roy Krenkel & Hal Foster Classicism",
    description: "Mark Schultz's post-apocalyptic ecological adventure featuring Jack Tenrec and Hannah Dundee, famous for Schultz's virtuoso brushwork and retro-futuristic mechanical draftsmanship.",
  },
  {
    id: "cb-madman-1",
    title: "Madman #1 — Mike Allred's Pop-Art Superhero",
    series: "Madman",
    issueNumber: "1",
    publisher: "Kitchen Sink Press",
    creatorOrSubject: "Mike Allred",
    type: "retrospective",
    duration: 100,
    resolution: "640x480",
    path: "K/Kitchen Sink/Madman/1.m4v",
    videoUrl: "/api/video/comicbase/K/Kitchen%20Sink/Madman/1.m4v",
    headline: "Frank Einstein, The Atomics, and 1960s Mod Aesthetic",
    description: "Mike and Laura Allred's vibrant, joyful homage to vintage pop art, music, and Silver Age superhero tropes, launching one of the most beloved indie heroes of the 1990s.",
  },
  {
    id: "cb-mage-1",
    title: "Mage: The Hero Discovered #1 — The Fisher King Myth",
    series: "Mage",
    issueNumber: "1",
    publisher: "COMICO / Image",
    creatorOrSubject: "Matt Wagner",
    type: "retrospective",
    duration: 67,
    resolution: "641x454",
    path: "C/COMICO/Mage/1.m4v",
    videoUrl: "/api/video/comicbase/C/COMICO/Mage/1.m4v",
    headline: "Matt Wagner Transposes Arthurian Legend to Modern Urban Fantasy",
    description: "Kevin Matchstick discovers he wields Excalibur in the form of a glowing baseball bat, cementing Matt Wagner as a premier auteur of 1980s direct-market independent comics.",
  },
  {
    id: "cb-sandman-mystery-theatre-1",
    title: "Sandman Mystery Theatre #1 — Golden Age Noir Wesley Dodds",
    series: "Sandman Mystery Theatre",
    issueNumber: "1",
    publisher: "Vertigo / DC",
    creatorOrSubject: "Matt Wagner, Steven T. Seagle & Guy Davis",
    type: "retrospective",
    duration: 86,
    resolution: "640x480",
    path: "V/Vertigo/Sandman Mystery Theatre/1.m4v",
    videoUrl: "/api/video/comicbase/V/Vertigo/Sandman%20Mystery%20Theatre/1.m4v",
    headline: "Gas-Mask Vigilante in Pre-WWII Manhattan",
    description: "Matt Wagner and Guy Davis's moody Vertigo reboot of Wesley Dodds, rooted in 1930s trench-coat pulps, social inequality, and psychological profiling.",
  },
  {
    id: "cb-batman-grendel-1",
    title: "Batman / Grendel #1 — Hunter Rose In Gotham",
    series: "Batman-Grendel",
    issueNumber: "1",
    publisher: "DC / Dark Horse",
    creatorOrSubject: "Matt Wagner",
    type: "retrospective",
    duration: 71,
    resolution: "620x480",
    path: "D/DC/B/Batman-Grendel (1st Series)/1.m4v",
    videoUrl: "/api/video/comicbase/D/DC/B/Batman-Grendel%20(1st%20Series)/1.m4v",
    headline: "The Sophisticated Assassin Confronts the Caped Crusader",
    description: "Matt Wagner wrote and illustrated the legendary 1993 DC/Dark Horse crossover pitting Hunter Rose's criminal mastermind against Batman in a game of intellect and blades.",
  },
  {
    id: "cb-grendel-war-child-1",
    title: "Grendel: War Child #1 — Grendel Prime's Dystopia",
    series: "Grendel- War Child",
    issueNumber: "1",
    publisher: "Dark Horse Comics",
    creatorOrSubject: "Matt Wagner & Patrick McEown",
    type: "retrospective",
    duration: 73,
    resolution: "640x480",
    path: "D/Dark Horse/G/Grendel- War Child/1.m4v",
    videoUrl: "/api/video/comicbase/D/Dark%20Horse/G/Grendel-%20War%20Child/1.m4v",
    headline: "Cyborg Paladin and the Rebirth of the Grendel Khan Dynasty",
    description: "The 10-issue science-fiction epic chronicling Grendel Prime's mission to protect Jupiter Assante through a militarized future Earth, winning the 1993 Eisner for Best Finite Series.",
  },
  {
    id: "cb-distant-soil-1",
    title: "A Distant Soil #1 — Colleen Doran's Space Opera",
    series: "A Distant Soil",
    issueNumber: "1",
    publisher: "Aria / Image",
    creatorOrSubject: "Colleen Doran",
    type: "retrospective",
    duration: 77,
    resolution: "640x480",
    path: "A/Aria/Distant Soil, A (2nd Series)/1.m4v",
    videoUrl: "/api/video/comicbase/A/Aria/Distant%20Soil,%20A%20(2nd%20Series)/1.m4v",
    headline: "Pioneering Space Opera and Bishonen Aesthetics in American Indie Comics",
    description: "Written and illustrated by Colleen Doran starting in her teens, A Distant Soil broke ground for creator rights, complex operatic worldbuilding, and manga influences in the US market.",
  },
  {
    id: "cb-red-rocket-7-1",
    title: "Red Rocket 7 #1 — Mike Allred's Musical Odyssey",
    series: "Red Rocket 7",
    issueNumber: "1",
    publisher: "Dark Horse Comics",
    creatorOrSubject: "Mike Allred",
    type: "retrospective",
    duration: 93,
    resolution: "640x480",
    path: "D/Dark Horse/R/Red Rocket 7/1.m4v",
    videoUrl: "/api/video/comicbase/D/Dark%20Horse/R/Red%20Rocket%207/1.m4v",
    headline: "An Alien Clone Chronicling the History of Rock and Roll",
    description: "Mike Allred's ambitious square-format series tracking the evolution of rock music from Little Richard and The Beatles to punk, glam, and modern indie music through an alien protagonist.",
  },
  {
    id: "cb-archie-1",
    title: "Archie Comics #1 — Riverdale's Golden Age Origin",
    series: "Archie",
    issueNumber: "1",
    publisher: "Archie Comics",
    creatorOrSubject: "Bob Montana & Vic Bloom",
    type: "retrospective",
    duration: 138,
    resolution: "640x480",
    path: "A/Archie/Archie/1.m4v",
    videoUrl: "/api/video/comicbase/A/Archie/Archie/1.m4v",
    headline: "Archie Andrews, Betty, Veronica, and Jughead: 1942 Americana",
    description: "Historical retrospective on MLJ/Archie's pivot from grim superhero crime-fighters to wholesome teenage comedy, becoming an enduring cornerstone of 20th-century pop culture.",
  },
  {
    id: "cb-josie-17",
    title: "Josie #17 — The Introduction of The Pussycats",
    series: "Josie",
    issueNumber: "17",
    publisher: "Archie Comics",
    creatorOrSubject: "Dan DeCarlo",
    type: "retrospective",
    duration: 90,
    resolution: "640x480",
    path: "A/Archie/Josie/17.m4v",
    videoUrl: "/api/video/comicbase/A/Archie/Josie/17.m4v",
    headline: "Dan DeCarlo Introduces Leopard Leotards and Melody Valentine",
    description: "The milestone issue where Josie and Melody team up with Valerie Brown, creating Archie's iconic rock group Josie and the Pussycats and introducing the first recurring Black female character in Archie canon.",
  },
  {
    id: "cb-buster-brown-1",
    title: "Buster Brown Comic Book #1 — Platinum Age Giveaway History",
    series: "Buster Brown Comic Book",
    issueNumber: "1",
    publisher: "Buster Brown Shoes",
    creatorOrSubject: "Richard F. Outcault",
    type: "retrospective",
    duration: 144,
    resolution: "160x120",
    path: "B/Buster Brown/Buster Brown Comic Book/1.m4v",
    videoUrl: "/api/video/comicbase/B/Buster%20Brown/Buster%20Brown%20Comic%20Book/1.m4v",
    headline: "Promotional Platinum Age Comics and Tige the Talking Dog",
    description: "Historical overview of early 20th-century promotional comic books distributed through shoe retailers, showcasing Richard Outcault's mischief-maker that revolutionized merchandising licensing.",
  },
  {
    id: "cb-ash-0",
    title: "Ash #0 — Joe Quesada & Jimmy Palmiotti's Event Comics",
    series: "Ash",
    issueNumber: "0",
    publisher: "Event Comics",
    creatorOrSubject: "Joe Quesada & Jimmy Palmiotti",
    type: "retrospective",
    duration: 53,
    resolution: "640x480",
    path: "E/Event/Ash/0.m4v",
    videoUrl: "/api/video/comicbase/E/Event/Ash/0.m4v",
    headline: "Firefighter Ashley Quinn and the Genesis of the Quesada/Palmiotti Studio",
    description: "The 1994 independent phenomenon that established Event Comics as a creative powerhouse, serving as the direct springboard to Joe Quesada becoming Marvel's Editor-in-Chief.",
  }
];

export function findComicBaseVideoForComic(seriesName?: string | null, issueNumber?: string | null): ComicBaseVideoRecord | null {
  if (!seriesName) return null;
  const cleanSeries = seriesName.toLowerCase().trim();
  const cleanIssue = (issueNumber || "").trim().replace(/^0+/, "");

  return COMICBASE_ARCHIVE_VIDEOS.find((v) => {
    const vSeries = v.series.toLowerCase();
    const vIssue = v.issueNumber.replace(/^0+/, "");
    
    // Check issue match first
    if (vIssue && cleanIssue && vIssue !== cleanIssue) {
      return false;
    }

    if (cleanSeries.includes(vSeries) || vSeries.includes(cleanSeries)) {
      return true;
    }

    // Specific aliases
    if (cleanSeries.includes("dark knight") && vSeries.includes("dark knight")) return true;
    if (cleanSeries.includes("showcase") && vSeries.includes("showcase")) return true;
    if (cleanSeries.includes("preacher") && vSeries.includes("preacher")) return true;
    if (cleanSeries.includes("hellblazer") && vSeries.includes("hellblazer")) return true;
    if (cleanSeries.includes("kingdom come") && vSeries.includes("kingdom come")) return true;
    if (cleanSeries.includes("sin city") && vSeries.includes("sin city")) return true;
    if (cleanSeries.includes("300") && vSeries === "300") return true;
    if (cleanSeries.includes("ronin") && vSeries === "ronin") return true;
    if (cleanSeries.includes("impulse") && vSeries.includes("impulse")) return true;
    if (cleanSeries.includes("bone") && vSeries.includes("bone")) return true;
    if (cleanSeries.includes("savage dragon") && vSeries.includes("savage dragon")) return true;
    if (cleanSeries.includes("groo") && vSeries.includes("groo")) return true;
    if (cleanSeries.includes("spider-man") && vSeries.includes("spider-man")) return true;
    if (cleanSeries.includes("daredevil") && vSeries.includes("daredevil")) return true;
    if (cleanSeries.includes("green lantern") && vSeries.includes("green lantern")) return true;
    if (cleanSeries.includes("hawkman") && vSeries.includes("hawkman")) return true;
    if (cleanSeries.includes("deadman") && vSeries.includes("deadman")) return true;
    if (cleanSeries.includes("krazy kat") && vSeries.includes("krazy kat")) return true;
    if (cleanSeries.includes("zot") && vSeries.includes("zot")) return true;
    if (cleanSeries.includes("stray bullets") && vSeries.includes("stray bullets")) return true;
    if (cleanSeries.includes("cadillacs") && vSeries.includes("cadillacs")) return true;
    if (cleanSeries.includes("madman") && vSeries.includes("madman")) return true;
    if (cleanSeries.includes("mage") && vSeries.includes("mage")) return true;
    if (cleanSeries.includes("archie") && vSeries.includes("archie")) return true;
    if (cleanSeries.includes("josie") && vSeries.includes("josie")) return true;
    if (cleanSeries.includes("buster brown") && vSeries.includes("buster brown")) return true;
    if (cleanSeries.includes("ash") && vSeries.includes("ash")) return true;

    return false;
  }) || null;
}
