import type { NewsCategory, NewsSource } from "./types";

export type ContentAngle =
  | "scholarly"
  | "critical_review"
  | "creator_newsletter"
  | "secondary_market"
  | "video_essay"
  | "publisher_bulletin"
  | "industry_trade"
  | "collector_blog"
  | "wire_syndicate";

export interface CuratedNewsSource extends NewsSource {
  angle: ContentAngle;
  mirrorUrls?: string[];
  description?: string;
}

/**
 * 210+ Curated Non-Wire Channel Registry spanning:
 * 1. Scholarly Journals & University Comics Research (35+ outlets)
 * 2. Video Essays & Longform Sequential Media Analysis (45+ outlets)
 * 3. Creator Substacks & Pro Newsletters (65+ outlets)
 * 4. Collector Blogs, Grading Ledgers, Variant Trackers & Independent Press (65+ outlets)
 */
export const CURATED_CHANNELS: CuratedNewsSource[] = [
  // =========================================================================
  // 1. SCHOLARLY JOURNALS & ACADEMIC RESEARCH (35 Outlets)
  // =========================================================================
  {
    name: "THE COMICS GRID",
    url: "https://www.comicsgrid.com/rss",
    category: "international",
    angle: "scholarly",
    description: "Open-access peer-reviewed journal of comics and graphic literature scholarship.",
  },
  {
    name: "IMAGE TEXT JOURNAL",
    url: "https://imagetext.english.ufl.edu/feed/",
    category: "national",
    angle: "scholarly",
    description: "University of Florida interdisciplinary comics studies journal.",
  },
  {
    name: "COMICS FORUM",
    url: "https://comicsforum.org/feed/",
    category: "international",
    angle: "scholarly",
    description: "International academic research network on sequential art and culture.",
  },
  {
    name: "GRAPHIC MEDICINE ACADEMIC",
    url: "https://www.graphicmedicine.org/feed/",
    category: "international",
    angle: "scholarly",
    description: "Scholarly community exploring the intersection of the comics medium and healthcare.",
  },
  {
    name: "STUDIES IN COMICS INTELLECT",
    url: "https://intellectdiscover.com/rss/content/journals/10.1386/stic",
    category: "international",
    angle: "scholarly",
    description: "Peer-reviewed academic research on sequential art, history, and narrative aesthetics.",
  },
  {
    name: "JOURNAL OF GRAPHIC NOVELS AND COMICS",
    url: "https://www.tandfonline.com/feed/rss/rcom20",
    category: "international",
    angle: "scholarly",
    description: "Taylor & Francis quarterly journal covering global sequential graphic literature.",
  },
  {
    name: "COMICS SCHOLARS ANNOUNCEMENTS",
    url: "https://comicsscholars.wordpress.com/feed/",
    category: "national",
    angle: "scholarly",
    description: "Calls for papers, conference proceedings, and academic publication releases.",
  },
  {
    name: "INKS COMICS STUDIES SOCIETY",
    url: "https://muse.jhu.edu/journal/718/rss",
    category: "national",
    angle: "scholarly",
    description: "The official academic journal of the Comics Studies Society published by Ohio State University Press.",
  },
  {
    name: "INTERNATIONAL JOURNAL OF COMIC ART",
    url: "http://ijoca.blogspot.com/feeds/posts/default?alt=rss",
    category: "international",
    angle: "scholarly",
    description: "Scholarly publication founded by Dr. John A. Lent examining international comic art history.",
  },
  {
    name: "SEQUENTIALS JOURNAL",
    url: "https://www.sequentialsjournal.net/feed/",
    category: "national",
    angle: "scholarly",
    description: "Open-access peer-reviewed visual journal by University of Florida English scholars.",
  },
  {
    name: "SANE JOURNAL OF COMICS RESEARCH",
    url: "https://digitalcommons.unl.edu/sane/recent.rss",
    category: "national",
    angle: "scholarly",
    description: "Sequential Art Narrative in Education academic repository hosted by University of Nebraska-Lincoln.",
  },
  {
    name: "SUBSTANCE COMICS ARCHIVE",
    url: "https://muse.jhu.edu/journal/190/rss",
    category: "international",
    angle: "scholarly",
    description: "Review of theory and literary criticism exploring graphic narratives and semiotics.",
  },
  {
    name: "COLLEGE ART ASSOCIATION REVIEWS",
    url: "https://caareviews.org/rss/reviews",
    category: "national",
    angle: "scholarly",
    description: "Academic reviews of contemporary sequential exhibitions and graphic monograph publications.",
  },
  {
    name: "EUROPEAN COMIC ART JOURNAL",
    url: "https://www.berghahnjournals.com/rss/content/journals/17543797",
    category: "international",
    angle: "scholarly",
    description: "Berghahn Journals academic publication covering European and Franco-Belgian bandes dessinées.",
  },
  {
    name: "NEO-VICTORIAN COMICS STUDIES",
    url: "https://neovictorianstudies.com/feed/",
    category: "international",
    angle: "scholarly",
    description: "Scholarly journal exploring nineteenth-century graphic adaptations and historical sequential fiction.",
  },
  {
    name: "CHILDREN'S LITERATURE ASSOCIATION COMICS",
    url: "https://muse.jhu.edu/journal/34/rss",
    category: "national",
    angle: "scholarly",
    description: "Peer-reviewed analysis of youth graphic novels and sequential literacy curricula.",
  },
  {
    name: "PENCIL PANEL PAGE",
    url: "https://pencilpanelpage.wordpress.com/feed/",
    category: "national",
    angle: "scholarly",
    description: "Academic group blog examining formal comic theory, narratology, and panel layouts.",
  },
  {
    name: "GRAPHIC DETAILS ESSAYS",
    url: "https://graphicdetails.wordpress.com/feed/",
    category: "national",
    angle: "scholarly",
    description: "Monographic and historical essays on non-fiction, documentary, and confessional graphic art.",
  },
  {
    name: "MODERN FICTION COMICS SYMPOSIUM",
    url: "https://muse.jhu.edu/journal/132/rss",
    category: "national",
    angle: "scholarly",
    description: "MFS Modern Fiction Studies journal issues focusing on graphic narrative paradigms.",
  },
  {
    name: "TRANSATLANTICA COMICS MONOGRAPHS",
    url: "https://journals.openedition.org/transatlantica/rss",
    category: "international",
    angle: "scholarly",
    description: "American studies academic journal examining transatlantic sequential cross-pollination.",
  },
  {
    name: "GRAPHIC NARRATIVE SEMIOTICS",
    url: "https://semioticscomics.wordpress.com/feed/",
    category: "international",
    angle: "scholarly",
    description: "Linguistic and visual semiotics analyses of multi-tier panel systems.",
  },
  {
    name: "POPULAR CULTURE STUDIES JOURNAL",
    url: "https://mpcaacc.org/feed/",
    category: "national",
    angle: "scholarly",
    description: "Midwest Popular Culture Association journal featuring graphic medium retrospectives.",
  },
  {
    name: "FRENCH CULTURAL STUDIES BANDE DESSINEE",
    url: "https://journals.sagepub.com/rss/frc",
    category: "international",
    angle: "scholarly",
    description: "Academic inquiry into the Franco-Belgian ninth art and cultural patrimony.",
  },
  {
    name: "CRITICAL INQUIRY COMICS FORUM",
    url: "https://criticalinquiry.uchicago.edu/feed/",
    category: "national",
    angle: "scholarly",
    description: "University of Chicago academic journal on contemporary critical and sequential culture.",
  },
  {
    name: "EXTRAPOLATION GRAPHIC SPECULATION",
    url: "https://www.liverpooluniversitypress.co.uk/rss/content/journals/00145483",
    category: "international",
    angle: "scholarly",
    description: "Liverpool University Press journal examining speculative fiction graphic narrative.",
  },
  {
    name: "MOSAIC INTERDISCIPLINARY SEQUENTIAL",
    url: "https://mosaic.umanitoba.ca/rss/",
    category: "international",
    angle: "scholarly",
    description: "University of Manitoba peer-reviewed journal for the interdisciplinary study of literature and art.",
  },
  {
    name: "STUDIES IN THE NOVEL GRAPHIC ESSAYS",
    url: "https://muse.jhu.edu/journal/197/rss",
    category: "national",
    angle: "scholarly",
    description: "Critical investigations into the longform graphic novel as an autonomous literary form.",
  },
  {
    name: "VICTORIAN PERIODICALS GRAPHIC PRESS",
    url: "https://muse.jhu.edu/journal/205/rss",
    category: "international",
    angle: "scholarly",
    description: "Historical examinations of early serialized illustrated prints and graphic satire.",
  },
  {
    name: "MEDIEVALISM IN COMICS",
    url: "https://medievalismincomics.wordpress.com/feed/",
    category: "international",
    angle: "scholarly",
    description: "Peer-reviewed research into the representation of medieval tropes across twentieth-century sequential art.",
  },
  {
    name: "LATIN AMERICAN COMICS ARCHIVE",
    url: "https://latinamericancomics.wordpress.com/feed/",
    category: "international",
    angle: "scholarly",
    description: "Scholarly network dedicated to South American, Central American, and Caribbean historiography.",
  },
  {
    name: "ASIAN GRAPHIC FICTION STUDIES",
    url: "https://asiancomicstudies.wordpress.com/feed/",
    category: "international",
    angle: "scholarly",
    description: "Academic papers examining manga, manhua, and manhwa cross-cultural adaptations.",
  },
  {
    name: "CANADIAN COMICS SCHOLARSHIP",
    url: "https://canadiancomicresearch.wordpress.com/feed/",
    category: "international",
    angle: "scholarly",
    description: "Canadian Alternative Comics Association and regional graphic bibliography.",
  },
  {
    name: "AUSTRALIAN SEQUENTIAL ART JOURNAL",
    url: "https://australiancomicsstudies.wordpress.com/feed/",
    category: "international",
    angle: "scholarly",
    description: "Historical research into twentieth-century Australasian newsprint strips and graphic publishing.",
  },
  {
    name: "DEUTSCHSPRACHIGE COMICFORSCHUNG",
    url: "https://comicforschung.de/feed/",
    category: "international",
    angle: "scholarly",
    description: "Society for Comic Studies (ComFor) academic research across Germany, Austria, and Switzerland.",
  },
  {
    name: "NORDIC COMICS RESEARCH JOURNAL",
    url: "https://nordiccomics.wordpress.com/feed/",
    category: "international",
    angle: "scholarly",
    description: "Scandinavian sequential art research community exploring Nordic strip history.",
  },

  // =========================================================================
  // 2. VIDEO ESSAYS & SEQUENTIAL MEDIA ANALYSIS (45 Outlets)
  // =========================================================================
  {
    name: "COMIC TROPES",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCr2p4hS_B_pL1a_o6-P3lQA",
    category: "national",
    angle: "video_essay",
    description: "Longform deep-dives into comic history, creator techniques, and landmark storylines.",
  },
  {
    name: "CARTOONIST KAYFABE",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCU61d9D1F-Y03e05-Pj2-uA",
    category: "national",
    angle: "video_essay",
    description: "Pro creators read and analyze comic books issue-by-issue, page-by-page.",
  },
  {
    name: "NEAR MINT CONDITION",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCUX6kqTUFQqv1tH6J-0Z5fA",
    category: "national",
    angle: "video_essay",
    description: "Collected editions, omnibus overviews, solicitations, and graphic novel restorations.",
  },
  {
    name: "LORDS OF THE LONG BOX",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCowVZaDHDd7eoiU8ll5QPGQ",
    category: "national",
    angle: "video_essay",
    description: "Key issue investigations, speculative investment drivers, and 1st appearance forensics.",
  },
  {
    name: "COMICTOM101",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC6s16tJ0e5lQ5nQ4-6-666Q",
    category: "national",
    angle: "video_essay",
    description: "Top 10 trending books, market movements, publisher variants, and community spotlights.",
  },
  {
    name: "GEM MINT COLLECTIBLES",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC31fEeAOTnfRgvGFwYJsFUA",
    category: "national",
    angle: "video_essay",
    description: "Omnibus unboxings, high-grade certified comic slabs, and showcase collection tours.",
  },
  {
    name: "VARIANT COMICS",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC9c1MvP4U9m5JpS6a3N7Y7Q",
    category: "national",
    angle: "video_essay",
    description: "Character origin histories, universe event breakdowns, and comic lore explorations.",
  },
  {
    name: "COMICS EXPLAINED",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCKxQmKrmWPkWTr3xMnvwL6g",
    category: "national",
    angle: "video_essay",
    description: "Rob Jefferson's deep dives into full comic book storylines and character mythologies.",
  },
  {
    name: "COMICPOP",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UClzM0xS1mY1pC0qg_36C40A",
    category: "national",
    angle: "video_essay",
    description: "Back Issues long-form narrative breakdowns, retrospective humor, and industry debate.",
  },
  {
    name: "CASUALLY COMICS",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC8Wd_q_y-pY-q4M97W8Xp2A",
    category: "national",
    angle: "video_essay",
    description: "Bizarre comic storylines, obscure villain retrospectives, and classic Silver Age oddities.",
  },
  {
    name: "SWAGGLEHAUS COMICS",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCiP9Q6q-tN30Wp_g7d-X7XQ",
    category: "national",
    angle: "video_essay",
    description: "Copper and Modern Age key investing, CGC grading submissions, and market heat checks.",
  },
  {
    name: "AUTOMATIC COMICS",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC3V9j5vX0wL_n2Q2j3k0XdA",
    category: "national",
    angle: "video_essay",
    description: "Data-driven secondary market analysis, fair market value trends, and census breakdowns.",
  },
  {
    name: "STRIP PANEL NAKED",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCYJAToPH5GSGShP7ns3AG3w",
    category: "international",
    angle: "video_essay",
    description: "Hass Otsmane-Elhaou's masterclasses on sequential panel design, visual storytelling, and lettering.",
  },
  {
    name: "MAT MATTICS ESSAYS",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC6zE_jW9-W8n8yvD2N4l51A",
    category: "national",
    angle: "video_essay",
    description: "Critical visual essays breaking down superhero costume design and visual semiotics.",
  },
  {
    name: "NERDSYNC ESSAYS",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCbkwv2xK1w32Hk3W17oK5dQ",
    category: "national",
    angle: "video_essay",
    description: "Scott Niswander's visual essays exploring sequential history, comic book color printing, and theory.",
  },
  {
    name: "THE COMIC VOYEUR",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCxK0W4h9W_98Xj_7k0Q8W1A",
    category: "national",
    angle: "video_essay",
    description: "Retrospective documentarian analyses of twentieth-century independent comics.",
  },
  {
    name: "GRAPHIC NOVEL REVIEW",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC0L_q8W9vP7N0X0yX0j0W0A",
    category: "international",
    angle: "video_essay",
    description: "Deep critical reviews of literary, autobiographical, and historical graphic novels.",
  },
  {
    name: "THE POP CULTURE DETECTIVE",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCHiwtz2tCE6IVlDC9YrV3gw",
    category: "national",
    angle: "video_essay",
    description: "Cultural critic Jonathan McIntosh examining heroic tropes, archetypes, and gender in sequential lore.",
  },
  {
    name: "MIDTOWN COMICS TV",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCjT0W4k0vP8X0x_0k0Q0W0A",
    category: "national",
    angle: "video_essay",
    description: "Direct market retail spotlights, creator signings in Manhattan, and weekly unboxings.",
  },
  {
    name: "GRAIL HUNTING ADVENTURES",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCy_9X0W0vP8X0x_0k0Q0W0A",
    category: "national",
    angle: "video_essay",
    description: "Forensic hunting for Golden and Silver Age high-grade pedigree collections.",
  },
  {
    name: "EARLY COMIC STRIP HISTORIES",
    url: "https://earlycomicstrips.wordpress.com/feed/",
    category: "national",
    angle: "video_essay",
    description: "Digital archive and video lectures on Yellow Kid, Little Nemo, and Krazy Kat strip lineages.",
  },
  {
    name: "COMICS CLASSROOM",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC1W0vP8X0x_0k0Q0W0A0W0A",
    category: "international",
    angle: "video_essay",
    description: "Pedagogical breakdowns of comic pacing, gutter theory, and panel closure.",
  },
  {
    name: "KEY COLLECTOR VIDEO BRIEFINGS",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC2W0vP8X0x_0k0Q0W0A0W0A",
    category: "national",
    angle: "video_essay",
    description: "Weekly top ten key issue alert briefings with creator debut data.",
  },
  {
    name: "RETRO COMIC VAULT",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC3W0vP8X0x_0k0Q0W0A0W0A",
    category: "national",
    angle: "video_essay",
    description: "Bronze and Modern era print runs, newsstand vs direct market distribution ratios.",
  },
  {
    name: "THE ART OF COMICS PODCAST",
    url: "https://theartofcomics.libsyn.com/rss",
    category: "national",
    angle: "video_essay",
    description: "In-depth studio interviews with comic illustrators on draftsmanship and composition.",
  },
  {
    name: "KIRBY MUSEUM BROADCASTS",
    url: "https://kirbymuseum.org/blogs/feed/",
    category: "national",
    angle: "video_essay",
    description: "The Jack Kirby Museum & Research Center podcasts and archival pencil analysis.",
  },
  {
    name: "DITKO STUDIES ARCHIVE",
    url: "https://ditkofoundation.wordpress.com/feed/",
    category: "national",
    angle: "video_essay",
    description: "Forensic visual essays on Steve Ditko's Marvel, Charlton, and independent philosophical work.",
  },
  {
    name: "EISNER LEGACY DOCUMENTARIES",
    url: "https://willeisner.com/feed/",
    category: "national",
    angle: "video_essay",
    description: "The Will and Ann Eisner Family Foundation archives on the invention of the graphic novel.",
  },
  {
    name: "STERANKO AESTHETIC STUDIES",
    url: "https://sterankostudies.wordpress.com/feed/",
    category: "national",
    angle: "video_essay",
    description: "Visual analysis of Jim Steranko's pop art, op art, and cinematic page architecture.",
  },
  {
    name: "EC HORROR EXAMINATIONS",
    url: "https://ecfanaddict.wordpress.com/feed/",
    category: "national",
    angle: "video_essay",
    description: "Retrospective critical dissections of Gaines, Feldstein, Kurtzman, and Craig masterworks.",
  },
  {
    name: "MOEBIUS ODYSSEY BROADCAST",
    url: "https://moebiusodyssey.wordpress.com/feed/",
    category: "international",
    angle: "video_essay",
    description: "Jean Giraud Moebius visual tributes and surrealist sci-fi sequential documentaries.",
  },
  {
    name: "HEAVY METAL CHRONICLES",
    url: "https://heavymetalchronicles.wordpress.com/feed/",
    category: "national",
    angle: "video_essay",
    description: "The legacy of Métal Hurlant and twentieth-century speculative fantasy magazine publishing.",
  },
  {
    name: "MANGA ARCHITECTURE REVIEWS",
    url: "https://mangainsight.wordpress.com/feed/",
    category: "international",
    angle: "video_essay",
    description: "Tezuka, Otomo, Miura, and Urasawa visual framing and dynamic speedline analysis.",
  },
  {
    name: "BD PASSION EUROPE",
    url: "https://bdpassion.canalblog.com/rss.xml",
    category: "international",
    angle: "video_essay",
    description: "Video and blog retrospectives on the Franco-Belgian clear line (ligne claire) tradition.",
  },
  {
    name: "CREATIVE LETTERING FORUM",
    url: "https://blambot.com/blogs/blambot-blog.atom",
    category: "national",
    angle: "video_essay",
    description: "Nate Piekos of Blambot on comic lettering craft, sound effects design, and balloon placement.",
  },
  {
    name: "PANEL BY PANEL BREAKDOWN",
    url: "https://panelbypanel.wordpress.com/feed/",
    category: "national",
    angle: "video_essay",
    description: "Detailed panel-by-panel script-to-art translation case studies.",
  },
  {
    name: "THE COMIC BOOK WORKSHOP",
    url: "https://comicbookworkshop.wordpress.com/feed/",
    category: "national",
    angle: "video_essay",
    description: "Professional drafting techniques, perspective grids, and thumbnailing strategies.",
  },
  {
    name: "INK AND PAINT LEGENDS",
    url: "https://inkandpaintlegends.wordpress.com/feed/",
    category: "national",
    angle: "video_essay",
    description: "Documentary spotlights on classic Silver and Bronze Age inkers and color separators.",
  },
  {
    name: "DC UNIVERSE INFINITE SPOTLIGHTS",
    url: "https://www.dc.com/blog/rss",
    category: "national",
    angle: "video_essay",
    description: "Official DC Comics creative team interviews, variant covers, and archival announcements.",
  },
  {
    name: "MARVEL METHOD CHRONICLES",
    url: "https://marvelmethodchronicles.wordpress.com/feed/",
    category: "national",
    angle: "video_essay",
    description: "Historical examinations of Stan Lee, Jack Kirby, and Steve Ditko collaboration models.",
  },
  {
    name: "INDIE COMIC REVIEW SHOW",
    url: "https://indiecomicreview.wordpress.com/feed/",
    category: "national",
    angle: "video_essay",
    description: "Small press, self-published, and Kickstarter comic book video reviews.",
  },
  {
    name: "WEBTOON CREATOR TALKS",
    url: "https://webtooncreators.wordpress.com/feed/",
    category: "international",
    angle: "video_essay",
    description: "Vertical scroll visual composition, digital coloring workflows, and Korean webcomic trends.",
  },
  {
    name: "COMIC CENSUS VAULT",
    url: "https://comiccensusvault.wordpress.com/feed/",
    category: "national",
    angle: "video_essay",
    description: "Population report analysis, census tier rarities, and 9.8 survival rate calculations.",
  },
  {
    name: "PEDIGREE ARCHIVE INVESTIGATIONS",
    url: "https://pedigreearchive.wordpress.com/feed/",
    category: "national",
    angle: "video_essay",
    description: "Case studies on Mile High, San Francisco, Allentown, and Church pedigree provenances.",
  },
  {
    name: "PANEL PROFITS FORENSIC STREAM",
    url: "https://comicbookstockexchange.com/api/news/feed",
    category: "national",
    angle: "video_essay",
    description: "Live Panel Profits broadcast telemetry stream for verified secondary comic equities.",
  },

  // =========================================================================
  // 3. CREATOR SUBSTACKS & PRO NEWSLETTERS (65 Outlets)
  // =========================================================================
  {
    name: "JONATHAN HICKMAN: 3W3M",
    url: "https://3w3m.substack.com/feed",
    category: "national",
    angle: "creator_newsletter",
    description: "Jonathan Hickman, Mike del Mundo, and Mike Huddleston building interconnected comic worlds.",
  },
  {
    name: "JAMES TYNION IV: THE EMPIRE OF THE TINY ONION",
    url: "https://jamestynioniv.substack.com/feed",
    category: "national",
    angle: "creator_newsletter",
    description: "Eisner-winner James Tynion IV on independent comic publishing, W0rldtr33, and Department of Truth.",
  },
  {
    name: "SCOTT SNYDER: OUR BEST JACKET",
    url: "https://bestjacketpress.substack.com/feed",
    category: "national",
    angle: "creator_newsletter",
    description: "Scott Snyder on scriptcraft, creator-owned comic models, and Dark Spaces.",
  },
  {
    name: "CHIP ZDARSKY: IT'S CHIP ZDARSKY'S NEWSLETTER, OKAY?",
    url: "https://zdarsky.substack.com/feed",
    category: "national",
    angle: "creator_newsletter",
    description: "Chip Zdarsky on Batman, Public Domain, Newburn, and comic industry absurdities.",
  },
  {
    name: "KELLY SUE DECONNICK & MATT FRACTION: MILKFED CRIMINALS",
    url: "https://milkfed.substack.com/feed",
    category: "national",
    angle: "creator_newsletter",
    description: "Kelly Sue DeConnick and Matt Fraction on Sex Criminals, Bitch Planet, and storytelling craft.",
  },
  {
    name: "JEFF LEMIRE: TALES FROM THE FARM",
    url: "https://jefflemire.substack.com/feed",
    category: "national",
    angle: "creator_newsletter",
    description: "Jeff Lemire on Sweet Tooth, Black Hammer, watercolor techniques, and serialized storytelling.",
  },
  {
    name: "TOM KING: EVERLASTING PRODUCTIONS",
    url: "https://tomking.substack.com/feed",
    category: "national",
    angle: "creator_newsletter",
    description: "Tom King on Mister Miracle, Supergirl, Helen of Wyndhorn, and twelve-issue maxiseries architecture.",
  },
  {
    name: "BRIAN MICHAEL BENDIS: JINXWORLD",
    url: "https://brianmichaelbendis.substack.com/feed",
    category: "national",
    angle: "creator_newsletter",
    description: "Brian Michael Bendis on comic dialogue, Ultimate Marvel history, and creator collaborations.",
  },
  {
    name: "ED BRUBAKER: FROM THE DESK OF ED BRUBAKER",
    url: "https://edbrubaker.substack.com/feed",
    category: "national",
    angle: "creator_newsletter",
    description: "Ed Brubaker on Reckless, Criminal, noir fiction, and hardboiled sequential storytelling.",
  },
  {
    name: "KIERON GILLEN: WORD SAVERY",
    url: "https://kierongillen.substack.com/feed",
    category: "international",
    angle: "creator_newsletter",
    description: "Kieron Gillen on The Wicked + The Divine, DIE, Uber, and game theory in comic writing.",
  },
  {
    name: "WARREN ELLIS: ORBITAL OPERATIONS",
    url: "https://orbitaloperations.substack.com/feed",
    category: "international",
    angle: "creator_newsletter",
    description: "Warren Ellis on speculative futures, Transmetropolitan, Planetary, and digital culture.",
  },
  {
    name: "GAIL SIMONE: YOU'VE GOT GAIL",
    url: "https://gailsimone.substack.com/feed",
    category: "national",
    angle: "creator_newsletter",
    description: "Gail Simone on Birds of Prey, Secret Six, Uncanny X-Men, and industry perspectives.",
  },
  {
    name: "GARY GROTH: THE COMICS JOURNAL EDITORIAL",
    url: "https://www.tcj.com/feed/",
    category: "national",
    angle: "creator_newsletter",
    description: "Gary Groth's seminal critical journal covering independent cartooning and comic history.",
  },
  {
    name: "MARGUERITE BENNETT: MONSTERPOCKET",
    url: "https://margueritebennett.substack.com/feed",
    category: "national",
    angle: "creator_newsletter",
    description: "Marguerite Bennett on Animosity, DC Bombshells, worldbuilding, and queer representation.",
  },
  {
    name: "DONNY CATES: PROOF OF LIFE",
    url: "https://donnycates.substack.com/feed",
    category: "national",
    angle: "creator_newsletter",
    description: "Donny Cates on Venom, God Country, Thor, and independent comic publishing.",
  },
  {
    name: "AL EWING: COSMIC DIALECTICS",
    url: "https://alewing.substack.com/feed",
    category: "international",
    angle: "creator_newsletter",
    description: "Al Ewing on Immortal Hulk, Ultimates, cosmic Marvel mythology, and metaphysical narrative.",
  },
  {
    name: "RAM V: THE SCENIC ROUTE",
    url: "https://ramv.substack.com/feed",
    category: "international",
    angle: "creator_newsletter",
    description: "Ram V on The Many Deaths of Laila Starr, Swamp Thing, Detective Comics, and poetic pacing.",
  },
  {
    name: "DANIEL WARREN JOHNSON: SPACE-MULLET",
    url: "https://danielwarrenjohnson.substack.com/feed",
    category: "national",
    angle: "creator_newsletter",
    description: "Daniel Warren Johnson on Transformers, Do a Powerbomb!, Murder Falcon, and raw brush inking.",
  },
  {
    name: "SKOTTIE YOUNG: STUPID FRESH MESS",
    url: "https://skottieyoung.substack.com/feed",
    category: "national",
    angle: "creator_newsletter",
    description: "Skottie Young on I Hate Fairyland, Middlewest, variant cover art, and creative independence.",
  },
  {
    name: "JOSHUA WILLIAMSON: RUNNING IN THE RED",
    url: "https://joshuawilliamson.substack.com/feed",
    category: "national",
    angle: "creator_newsletter",
    description: "Joshua Williamson on The Flash, G.I. Joe, Cobra Commander, and DC line architecture.",
  },
  {
    name: "CHRIS CONDON: THAT TEXAS DISPATCH",
    url: "https://chriscondon.substack.com/feed",
    category: "national",
    angle: "creator_newsletter",
    description: "Chris Condon on That Texas Blood, The Enfield Gang Massacre, and western comic noir.",
  },
  {
    name: "MATTHEW ROSENBERG: ASHCAN",
    url: "https://matthewrosenberg.substack.com/feed",
    category: "national",
    angle: "creator_newsletter",
    description: "Matthew Rosenberg on 4 Kids Walk Into a Bank, What's the Furthest Place From Here?, and punk comics.",
  },
  {
    name: "STEPHANIE PHILLIPS: WRITING IN REVERSE",
    url: "https://stephaniephillips.substack.com/feed",
    category: "national",
    angle: "creator_newsletter",
    description: "Stephanie Phillips on Harley Quinn, Grim, Cosmic Detective, and historical research.",
  },
  {
    name: "KYLE HIGGINS: BLACK MARKET NARRATIVE",
    url: "https://blackmarket.substack.com/feed",
    category: "national",
    angle: "creator_newsletter",
    description: "Kyle Higgins on Radiant Black, the Massive-Verse, and multi-media comic creation.",
  },
  {
    name: "RODNEY BARNES: DARK RUN PRODUCTIONS",
    url: "https://rodneybarnes.substack.com/feed",
    category: "national",
    angle: "creator_newsletter",
    description: "Rodney Barnes on Killadelphia, Blacula, monster fiction, and cinematic graphic writing.",
  },
  {
    name: "PHILLIP KENNEDY JOHNSON: SMILING SHADOWS",
    url: "https://phillipkennedyjohnson.substack.com/feed",
    category: "national",
    angle: "creator_newsletter",
    description: "Phillip Kennedy Johnson on Action Comics, Alien, Green Lantern: War Journal, and worldcraft.",
  },
  {
    name: "ZACK KAPLAN: TRANSMISSION",
    url: "https://zackkaplan.substack.com/feed",
    category: "national",
    angle: "creator_newsletter",
    description: "Zack Kaplan on Port of Earth, Eclipse, Break Out, and high-concept sci-fi publishing.",
  },
  {
    name: "MARK MILLAR: MILLARWORLD DISPATCH",
    url: "https://markmillar.substack.com/feed",
    category: "international",
    angle: "creator_newsletter",
    description: "Mark Millar on Jupiter's Legacy, Kick-Ass, Nemesis, and creator-owned media rights.",
  },
  {
    name: "JERRY ORDWAY: THE LONG BOX SKETCHBOOK",
    url: "https://jerryordway.wordpress.com/feed/",
    category: "national",
    angle: "creator_newsletter",
    description: "Jerry Ordway on Crisis on Infinite Earths, The Power of Shazam!, and classic DC draftsmanship.",
  },
  {
    name: "WALT SIMONSON: RAGNAROK ARCHIVE",
    url: "https://waltsimonson.wordpress.com/feed/",
    category: "national",
    angle: "creator_newsletter",
    description: "Walter Simonson on The Mighty Thor, Manhunter, Norse mythos, and dynamic sequential layouts.",
  },
  {
    name: "BILL SIENKIEWICZ ART DISPATCH",
    url: "https://billsienkiewiczart.com/blogs/news.atom",
    category: "national",
    angle: "creator_newsletter",
    description: "Bill Sienkiewicz on Moon Knight, Elektra: Assassin, Stray Toasters, and mixed-media expressionism.",
  },
  {
    name: "COLLEEN DORAN: A DISTANT SOIL",
    url: "https://adistantsoil.com/feed/",
    category: "national",
    angle: "creator_newsletter",
    description: "Colleen Doran on pioneering creator-owned space opera, Neil Gaiman adaptations, and comic craft.",
  },
  {
    name: "PAUL LEVITZ: MANHATTAN CONTINUITY",
    url: "https://paullevitz.wordpress.com/feed/",
    category: "national",
    angle: "creator_newsletter",
    description: "Paul Levitz on Legion of Super-Heroes, DC Comics publishing history, and Golden Age legacy.",
  },
  {
    name: "KURT BUSIEK: ARROWSMITH LETTERS",
    url: "https://busiek.com/feed/",
    category: "national",
    angle: "creator_newsletter",
    description: "Kurt Busiek on Astro City, Marvels, Autumnlands, and superhero deconstruction.",
  },
  {
    name: "MARK WAID: THE INK TANK",
    url: "https://markwaid.wordpress.com/feed/",
    category: "national",
    angle: "creator_newsletter",
    description: "Mark Waid on Kingdom Come, Flash: Born to Run, Daredevil, and DC editorial history.",
  },
  {
    name: "J.M. DEMATTEIS: CREATION POINT",
    url: "https://jmdematteis.blogspot.com/feeds/posts/default?alt=rss",
    category: "national",
    angle: "creator_newsletter",
    description: "J.M. DeMatteis on Kraven's Last Hunt, Justice League International, and psychological depth.",
  },
  {
    name: "CLIFF CHIANG: PAPER GIRLS STUDIO",
    url: "https://cliffchiang.com/feed/",
    category: "national",
    angle: "creator_newsletter",
    description: "Cliff Chiang on Paper Girls, Catwoman: Lonely City, color theory, and line weight.",
  },
  {
    name: "BECKY CLOONAN: STUDIO PUNX",
    url: "https://beckycloonan.wordpress.com/feed/",
    category: "national",
    angle: "creator_newsletter",
    description: "Becky Cloonan on Gotham Academy, The True Lives of the Fabulous Killjoys, and mini-comics.",
  },
  {
    name: "MITCH GERADS: TACTICAL SEQUENTIAL",
    url: "https://mitchgerads.wordpress.com/feed/",
    category: "national",
    angle: "creator_newsletter",
    description: "Mitch Gerads on Mister Miracle, Strange Adventures, The Sheriff of Babylon, and photoreal inking.",
  },
  {
    name: "DOC SHANER: SKYWARD ADVENTURES",
    url: "https://docshaner.wordpress.com/feed/",
    category: "national",
    angle: "creator_newsletter",
    description: "Evan 'Doc' Shaner on Captain Marvel, Green Lantern: Earth One, and Silver Age purity.",
  },
  {
    name: "DECLAN SHALVEY: DRAWING LINES",
    url: "https://declanshalvey.substack.com/feed",
    category: "international",
    angle: "creator_newsletter",
    description: "Declan Shalvey on Moon Knight, Injection, Old Dog, Alien, and Irish comic publishing.",
  },
  {
    name: "CHRISTIAN WARD: COSMIC PSYCHEDELIA",
    url: "https://christianward.substack.com/feed",
    category: "international",
    angle: "creator_newsletter",
    description: "Christian Ward on ODY-C, Invisible Kingdom, Batman: City of Madness, and chromatic palettes.",
  },
  {
    name: "JOCK: 400 FLOOD",
    url: "https://400flood.com/feed/",
    category: "international",
    angle: "creator_newsletter",
    description: "Jock (Mark Simpson) on Batman: The Black Mirror, Wytches, 2000 AD, and film concept art.",
  },
  {
    name: "SEAN PHILLIPS: COLD CRIME SKETCHES",
    url: "https://seanphillips.wordpress.com/feed/",
    category: "international",
    angle: "creator_newsletter",
    description: "Sean Phillips on Criminal, The Fade Out, Pulp, and atmospheric European-inspired shadows.",
  },
  {
    name: "GABRIEL HERNANDEZ WALTA: SUBTERRANEAN LINES",
    url: "https://walta.wordpress.com/feed/",
    category: "international",
    angle: "creator_newsletter",
    description: "Gabriel Hernandez Walta on The Vision, Sentient, Hellboy, and subtle emotional characterization.",
  },
  {
    name: "JAMIE DELANO: STRANGE DAYS",
    url: "https://jamiedelano.wordpress.com/feed/",
    category: "international",
    angle: "creator_newsletter",
    description: "Jamie Delano on Hellblazer, Vertigo origins, Swamp Thing, and British speculative fiction.",
  },
  {
    name: "PETER MILLIGAN: SUBVERSIVE SCRIPTS",
    url: "https://petermilligan.wordpress.com/feed/",
    category: "international",
    angle: "creator_newsletter",
    description: "Peter Milligan on Shade The Changing Man, X-Statix, Enigma, and post-punk comic subversion.",
  },
  {
    name: "JOHN BYRNE: BYRNE ROBOTICS FORUM",
    url: "https://byrnerobotics.com/forum/feed.php",
    category: "national",
    angle: "creator_newsletter",
    description: "John Byrne's primary creator forum covering X-Men, Fantastic Four, Superman: Man of Steel, and Next Men.",
  },
  {
    name: "DAVE GIBBONS: WATCHMAKER DISPATCH",
    url: "https://davegibbons.wordpress.com/feed/",
    category: "international",
    angle: "creator_newsletter",
    description: "Dave Gibbons on Watchmen formal design, 9-panel grids, Rogue Trooper, and digital lettering.",
  },
  {
    name: "ALAN MOORE ARCHIVAL LETTERS",
    url: "https://alanmoorechronicles.wordpress.com/feed/",
    category: "international",
    angle: "creator_newsletter",
    description: "Documentary repository and transcription archive of Alan Moore's interviews, essays, and lectures.",
  },
  {
    name: "NEIL GAIMAN JOURNAL",
    url: "https://journal.neilgaiman.com/feeds/posts/default?alt=rss",
    category: "international",
    angle: "creator_newsletter",
    description: "Neil Gaiman on Sandman, mythology, graphic adaptation, and literary sequential craft.",
  },
  {
    name: "MIKE MIGNOLA: HELLBOY FORUM",
    url: "https://artofmikemignola.com/feed/",
    category: "national",
    angle: "creator_newsletter",
    description: "Mike Mignola on Hellboy, the B.P.R.D. universe, chiaroscuro inks, and gothic folklore.",
  },
  {
    name: "STAN SAKAI: USAGI YOJIMBO CHRONICLES",
    url: "https://stansakai.com/feed/",
    category: "national",
    angle: "creator_newsletter",
    description: "Stan Sakai on Usagi Yojimbo historical research, ink brush calligraphy, and Edo-period Japan.",
  },
  {
    name: "SERGIO ARAGONES: GROO NEWS",
    url: "https://sergioaragones.com/feed/",
    category: "national",
    angle: "creator_newsletter",
    description: "Sergio Aragonés on MAD Magazine marginals, Groo the Wanderer, and spontaneous pantomime gag cartooning.",
  },
  {
    name: "JIM LEE: WILDSTORM RECOLLECTIONS",
    url: "https://jimlee.wordpress.com/feed/",
    category: "national",
    angle: "creator_newsletter",
    description: "Jim Lee on X-Men #1, WildC.A.T.s, Image Comics inception, and DC editorial leadership.",
  },
  {
    name: "TODD MCFARLANE: SPAWN DISPATCH",
    url: "https://mcfarlane.com/news/feed/",
    category: "national",
    angle: "creator_newsletter",
    description: "Todd McFarlane on Spawn, creator rights, dynamic cross-hatching, and toy architecture.",
  },
  {
    name: "ERIK LARSEN: SAVAGE DRAGON ARCHIVE",
    url: "https://savagedragon.com/feed/",
    category: "national",
    angle: "creator_newsletter",
    description: "Erik Larsen on 300+ uninterrupted issues of Savage Dragon, Image Comics history, and Jack Kirby influence.",
  },
  {
    name: "MARC SILVESTRI: TOP COW PULSE",
    url: "https://topcow.com/feed/",
    category: "national",
    angle: "creator_newsletter",
    description: "Marc Silvestri on Cyberforce, Witchblade, The Darkness, and studio comic production.",
  },
  {
    name: "ROB LIEFELD: ROBERVATIONS",
    url: "https://robliefeldcreations.com/feed/",
    category: "national",
    angle: "creator_newsletter",
    description: "Rob Liefeld on Youngblood, Deadpool, X-Force, and the explosive energy of the early 1990s boom.",
  },
  {
    name: "JIM VALENTINO: SHADOWHAWK FORUM",
    url: "https://shadowhawk.com/feed/",
    category: "national",
    angle: "creator_newsletter",
    description: "Jim Valentino on Shadowline, Guardians of the Galaxy, and the birth of Image Comics.",
  },
  {
    name: "WHILCE PORTACIO: BISHOP FORUM",
    url: "https://whilceportacio.wordpress.com/feed/",
    category: "national",
    angle: "creator_newsletter",
    description: "Whilce Portacio on Wetworks, Bishop, Punisher, and mentoring Asian-American sequential artists.",
  },
  {
    name: "TERRY MOORE: STRANGERS IN PARADISE CHRONICLES",
    url: "https://terrymooreart.com/feed/",
    category: "national",
    angle: "creator_newsletter",
    description: "Terry Moore on self-publishing Strangers in Paradise, Echo, Rachel Rising, and independent survival.",
  },
  {
    name: "JEFF SMITH: BONE ARCHIVE",
    url: "https://cartoonbooks.com/feed/",
    category: "national",
    angle: "creator_newsletter",
    description: "Jeff Smith on self-publishing BONE, RASL, TUKI, and cartooning craft.",
  },
  {
    name: "CHRIS WARE: THE ACME NOVELTY LETTERS",
    url: "https://acmenovelty.wordpress.com/feed/",
    category: "national",
    angle: "creator_newsletter",
    description: "Chris Ware on Jimmy Corrigan, Building Stories, typographic architecture, and physical bookcraft.",
  },
  {
    name: "DANIEL CLOWES: EIGHTBALL FORUM",
    url: "https://danielclowes.wordpress.com/feed/",
    category: "national",
    angle: "creator_newsletter",
    description: "Daniel Clowes on Ghost World, Monica, David Boring, and mid-century satirical cartooning.",
  },

  // =========================================================================
  // 4. SECONDARY MARKET, INDUSTRY TRADES & CRITICAL REVIEWS (65 Outlets)
  // =========================================================================
  {
    name: "COMICBOOK INVEST",
    url: "https://comicbookinvest.com/feed/",
    category: "national",
    angle: "secondary_market",
    description: "Key issue print run investigations, market trends, and first appearance checklists.",
  },
  {
    name: "GOCOLLECT BLOG",
    url: "https://gocollect.com/blog/feed",
    category: "national",
    angle: "secondary_market",
    description: "CGC sales analysis, cold market buys, record auction results, and market sentiment.",
  },
  {
    name: "COVRPRICE BLOG",
    url: "https://covrprice.com/feed/",
    category: "national",
    angle: "secondary_market",
    description: "Top 10 daily comic movers, trend reports, and secondary market sales velocity.",
  },
  {
    name: "COMIC BOOK HERALD",
    url: "https://www.comicbookherald.com/feed/",
    category: "national",
    angle: "critical_review",
    description: "Dave Buesing's complete Marvel & DC reading orders, story event timelines, and collected editions.",
  },
  {
    name: "COMICHRON HISTORICAL DATA",
    url: "https://blog.comichron.com/feeds/posts/default?alt=rss",
    category: "national",
    angle: "secondary_market",
    description: "John Jackson Miller's historical sales numbers, print run estimations, and circulation records.",
  },
  {
    name: "THE OVERSTREET DISPATCH",
    url: "https://gemstonepub.com/feed/",
    category: "national",
    angle: "secondary_market",
    description: "The official blog of the Overstreet Comic Book Price Guide and Gemstone Publishing.",
  },
  {
    name: "CGC COMICS NEWS",
    url: "https://www.cgccomics.com/news/rss/",
    category: "national",
    angle: "secondary_market",
    description: "Certified Guaranty Company registry announcements, signature series signings, and population updates.",
  },
  {
    name: "CBCS COMICS NEWS",
    url: "https://www.cbcscomics.com/blog/feed/",
    category: "national",
    angle: "secondary_market",
    description: "Comic Book Certification Service verified signature programs and grading population news.",
  },
  {
    name: "HERITAGE COMICS AUCTION PRESS",
    url: "https://www.ha.com/c/rss/news.zx?type=rss",
    category: "national",
    angle: "secondary_market",
    description: "Official auction catalog alerts for million-dollar Golden Age pedigrees and original art.",
  },
  {
    name: "COMICLINK EXCHANGE SPOTLIGHTS",
    url: "https://www.comiclink.com/rss/news.xml",
    category: "national",
    angle: "secondary_market",
    description: "Certified auction results, focused exchange highlights, and private transaction clearing reports.",
  },
  {
    name: "COMICCONNECT PULSE",
    url: "https://www.comicconnect.com/rss/news",
    category: "national",
    angle: "secondary_market",
    description: "Event auction announcements, Guinness World Record sales, and vintage pedigree consignments.",
  },
  {
    name: "SHORTBOXED VAULT",
    url: "https://shortboxed.com/feed/",
    category: "national",
    angle: "secondary_market",
    description: "Graded comic market liquidity, mobile marketplace velocity, and collector app updates.",
  },
  {
    name: "KEY COLLECTOR COMICS BLOG",
    url: "https://keycollectorcomics.com/feed/",
    category: "national",
    angle: "secondary_market",
    description: "Key issue database updates, MCU/DCU speculative catalysts, and character debut crosswalks.",
  },
  {
    name: "PREVIEWS WORLD CATALOG",
    url: "https://www.previewsworld.com/rss",
    category: "national",
    angle: "industry_trade",
    description: "Direct market comic distribution solicitations, FOC order deadlines, and variant incentives.",
  },
  {
    name: "LUNAR DISTRIBUTION ALERTS",
    url: "https://www.lunardistribution.com/news/feed",
    category: "national",
    angle: "industry_trade",
    description: "DC Comics and Image Comics primary direct market logistics and inventory allocations.",
  },
  {
    name: "PRH COMICS RETAIL DISPATCH",
    url: "https://prhcomics.com/feed/",
    category: "national",
    angle: "industry_trade",
    description: "Penguin Random House direct market distribution announcements for Marvel, IDW, and Dark Horse.",
  },
  {
    name: "UNIVERSAL DISTRIBUTION BULLETINS",
    url: "https://universaldist.com/feed/",
    category: "international",
    angle: "industry_trade",
    description: "Canadian direct market distribution news, hobby store inventory, and convention logistics.",
  },
  {
    name: "DIAMOND GALLERIES VINTAGE VAULT",
    url: "https://diamondgalleries.com/feed/",
    category: "national",
    angle: "industry_trade",
    description: "Steve Geppi's classic Golden and Silver Age comic museum and gallery collection updates.",
  },
  {
    name: "PEDIGREE COMICS DISPATCH",
    url: "https://pedigreecomics.com/rss.xml",
    category: "national",
    angle: "secondary_market",
    description: "High-grade Silver and Bronze Age certified CGC investment grade consignment sales.",
  },
  {
    name: "METROPOLIS COMICS BLOG",
    url: "https://www.metropoliscomics.com/feed",
    category: "national",
    angle: "secondary_market",
    description: "Vincent Zurzolo's vintage comic market commentary and Action Comics #1 provenance history.",
  },
  {
    name: "MYCOMICSHOP DEALER DISPATCH",
    url: "https://www.mycomicshop.com/rss/news.xml",
    category: "national",
    angle: "secondary_market",
    description: "Lone Star Comics weekly auctions, inventory buying lists, and back-issue catalog updates.",
  },
  {
    name: "MIDTOWN COMICS COLLECTOR BLOG",
    url: "https://blog.midtowncomics.com/feed/",
    category: "national",
    angle: "industry_trade",
    description: "New York retail perspective, exclusive store variant launches, and collector spotlights.",
  },
  {
    name: "MILE HIGH COMICS NEWSLETTERS",
    url: "https://www.milehighcomics.com/newsletters.atom",
    category: "national",
    angle: "industry_trade",
    description: "Chuck Rozanski's historical memoirs, warehouse unearthings, and direct market pioneer history.",
  },
  {
    name: "TORPEDO COMICS PULSE",
    url: "https://torpedocomics.com/feed/",
    category: "national",
    angle: "industry_trade",
    description: "West Coast key comic conventions, blue-chip investments, and certified 9.8 inventory.",
  },
  {
    name: "NEW KADIA VINTAGE LOG",
    url: "https://www.newkadia.com/feed",
    category: "national",
    angle: "collector_blog",
    description: "Online back issue grading standards, preservation supplies, and paper degradation studies.",
  },
  {
    name: "WESTFIELD COMICS BLOG",
    url: "https://westfieldcomics.com/blog/feed/",
    category: "national",
    angle: "industry_trade",
    description: "Monthly advance order recommendations and long-running direct sales mail order retrospectives.",
  },
  {
    name: "FANTAGRAPHICS BOOKS BLOG",
    url: "https://www.fantagraphics.com/blogs/flog.atom",
    category: "national",
    angle: "publisher_bulletin",
    description: "The seminal indie comics publisher blog covering archival reprints, Love and Rockets, and cartoonists.",
  },
  {
    name: "DRAWN & QUARTERLY DISPATCH",
    url: "https://drawnandquarterly.com/feed/",
    category: "international",
    angle: "publisher_bulletin",
    description: "Montreal-based literary graphic novel publisher news, international licensing, and creator tours.",
  },
  {
    name: "KODANSHA COMICS NEWS",
    url: "https://kodansha.us/feed/",
    category: "international",
    angle: "publisher_bulletin",
    description: "Official Japanese manga English editions, digital releases, and localization announcements.",
  },
  {
    name: "VIZ MEDIA NEWSROOM",
    url: "https://www.viz.com/feed/news",
    category: "national",
    angle: "publisher_bulletin",
    description: "Shonen Jump, Shojo Beat, and award-winning manga serialization announcements.",
  },
  {
    name: "DARK HORSE DIRECT BLOG",
    url: "https://www.darkhorse.com/Blog/rss",
    category: "national",
    angle: "publisher_bulletin",
    description: "Hellboy, Sin City, Usagi Yojimbo, and licensed graphic novel release bulletins.",
  },
  {
    name: "IMAGE COMICS OFFICIAL BULLETINS",
    url: "https://imagecomics.com/news.atom",
    category: "national",
    angle: "publisher_bulletin",
    description: "Creator-owned press releases, reprint printings, and launch solicits.",
  },
  {
    name: "2000 AD GALAXY'S GREATEST",
    url: "https://2000ad.com/news/feed/",
    category: "international",
    angle: "publisher_bulletin",
    description: "Judge Dredd, Sláine, Strontium Dog, and Rebellion Publishing British sci-fi comics.",
  },
  {
    name: "REBELLION PUBLISHING NEWS",
    url: "https://rebellionpublishing.com/feed/",
    category: "international",
    angle: "publisher_bulletin",
    description: "Treasury of British Comics archival restorations, Roy of the Rovers, and classic UK graphic heritage.",
  },
  {
    name: "EUROPE COMICS DISPATCH",
    url: "https://www.europecomics.com/feed/",
    category: "international",
    angle: "publisher_bulletin",
    description: "Digital translations of premier French, Belgian, Spanish, and Italian graphic novels.",
  },
  {
    name: "CINEBOOK THE 9TH ART",
    url: "https://www.cinebook.co.uk/rss.php",
    category: "international",
    angle: "publisher_bulletin",
    description: "English translations of classic European series including Lucky Luke, Blake and Mortimer, and Thorgal.",
  },
  {
    name: "HEAVY METAL MAGAZINE NEWS",
    url: "https://www.heavymetal.com/feed/",
    category: "national",
    angle: "publisher_bulletin",
    description: "Sci-fi and fantasy graphic magazine releases, original art retrospectives, and studio adaptations.",
  },
  {
    name: "MAD MAGAZINE HISTORICAL VAULT",
    url: "https://madmagazine.wordpress.com/feed/",
    category: "national",
    angle: "critical_review",
    description: "Historical satirical analysis of William M. Gaines, Al Feldstein, and the usual gang of idiots.",
  },
  {
    name: "HEAVY INK RETRO ARCHIVE",
    url: "https://heavyink.wordpress.com/feed/",
    category: "national",
    angle: "industry_trade",
    description: "Comic book pull list analytics, subscriber ordering patterns, and back issue preservation.",
  },
  {
    name: "COMIC PRICE ENGINE BLOG",
    url: "https://comicpriceguide.wordpress.com/feed/",
    category: "national",
    angle: "secondary_market",
    description: "Predictive econometric models applied to key first appearance auction realization histories.",
  },
  {
    name: "RAW COMICS PRESERVATION BLOG",
    url: "https://rawcomicspreservation.wordpress.com/feed/",
    category: "national",
    angle: "collector_blog",
    description: "Microchamber paper, mylar archival sleeves, acid-free backing boards, and humidity curation.",
  },
  {
    name: "PRESSING & CLEANING FORENSICS",
    url: "https://comicpressingforensics.wordpress.com/feed/",
    category: "national",
    angle: "collector_blog",
    description: "Thermal heat press curves, dry cleaning protocols, and non-invasive restoration detection.",
  },
  {
    name: "PEDIGREE DETECTIVES",
    url: "https://pedigreedetectives.wordpress.com/feed/",
    category: "national",
    angle: "secondary_market",
    description: "Investigating the origins of church pedigrees, Edgar Church collections, and Golden Age estate finds.",
  },
  {
    name: "THE PROMISE COLLECTION VAULT",
    url: "https://promisecollection.wordpress.com/feed/",
    category: "national",
    angle: "secondary_market",
    description: "Analysis of the 5,000-book high-grade 1940s estate collection with pristine white pages.",
  },
  {
    name: "NORTHLAND COLLECTION LOGS",
    url: "https://northlandcollection.wordpress.com/feed/",
    category: "national",
    angle: "collector_blog",
    description: "Uncataloged Canadian whites, American editions, and wartime distribution anomalies.",
  },
  {
    name: "CANADIAN WHITES ARCHIVE",
    url: "https://canadianwhites.wordpress.com/feed/",
    category: "international",
    angle: "collector_blog",
    description: "Historical research into 1941-1946 War Exchange Conservation Act wartime comic production.",
  },
  {
    name: "AUSTRALIAN REPRINT TRACKER",
    url: "https://australianreprints.wordpress.com/feed/",
    category: "international",
    angle: "collector_blog",
    description: "Tracking K.G. Murray, Yaffa, and Newton black-and-white regional reprint editions.",
  },
  {
    name: "BRITISH PRICE VARIANT (BPV) REGISTRY",
    url: "https://britishpricevariants.wordpress.com/feed/",
    category: "international",
    angle: "collector_blog",
    description: "Census documentation of Marvel and DC UK cover price variants printed at the same time in the US.",
  },
  {
    name: "NEWSSTAND VS DIRECT MARKET STUDY",
    url: "https://newsstandvariants.wordpress.com/feed/",
    category: "national",
    angle: "collector_blog",
    description: "Rarity studies examining UPC barcode newsstand surviving populations from 1986 to 2013.",
  },
  {
    name: "MARK JEWELERS INSERT CENSUS",
    url: "https://markjewelersinsert.wordpress.com/feed/",
    category: "national",
    angle: "collector_blog",
    description: "Tracking rare military base insert editions distributed to US troops overseas from 1972 to 1991.",
  },
  {
    name: "WHITMAN VARIANT CATALOG",
    url: "https://whitmanvariants.wordpress.com/feed/",
    category: "national",
    angle: "collector_blog",
    description: "Documenting diamond logo, blank UPC box, and multi-pack editions from Western Publishing (1979-1982).",
  },
  {
    name: "PRICE ALTERATION VARIANT LOG",
    url: "https://pricevariants.wordpress.com/feed/",
    category: "national",
    angle: "secondary_market",
    description: "Tracking 30¢, 35¢, and 75¢ test market comic price variants in selective test cities.",
  },
  {
    name: "ORIGINAL COMIC ART TRACER",
    url: "https://www.comicartfans.com/rss/CAFNews.xml",
    category: "national",
    angle: "secondary_market",
    description: "The primary community hub for original comic art collectors, sketch covers, and master splash pages.",
  },
  {
    name: "SPLASH PAGE ORIGINAL ART NEWS",
    url: "https://splashpageart.wordpress.com/feed/",
    category: "national",
    angle: "secondary_market",
    description: "Artist representative updates for high-profile comic illustrators, covers, and interior panels.",
  },
  {
    name: "ALBERTO BECATTINI COMICS LOG",
    url: "https://becattinibrass.wordpress.com/feed/",
    category: "international",
    angle: "critical_review",
    description: "Forensic creator attribution research across twentieth-century Disney, Dell, and Gold Key comic lines.",
  },
  {
    name: "WHO'S OUT THERE COMIC DETECTIVE",
    url: "https://whosouttherecomics.wordpress.com/feed/",
    category: "national",
    angle: "critical_review",
    description: "Tracing obscure pseudonyms, ghost artists, and uncredited studio assists in Golden Age books.",
  },
  {
    name: "GOLDEN AGE COMIC ARCHIVE",
    url: "https://goldenagecomics.wordpress.com/feed/",
    category: "national",
    angle: "critical_review",
    description: "Public domain comic scans, high-resolution color restoration, and forgotten superhero revivals.",
  },
  {
    name: "SILVER AGE MARVEL CONTINUITY",
    url: "https://silveragecontinuity.wordpress.com/feed/",
    category: "national",
    angle: "critical_review",
    description: "Chronological mapping of Marvel Comics Earth-616 continuity from Fantastic Four #1 (1961) onward.",
  },
  {
    name: "BRONZE AGE REVOLUTION",
    url: "https://bronzeagerevolution.wordpress.com/feed/",
    category: "national",
    angle: "critical_review",
    description: "Retrospective analysis of the shift from the Comics Code Authority to socially relevant storytelling (1970-1985).",
  },
  {
    name: "COPPER AGE DISPATCH",
    url: "https://copperagecomics.wordpress.com/feed/",
    category: "national",
    angle: "critical_review",
    description: "Exploration of the direct market birth, independent publishing explosion, and dark modern grimness (1984-1991).",
  },
  {
    name: "MODERN FIRST APPEARANCES LOG",
    url: "https://modernfirstappearances.wordpress.com/feed/",
    category: "national",
    angle: "critical_review",
    description: "Tracking 21st-century debut keys from Miles Morales and Kamala Khan to Knull and Cosmic Ghost Rider.",
  },
  {
    name: "INDEPENDENT CARTOONIST REVIEW",
    url: "https://independentcartoonist.wordpress.com/feed/",
    category: "national",
    angle: "critical_review",
    description: "Zines, risograph mini-comics, Ignatz award nominees, and SPX (Small Press Expo) coverage.",
  },
  {
    name: "WOMEN IN COMICS RESEARCH NETWORK",
    url: "https://womenincomics.wordpress.com/feed/",
    category: "national",
    angle: "critical_review",
    description: "Historical documentation of pioneering women creators from Nell Brinkley and Tarpe Mills to Ramona Fradon.",
  },
  {
    name: "BLACK COMIC CREATOR COLLECTIVE",
    url: "https://blackcomiccreators.wordpress.com/feed/",
    category: "national",
    angle: "critical_review",
    description: "Spotlighting Black cartoonists, Milestone Media legacy, and independent Afrofuturist sequential titles.",
  },
  {
    name: "QUEER COMICS CULTURE ARCHIVE",
    url: "https://queercomicsculture.wordpress.com/feed/",
    category: "national",
    angle: "critical_review",
    description: "History of LGBTQ+ themes, underground comix pioneers, and contemporary inclusive graphic narratives.",
  },
];

/**
 * Direct alias for CURATED_FEEDS satisfying both naming conventions.
 */
export const CURATED_FEEDS: CuratedNewsSource[] = CURATED_CHANNELS;
