export interface EntityWikiDef {
  term: string;
  ticker?: string;
  type: "character" | "publisher" | "equity" | "creator" | "market-concept" | "grading" | "lexicon";
  target: "intelligence" | "lexicon"; // 'intelligence' = CBR Intelligence (Lore/Creators), 'lexicon' = CBR Financial Lexicon
  wikiPath: string;
}

export const KNOWN_NEWS_ENTITIES_MAP: EntityWikiDef[] = [
  // --- REAL WORLD CORPORATE & MEDIA EQUITIES (CBR Financial Lexicon -> Real Stock Tickers) ---
  { term: "HBO Max", ticker: "WBD:MAX", type: "equity", target: "lexicon", wikiPath: "/lexicon?q=HBO%20Max" },
  { term: "Max", ticker: "WBD:MAX", type: "equity", target: "lexicon", wikiPath: "/lexicon?q=Max" },
  { term: "Disney", ticker: "DIS", type: "equity", target: "lexicon", wikiPath: "/lexicon?q=Disney" },
  { term: "Marvel Studios", ticker: "DIS:MARVEL", type: "equity", target: "lexicon", wikiPath: "/lexicon?q=Marvel%20Studios" },
  { term: "Warner Bros", ticker: "WBD", type: "equity", target: "lexicon", wikiPath: "/lexicon?q=Warner%20Bros" },
  { term: "Warner Bros Discovery", ticker: "WBD", type: "equity", target: "lexicon", wikiPath: "/lexicon?q=Warner%20Bros" },
  { term: "DC Studios", ticker: "WBD:DC", type: "equity", target: "lexicon", wikiPath: "/lexicon?q=DC%20Studios" },
  { term: "Sony Pictures", ticker: "SONY", type: "equity", target: "lexicon", wikiPath: "/lexicon?q=Sony" },
  { term: "Paramount", ticker: "PARA", type: "equity", target: "lexicon", wikiPath: "/lexicon?q=Paramount" },
  { term: "Universal Pictures", ticker: "CMCSA", type: "equity", target: "lexicon", wikiPath: "/lexicon?q=Universal" },
  { term: "Netflix", ticker: "NFLX", type: "equity", target: "lexicon", wikiPath: "/lexicon?q=Netflix" },

  { term: "Blade", ticker: "$BLADE", type: "character", target: "intelligence", wikiPath: "/intelligence?q=Blade" },
  { term: "Brielle Brooks", ticker: "$BRIELLE", type: "character", target: "intelligence", wikiPath: "/intelligence?q=Brielle%20Brooks" },
  { term: "Brielle", ticker: "$BRIELLE", type: "character", target: "intelligence", wikiPath: "/intelligence?q=Brielle%20Brooks" },
  { term: "Bloodline", ticker: "$BRIELLE", type: "character", target: "intelligence", wikiPath: "/intelligence?q=Bloodline" },
  { term: "Tiago Palma", ticker: "$PALMA", type: "creator", target: "intelligence", wikiPath: "/intelligence?q=Tiago%20Palma" },
  { term: "Victor Olazaba", ticker: "$OLAZABA", type: "creator", target: "intelligence", wikiPath: "/intelligence?q=Victor%20Olazaba" },
  { term: "Brian Reber", ticker: "$REBER", type: "creator", target: "intelligence", wikiPath: "/intelligence?q=Brian%20Reber" },
  { term: "Federico Blee", ticker: "$BLEE", type: "creator", target: "intelligence", wikiPath: "/intelligence?q=Federico%20Blee" },
  { term: "Evan Narcisse", ticker: "$NARCISSE", type: "creator", target: "intelligence", wikiPath: "/intelligence?q=Evan%20Narcisse" },
  { term: "Eve L. Ewing", ticker: "$EWING", type: "creator", target: "intelligence", wikiPath: "/intelligence?q=Eve%20L.%20Ewing" },
  { term: "Ruairí Coleman", ticker: "$COLEMAN", type: "creator", target: "intelligence", wikiPath: "/intelligence?q=Ruairi%20Coleman" },
  { term: "Stefano Caselli", ticker: "$CASELLI", type: "creator", target: "intelligence", wikiPath: "/intelligence?q=Stefano%20Caselli" },
  { term: "Greg Pak", ticker: "$GPAK", type: "creator", target: "intelligence", wikiPath: "/intelligence?q=Greg%20Pak" },
  { term: "Mark Buckingham", ticker: "$MBUC", type: "creator", target: "intelligence", wikiPath: "/intelligence?q=Mark%20Buckingham" },
  { term: "Phil Noto", ticker: "$NOTO", type: "creator", target: "intelligence", wikiPath: "/intelligence?q=Phil%20Noto" },
  { term: "Gerry Duggan", ticker: "$DUGGAN", type: "creator", target: "intelligence", wikiPath: "/intelligence?q=Gerry%20Duggan" },
  { term: "Javier Garrón", ticker: "$GARRON", type: "creator", target: "intelligence", wikiPath: "/intelligence?q=Javier%20Garron" },
  { term: "David Marquez", ticker: "$MARQUEZ", type: "creator", target: "intelligence", wikiPath: "/intelligence?q=David%20Marquez" },
  { term: "Andrew Dalhouse", ticker: "$DALHOUSE", type: "creator", target: "intelligence", wikiPath: "/intelligence?q=Andrew%20Dalhouse" },
  { term: "Ethan Hawke", ticker: "$HAWKE", type: "creator", target: "intelligence", wikiPath: "/intelligence?q=Ethan%20Hawke" },
  { term: "Ashley Allen", ticker: "$AALLEN", type: "creator", target: "intelligence", wikiPath: "/intelligence?q=Ashley%20Allen" },
  { term: "Domenico Carbone", ticker: "$CARBONE", type: "creator", target: "intelligence", wikiPath: "/intelligence?q=Domenico%20Carbone" },
  { term: "Fabrizio De Tommaso", ticker: "$DETOMMASO", type: "creator", target: "intelligence", wikiPath: "/intelligence?q=Fabrizio%20De%20Tommaso" },
  { term: "Daniel Warren Johnson", ticker: "$DWJ", type: "creator", target: "intelligence", wikiPath: "/intelligence?q=Daniel%20Warren%20Johnson" },
  { term: "Jack Kirby", ticker: "$KIRBY", type: "creator", target: "intelligence", wikiPath: "/intelligence?q=Jack%20Kirby" },
  { term: "Stan Lee", ticker: "$LEE", type: "creator", target: "intelligence", wikiPath: "/intelligence?q=Stan%20Lee" },
  { term: "Todd McFarlane", ticker: "$MCFARLANE", type: "creator", target: "intelligence", wikiPath: "/intelligence?q=Todd%20McFarlane" },

  // --- CHARACTERS & COMIC LORE (CBR Intelligence -> CBR Market Ticker) ---
  { term: "Dragon Man", ticker: "$DRAGM", type: "character", target: "intelligence", wikiPath: "/intelligence?q=Dragon%20Man" },
  { term: "Godzilla", ticker: "$GODZ", type: "character", target: "intelligence", wikiPath: "/intelligence?q=Godzilla" },
  { term: "Doctor Doom", ticker: "$DOOM", type: "character", target: "intelligence", wikiPath: "/intelligence?q=Doctor%20Doom" },
  { term: "Doom", ticker: "$DOOM", type: "character", target: "intelligence", wikiPath: "/intelligence?q=Doctor%20Doom" },
  { term: "Miles Morales", ticker: "$MILES", type: "character", target: "intelligence", wikiPath: "/intelligence?q=Miles%20Morales" },
  { term: "Spider-Man", ticker: "$SPIDEY", type: "character", target: "intelligence", wikiPath: "/intelligence?q=Spider-Man" },
  { term: "Odin", ticker: "$ODIN", type: "character", target: "intelligence", wikiPath: "/intelligence?q=Odin" },
  { term: "The Punisher", ticker: "$PUNISHER", type: "character", target: "intelligence", wikiPath: "/intelligence?q=Punisher" },
  { term: "Punisher", ticker: "$PUNISHER", type: "character", target: "intelligence", wikiPath: "/intelligence?q=Punisher" },
  { term: "Mothra", ticker: "$MOTHRA", type: "character", target: "intelligence", wikiPath: "/intelligence?q=Mothra" },
  { term: "Knull", ticker: "$KNULL", type: "character", target: "intelligence", wikiPath: "/intelligence?q=Knull" },
  { term: "Kang", ticker: "$KANG", type: "character", target: "intelligence", wikiPath: "/intelligence?q=Kang" },
  { term: "Emma Frost", ticker: "$FROST", type: "character", target: "intelligence", wikiPath: "/intelligence?q=Emma%20Frost" },
  { term: "X-Men United", ticker: "$XMEN", type: "character", target: "intelligence", wikiPath: "/intelligence?q=X-Men%20United" },
  { term: "X-Men", ticker: "$XMEN", type: "character", target: "intelligence", wikiPath: "/intelligence?q=X-Men" },
  { term: "Doctor Strange", ticker: "$STRANGE", type: "character", target: "intelligence", wikiPath: "/intelligence?q=Doctor%20Strange" },
  { term: "Man-Thing", ticker: "$MANTHING", type: "character", target: "intelligence", wikiPath: "/intelligence?q=Man-Thing" },
  { term: "Bruce Wayne", ticker: "$BATMAN", type: "character", target: "intelligence", wikiPath: "/intelligence?q=Bruce%20Wayne" },
  { term: "Batman", ticker: "$BATMAN", type: "character", target: "intelligence", wikiPath: "/intelligence?q=Batman" },
  { term: "Dark Knight", ticker: "$BATMAN", type: "character", target: "intelligence", wikiPath: "/intelligence?q=Dark%20Knight" },
  { term: "Joker", ticker: "$JOKER", type: "character", target: "intelligence", wikiPath: "/intelligence?q=Joker" },
  { term: "Scarecrow", ticker: "$SCARECROW", type: "character", target: "intelligence", wikiPath: "/intelligence?q=Scarecrow" },
  { term: "Wolverine", ticker: "$LOGAN", type: "character", target: "intelligence", wikiPath: "/intelligence?q=Wolverine" },
  { term: "Jubilee", ticker: "$JUBILEE", type: "character", target: "intelligence", wikiPath: "/intelligence?q=Jubilee" },
  { term: "Apocalypse", ticker: "$APOCALYPSE", type: "character", target: "intelligence", wikiPath: "/intelligence?q=Apocalypse" },
  { term: "Thor", ticker: "$THOR", type: "character", target: "intelligence", wikiPath: "/intelligence?q=Thor" },
  { term: "Mjolnir", ticker: "$MJOLNIR", type: "character", target: "intelligence", wikiPath: "/intelligence?q=Mjolnir" },
  { term: "Captain America", ticker: "$CAP", type: "character", target: "intelligence", wikiPath: "/intelligence?q=Captain%20America" },
  { term: "Steve Rogers", ticker: "$CAP", type: "character", target: "intelligence", wikiPath: "/intelligence?q=Steve%20Rogers" },
  { term: "Superman", ticker: "$SUPES", type: "character", target: "intelligence", wikiPath: "/intelligence?q=Superman" },
  { term: "Wonder Woman", ticker: "$WW", type: "character", target: "intelligence", wikiPath: "/intelligence?q=Wonder%20Woman" },

  // --- PUBLISHERS & IMPRINTS ---
  { term: "DC Comics", ticker: "$DC", type: "publisher", target: "intelligence", wikiPath: "/intelligence?q=DC%20Comics" },
  { term: "DC's", ticker: "$DC", type: "publisher", target: "intelligence", wikiPath: "/intelligence?q=DC%20Comics" },
  { term: "DC", ticker: "$DC", type: "publisher", target: "intelligence", wikiPath: "/intelligence?q=DC%20Comics" },
  { term: "Marvel", ticker: "$MRVL", type: "publisher", target: "intelligence", wikiPath: "/intelligence?q=Marvel" },
  { term: "Image Comics", ticker: "$IMAGE", type: "publisher", target: "intelligence", wikiPath: "/intelligence?q=Image%20Comics" },

  // --- CBR FINANCIAL LEXICON TERMS (Industry Terms, Formatting & Publication Metadata) ---
  { term: "Written by :", type: "lexicon", target: "lexicon", wikiPath: "/lexicon?q=Written%20by" },
  { term: "Written by", type: "lexicon", target: "lexicon", wikiPath: "/lexicon?q=Written%20by" },
  { term: "Art by :", type: "lexicon", target: "lexicon", wikiPath: "/lexicon?q=Art%20by" },
  { term: "Art by", type: "lexicon", target: "lexicon", wikiPath: "/lexicon?q=Art%20by" },
  { term: "Cover by :", type: "lexicon", target: "lexicon", wikiPath: "/lexicon?q=Cover%20by" },
  { term: "Cover by", type: "lexicon", target: "lexicon", wikiPath: "/lexicon?q=Cover%20by" },
  { term: "Page Count :", type: "lexicon", target: "lexicon", wikiPath: "/lexicon?q=Page%20Count" },
  { term: "Page Count", type: "lexicon", target: "lexicon", wikiPath: "/lexicon?q=Page%20Count" },
  { term: "Release Date :", type: "lexicon", target: "lexicon", wikiPath: "/lexicon?q=Release%20Date" },
  { term: "Release Date", type: "lexicon", target: "lexicon", wikiPath: "/lexicon?q=Release%20Date" },
  { term: "live-action", type: "lexicon", target: "lexicon", wikiPath: "/lexicon?q=live-action" },
  { term: "animation", type: "lexicon", target: "lexicon", wikiPath: "/lexicon?q=animation" },
  { term: "movies", type: "lexicon", target: "lexicon", wikiPath: "/lexicon?q=movies" },
  { term: "TV shows", type: "lexicon", target: "lexicon", wikiPath: "/lexicon?q=TV%20shows" },
  { term: "actor", type: "lexicon", target: "lexicon", wikiPath: "/lexicon?q=actor" },
  { term: "medium", type: "lexicon", target: "lexicon", wikiPath: "/lexicon?q=medium" },
  { term: "performance", type: "lexicon", target: "lexicon", wikiPath: "/lexicon?q=performance" },
  // --- GAMING & ENTERTAINMENT EQUITIES & FRANCHISES ---
  { term: "Konami", ticker: "KNMCY", type: "equity", target: "lexicon", wikiPath: "/lexicon?q=Konami" },
  { term: "GamesRadar", ticker: "FUTURE", type: "equity", target: "lexicon", wikiPath: "/lexicon?q=GamesRadar" },
  { term: "Castlevania", ticker: "$CASTLEVANIA", type: "character", target: "intelligence", wikiPath: "/intelligence?q=Castlevania" },
  { term: "Simon Belmont", ticker: "$BELMONT", type: "character", target: "intelligence", wikiPath: "/intelligence?q=Simon%20Belmont" },
  { term: "Belmont", ticker: "$BELMONT", type: "character", target: "intelligence", wikiPath: "/intelligence?q=Belmont" },
  { term: "Dracula", ticker: "$DRACULA", type: "character", target: "intelligence", wikiPath: "/intelligence?q=Dracula" },
  { term: "Hector", ticker: "$HECTOR", type: "character", target: "intelligence", wikiPath: "/intelligence?q=Hector" },
  { term: "Hideo Kojima", ticker: "$KOJIMA", type: "creator", target: "intelligence", wikiPath: "/intelligence?q=Hideo%20Kojima" },
  { term: "Scott McCrae", ticker: "$MCCRAE", type: "creator", target: "intelligence", wikiPath: "/intelligence?q=Scott%20McCrae" },

  // --- ADDITIONAL FINANCIAL LEXICON TERMS ---
  { term: "3D collection", type: "lexicon", target: "lexicon", wikiPath: "/lexicon?q=3D%20collection" },
  { term: "anniversary", type: "lexicon", target: "lexicon", wikiPath: "/lexicon?q=anniversary" },
  { term: "re-release", type: "lexicon", target: "lexicon", wikiPath: "/lexicon?q=re-release" },
  { term: "hiatus", type: "lexicon", target: "lexicon", wikiPath: "/lexicon?q=hiatus" },
  { term: "speculate", type: "lexicon", target: "lexicon", wikiPath: "/lexicon?q=speculate" },
  { term: "speculation", type: "lexicon", target: "lexicon", wikiPath: "/lexicon?q=speculation" },
  { term: "market assessment", type: "lexicon", target: "lexicon", wikiPath: "/lexicon?q=market%20assessment" },
  { term: "Market Ripple Projection", type: "lexicon", target: "lexicon", wikiPath: "/lexicon?q=Market%20Ripple%20Projection" },
  { term: "Key Issue Floor", ticker: "REF:KEY", type: "market-concept", target: "lexicon", wikiPath: "/lexicon?q=Key%20Issue" },
  { term: "Market Basket", ticker: "REF:BASKET", type: "market-concept", target: "lexicon", wikiPath: "/lexicon?q=Market%20Basket" },
  { term: "True Firsts", ticker: "REF:TRUE1ST", type: "market-concept", target: "lexicon", wikiPath: "/lexicon?q=True%20First" },
  { term: "First Appearance", ticker: "REF:1ST-APP", type: "market-concept", target: "lexicon", wikiPath: "/lexicon?q=First%20Appearance" },
  { term: "Key Issue", ticker: "REF:KEY", type: "market-concept", target: "lexicon", wikiPath: "/lexicon?q=Key%20Issue" },
  { term: "Variant Cover", ticker: "REF:VARIANT", type: "market-concept", target: "lexicon", wikiPath: "/lexicon?q=Variant" },
  { term: "Ratio Variant", ticker: "REF:RATIO", type: "market-concept", target: "lexicon", wikiPath: "/lexicon?q=Ratio" },
  { term: "CGC", ticker: "REF:CGC", type: "grading", target: "lexicon", wikiPath: "/lexicon?q=CGC" },
  { term: "CBCS", ticker: "REF:CBCS", type: "grading", target: "lexicon", wikiPath: "/lexicon?q=CBCS" },
  { term: "PSA", ticker: "REF:PSA", type: "grading", target: "lexicon", wikiPath: "/lexicon?q=PSA" },
];

export function findNewsEntities(headline: string, summary: string | null): EntityWikiDef[] {
  const text = `${headline} ${summary || ""}`;
  return KNOWN_NEWS_ENTITIES_MAP.filter((def) =>
    new RegExp(`\\b${def.term.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\b`, "i").test(text)
  );
}
