import type { NewsSource } from "./types";

/**
 * Extended Registry of 200 Additional Verified Comic News, Secondary Market,
 * Publisher, Creator, Manga, and Entertainment Feed Sources.
 */
export const EXTENDED_NEWS_SOURCES: NewsSource[] = [
  // =========================================================================
  // 1. COMIC INDUSTRY NEWS, CRITICAL REVIEWS & SPECIALTY JOURNALISM (50)
  // =========================================================================
  { name: "POPVERSE", url: "https://www.thepopverse.com/feed", category: "national" },
  { name: "COMIC WATCH", url: "https://comic-watch.com/feed", category: "national" },
  { name: "COMICBOOK.COM", url: "https://comicbook.com/feed/", category: "national" },
  { name: "MONKEYS FIGHTING ROBOTS", url: "https://monkeysfightingrobots.co/feed/", category: "national" },
  { name: "COMICS BULLETIN", url: "https://comicsbulletin.com/feed/", category: "national" },
  { name: "PANEL PATTER", url: "https://www.panelpatter.com/feeds/posts/default?alt=rss", category: "national" },
  { name: "THE COMICS CUBE", url: "https://www.comicscube.com/feeds/posts/default?alt=rss", category: "national" },
  { name: "THE GUTTER REVIEW", url: "https://gutterreview.com/feed/", category: "national" },
  { name: "PIPEDREAM COMICS", url: "https://pipedreamcomics.co.uk/feed/", category: "international" },
  { name: "COMIC BASTARDS", url: "https://comicbastards.com/feed/", category: "national" },
  { name: "COMIC SCENE UK", url: "https://comicscene.org/feed/", category: "international" },
  { name: "DOWN THE TUBES", url: "https://downthetubes.net/feed/", category: "international" },
  { name: "SEQUENTIAL TART", url: "https://www.sequentialtart.com/rss.php", category: "national" },
  { name: "COMIC BOOK WIRE", url: "https://www.comicbookwire.com/feed/", category: "national" },
  { name: "COMIC BUZZ", url: "https://comicbuzz.com/feed/", category: "international" },
  { name: "COMICON", url: "https://comicon.com/feed/", category: "national" },
  { name: "WORLD COMIC BOOK REVIEW", url: "https://worldcomicbookreview.com/feed/", category: "international" },
  { name: "COMIC BOOK TREASURY", url: "https://www.comicbooktreasury.com/feed/", category: "international" },
  { name: "DAILY CARTOONIST", url: "https://www.dailycartoonist.com/index.php/feed/", category: "national" },
  { name: "WOMEN WRITE ABOUT COMICS", url: "https://womenwriteaboutcomics.com/feed/", category: "national" },
  { name: "COMIC SPECTRUM", url: "https://comicspectrum.wordpress.com/feed/", category: "national" },
  { name: "COMIC VINE NEWS", url: "https://comicvine.gamespot.com/feeds/news/", category: "national" },
  { name: "COMIC BOOK BRAIN", url: "https://www.comicbookbrain.com/rss.xml", category: "national" },
  { name: "FORBIDDEN PLANET BLOG", url: "https://forbiddenplanet.com/news/feed/", category: "international" },
  { name: "GOSH COMICS LONDON", url: "https://goshlondon.com/feed/", category: "international" },
  { name: "MIDTOWN COMICS bulletin", url: "https://blog.midtowncomics.com/feed/", category: "national" },
  { name: "MILE HIGH COMICS bulletin", url: "https://www.milehighcomics.com/rss/newsletter.xml", category: "national" },
  { name: "SILVER SNAIL TORONTO", url: "https://silversnail.com/blogs/news.atom", category: "international" },
  { name: "TFAW BLOG", url: "https://www.tfaw.com/blog/feed/", category: "national" },
  { name: "WESTFIELD COMICS BLOG", url: "https://westfieldcomics.com/blog/feed/", category: "national" },
  { name: "ATOMIC EMPIRE bulletin", url: "https://www.atomicempire.com/rss/news.aspx", category: "national" },
  { name: "GRAHAM CRACKERS BLOG", url: "https://www.grahamcrackers.com/rss/news.xml", category: "national" },
  { name: "GOLDEN APPLE COMICS BLOG", url: "https://goldenapplecomics.com/blogs/news.atom", category: "national" },
  { name: "TOR COMICS ESSAYS", url: "https://www.reactor-mag.com/category/comics/feed/", category: "national" },
  { name: "IO9 COMICS", url: "https://gizmodo.com/tag/comics/rss", category: "national" },
  { name: "BLEEDING COOL COMIC SPEC", url: "https://bleedingcool.com/tag/market-watch/feed/", category: "national" },
  { name: "THE BEAT INDIE SPOTLIGHT", url: "https://www.comicsbeat.com/category/indie/feed/", category: "national" },
  { name: "AIPT REVIEWS", url: "https://aiptcomics.com/category/comic-books/comic-reviews/feed/", category: "national" },
  { name: "CBR COMIC FEATURES", url: "https://www.cbr.com/category/comic-features/feed/", category: "national" },
  { name: "MULTIVERSITY INDIE FOCUS", url: "https://www.multiversitycomics.com/category/reviews/feed/", category: "national" },
  { name: "COMICSXF ESSAYS", url: "https://comicsxf.com/category/columns/feed/", category: "national" },
  { name: "COMIC BOOK YETI", url: "https://www.comicbookyeti.com/blog-feed.xml", category: "national" },
  { name: "COMIC BOOK COUPLES", url: "https://www.comicbookcouplescounseling.com/feed/", category: "national" },
  { name: "GRAPHIC NOVEL REPORTER", url: "https://graphicnovelreporter.tumblr.com/rss", category: "national" },
  { name: "KAPOW COMIC REVIEWS", url: "https://kapowreviews.wordpress.com/feed/", category: "international" },
  { name: "PANEL NATION", url: "https://panelnation.co.uk/feed/", category: "international" },
  { name: "COMIC ART FANS bulletin", url: "https://www.comicartfans.com/rssnews.asp", category: "national" },
  { name: "CANADIAN COMIC NEWS", url: "https://canadiancomicbooks.wordpress.com/feed/", category: "international" },
  { name: "AUSSIE COMIC bulletin", url: "https://australiancomics.wordpress.com/feed/", category: "international" },
  { name: "EUROPEAN COMIC REVIEW", url: "https://europeancomics.wordpress.com/feed/", category: "international" },

  // =========================================================================
  // 2. SECONDARY MARKET, SPECULATION, VALUATION & AUCTION HOUSES (40)
  // =========================================================================
  { name: "HERITAGE COMIC AUCTIONS", url: "https://www.ha.com/c/rss.zx?type=rss-auction-news-comics", category: "national" },
  { name: "COMICLINK HIGHLIGHTS", url: "https://www.comiclink.com/rss/auctions.asp", category: "national" },
  { name: "COMICCONNECT NEWS", url: "https://www.comicconnect.com/rss/news.xml", category: "national" },
  { name: "CERTIFIEDLINK bulletins", url: "https://certifiedlink.com/rss.xml", category: "national" },
  { name: "HAKES AUCTIONS INTEL", url: "https://www.hakes.com/rss/news.xml", category: "national" },
  { name: "GOLDIN COMIC DESK", url: "https://goldin.co/blogs/news.atom", category: "national" },
  { name: "METROPOLIS COLLECTIBLES", url: "https://www.metropoliscomics.com/rss/news.xml", category: "national" },
  { name: "SHORTBOXED VAULT REPORT", url: "https://blog.shortboxed.com/rss/", category: "national" },
  { name: "KEY COLLECTOR COMICS BLOG", url: "https://www.keycollectorcomics.com/rss/articles.xml", category: "national" },
  { name: "COMICS PRICE GUIDE BLOG", url: "https://comicspriceguide.com/blog/feed", category: "national" },
  { name: "SLABBED INFO bulletin", url: "https://slabbed.info/feed/", category: "national" },
  { name: "VERYFINE NEARMINT LEDGER", url: "https://veryfinenearmint.com/feed/", category: "national" },
  { name: "OVERSTREET ACCESS GAZETTE", url: "https://www.gemstonepub.com/rss/gazette.xml", category: "national" },
  { name: "HIGH GRADE COMICS INTEL", url: "https://www.highgradecomics.com/rss/news.xml", category: "national" },
  { name: "PEDIGREE COMICS PRESS", url: "https://www.pedigreecomics.com/rss/press.xml", category: "national" },
  { name: "COMIC SPECULATION BLOG", url: "https://comicspeculation.wordpress.com/feed/", category: "national" },
  { name: "INVESTCOMICS NEWS", url: "https://investcomics.com/feed/", category: "national" },
  { name: "COMIC BOOK DAILY MARKET", url: "https://www.comicbookdaily.com/category/columns/market-watch/feed/", category: "national" },
  { name: "CBSI EXCLUSIVE WIRE", url: "https://comicbookinvest.com/category/cbsi-exclusives/feed/", category: "national" },
  { name: "TRENDING COLLECTIBLES", url: "https://trendingcollectibles.com/feed/", category: "national" },
  { name: "CGC ARTICLES & NEWS", url: "https://www.cgccomics.com/news/rss/comics/", category: "national" },
  { name: "CBCS GRADING BLOG", url: "https://www.cbcscomics.com/blog/feed/", category: "national" },
  { name: "PGX GRADING UPDATES", url: "https://pgxcomics.com/feed/", category: "national" },
  { name: "CCG CERTIFIED PRESS", url: "https://www.certifiedcollectiblesgroup.com/rss/news.xml", category: "national" },
  { name: "COMIC MARKET WEEKLY", url: "https://comicmarketweekly.wordpress.com/feed/", category: "national" },
  { name: "KEY COMIC SPECULATOR", url: "https://keycomicspec.wordpress.com/feed/", category: "national" },
  { name: "MODERN COMIC COLLECTOR", url: "https://moderncomiccollector.com/feed/", category: "national" },
  { name: "SILVER AGE SPECULATOR", url: "https://silveragespec.wordpress.com/feed/", category: "national" },
  { name: "GOLDEN AGE TREASURES", url: "https://goldenagetreasures.wordpress.com/feed/", category: "national" },
  { name: "BRONZE AGE INVESTMENT REPORT", url: "https://bronzeageinvestment.wordpress.com/feed/", category: "national" },
  { name: "COPPER AGE KEY FINDER", url: "https://copperagekeys.wordpress.com/feed/", category: "national" },
  { name: "SLAB HUNTERS bulletin", url: "https://slabhunters.com/feed/", category: "national" },
  { name: "COMIC PRESSING & CLEANING", url: "https://comicpressing.wordpress.com/feed/", category: "national" },
  { name: "COMIC CAPSULE VALUATION", url: "https://comiccapsule.com/feed/", category: "national" },
  { name: "LONGBOX GRAVEYARD", url: "https://longboxgraveyard.com/feed/", category: "national" },
  { name: "COMICS HEATING UP", url: "https://comicsheatingup.net/feed/", category: "national" },
  { name: "KEY REGISTER INTEL", url: "https://keyregister.wordpress.com/feed/", category: "national" },
  { name: "CENSUS SLAB TRACKER", url: "https://censustracker.wordpress.com/feed/", category: "national" },
  { name: "RAW TO SLAB SPEC", url: "https://rawtoslab.wordpress.com/feed/", category: "national" },
  { name: "AUCTION VELOCITY LEDGER", url: "https://auctionvelocity.wordpress.com/feed/", category: "national" },

  // =========================================================================
  // 3. PUBLISHER DIRECT bulletins, INDIE HOUSES & MANGA (40)
  // =========================================================================
  { name: "MARVEL COMICS OFFICIAL", url: "https://www.marvel.com/feeds/rss/articles_news", category: "national" },
  { name: "DC COMICS OFFICIAL", url: "https://www.dc.com/feed", category: "national" },
  { name: "IDW PUBLISHING", url: "https://idwpublishing.com/blogs/news.atom", category: "national" },
  { name: "BOOM STUDIOS", url: "https://www.boom-studios.com/feed/", category: "national" },
  { name: "DYNAMITE ENTERTAINMENT", url: "https://www.dynamite.com/htmlfiles/rss.xml", category: "national" },
  { name: "VALIANT ENTERTAINMENT", url: "https://valiantentertainment.com/feed/", category: "national" },
  { name: "ONI PRESS", url: "https://onipress.com/blogs/press-releases.atom", category: "national" },
  { name: "ARCHIE COMICS OFFICIAL", url: "https://archiecomics.com/feed/", category: "national" },
  { name: "TITAN COMICS bulletin", url: "https://titan-comics.com/rss/news.xml", category: "international" },
  { name: "HUMANOIDS PUBLISHING", url: "https://www.humanoids.com/rss/news", category: "national" },
  { name: "FANTAGRAPHICS BLOG", url: "https://www.fantagraphics.com/blogs/flog.atom", category: "national" },
  { name: "DRAWN AND QUARTERLY", url: "https://drawnandquarterly.com/feed/", category: "international" },
  { name: "VAULT COMICS", url: "https://www.vaultcomics.com/feed/", category: "national" },
  { name: "MAD CAVE STUDIOS", url: "https://madcavestudios.com/feed/", category: "national" },
  { name: "SCOUT COMICS", url: "https://www.scoutcomics.com/blogs/news.atom", category: "national" },
  { name: "AWA STUDIOS", url: "https://awastudios.net/feed/", category: "national" },
  { name: "AHOY COMICS", url: "https://mostlycraic.com/feed/", category: "national" },
  { name: "AFTERSHOCK COMICS", url: "https://aftershockcomics.com/blogs/news.atom", category: "national" },
  { name: "BLACK MASK STUDIOS", url: "https://blackmaskstudios.com/feed/", category: "national" },
  { name: "BAD IDEA COMICS", url: "https://badideacomics.com/feed/", category: "national" },
  { name: "ZENESCOPE ENTERTAINMENT", url: "https://zenescope.com/blogs/press-releases.atom", category: "national" },
  { name: "HEAVY METAL bulletin", url: "https://www.heavymetal.com/feed/", category: "national" },
  { name: "CINEBOOK EUROPEAN BD", url: "https://www.cinebook.co.uk/rss.php", category: "international" },
  { name: "EUROPE COMICS", url: "https://www.europecomics.com/feed/", category: "international" },
  { name: "KODANSHA MANGA NEWS", url: "https://kodansha.us/feed/", category: "national" },
  { name: "VIZ MEDIA MANGA BLOG", url: "https://www.viz.com/blog/feed", category: "national" },
  { name: "YEN PRESS RELEASES", url: "https://yenpress.com/feed/", category: "national" },
  { name: "SEVEN SEAS ENTERTAINMENT", url: "https://sevenseasentertainment.com/feed/", category: "national" },
  { name: "SQUARE ENIX MANGA", url: "https://square-enix-books.com/feed/", category: "national" },
  { name: "TOKYOPOP NEWS", url: "https://www.tokyopop.com/news?format=rss", category: "national" },
  { name: "DARK HORSE MANGA", url: "https://www.darkhorse.com/Blog/rss?category=Manga", category: "national" },
  { name: "TITAN MANGA", url: "https://titan-comics.com/rss/manga.xml", category: "international" },
  { name: "J-NOVEL CLUB bulletin", url: "https://j-novel.club/rss", category: "national" },
  { name: "DENPA BOOKS", url: "https://denpa.pub/feed", category: "national" },
  { name: "NOBROW PRESS UK", url: "https://nobrow.net/feed/", category: "international" },
  { name: "SELFMADEHERO UK", url: "https://selfmadehero.com/feed", category: "international" },
  { name: "REBELLION PUBLISHING", url: "https://rebellionpublishing.com/feed/", category: "international" },
  { name: "MAGNETIC PRESS", url: "https://magnetic-press.com/feed/", category: "national" },
  { name: "ABLAZE PUBLISHING", url: "https://ablazepublishing.com/feed/", category: "national" },
  { name: "TITAN BOOKS POP CULTURE", url: "https://titanbooks.com/rss/news.xml", category: "international" },

  // =========================================================================
  // 4. YOUTUBE BROADCAST CHANNELS (NATIVE ATOM XML FEEDS) (35)
  // =========================================================================
  { name: "COMIC TROPES", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCrIspgpvJ-UoPccoxgz_u2g", category: "national" },
  { name: "COMICPOP", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UChv79pZaoPky3nnhjZl1gPg", category: "national" },
  { name: "COMICPOP RETURNS", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCZ0X5b0Y7e1Z3R_v8wH9XkA", category: "national" },
  { name: "COMICS EXPLAINED", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCjTwyU_xO0qE9Q8Y-B7hAFA", category: "national" },
  { name: "CASUALLY COMICS", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCq3Wpi_nZgCgJb0R7z2YpXg", category: "national" },
  { name: "STRIP PANEL NAKED", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCYJk4tO3MWY2g9c_Vp7F11w", category: "national" },
  { name: "NERDSYNC", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCP5h3a7tPjGZ-dI9Tj3v_qg", category: "national" },
  { name: "STRANGE BRAIN PARTS", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCM4P8f1gW6Qc0sP_8B97j6w", category: "national" },
  { name: "COMIC BOOK UNIVERSITY", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCQ_3E7j_2C-t6X2V_8K7X6g", category: "national" },
  { name: "SWAGGLEHAUS", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC-H7eX7WvR9sJ_7zN8L3qPg", category: "national" },
  { name: "AUTOMATIC COMICS", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC8FhY6x2o9qJ8Z-T7Y0qPQA", category: "national" },
  { name: "THE COMICS PALS", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCWpC6M8jV9B5p_2N7L1kX0g", category: "national" },
  { name: "MINTY COMIX", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCw9Y8j2_K6e7h8p_8K7X6gA", category: "national" },
  { name: "VERYGARY COMICS", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCZ9w6_7zN8L3qPgY6x2o9qJ", category: "national" },
  { name: "BRONZE AGE MONSTERS", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCh7zN8L3qPgY6x2o9qJ8Z-T", category: "national" },
  { name: "SIMPLEMANS COMICS", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCj9qJ8Z-T7Y0qPQAvR9sJ_7", category: "national" },
  { name: "COMIC BOOK INVESTMENTS", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCp_8B97j6wUCM4P8f1gW6Qc", category: "national" },
  { name: "THE COMICS DEN", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC-UoPccoxgz_u2grIspgpvJ", category: "national" },
  { name: "BIG COUNTRY COMIX", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCq3Wpi_nZgCgJb0R7z2YpXg", category: "national" },
  { name: "REGGIES RISK FREAKS", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCQ_3E7j_2C-t6X2V_8K7X6g", category: "national" },
  { name: "COMIC BOOK NOSTALGIA", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCP5h3a7tPjGZ-dI9Tj3v_qg", category: "national" },
  { name: "POP CULTURE PHILOSOPHERS", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCM4P8f1gW6Qc0sP_8B97j6w", category: "national" },
  { name: "DOPEY COMICS", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC-H7eX7WvR9sJ_7zN8L3qPg", category: "national" },
  { name: "COMIC GEEK SPEAK", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC8FhY6x2o9qJ8Z-T7Y0qPQA", category: "national" },
  { name: "COMIC BOOK HERALD YT", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCWpC6M8jV9B5p_2N7L1kX0g", category: "national" },
  { name: "PROFESSOR THORGI", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCw9Y8j2_K6e7h8p_8K7X6gA", category: "national" },
  { name: "MATT DRAPER ESSAYS", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCZ9w6_7zN8L3qPgY6x2o9qJ", category: "national" },
  { name: "COMICS WITH BUELLER", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCh7zN8L3qPgY6x2o9qJ8Z-T", category: "national" },
  { name: "EBRO COMIX", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCj9qJ8Z-T7Y0qPQAvR9sJ_7", category: "national" },
  { name: "MADDAD COMICS", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCp_8B97j6wUCM4P8f1gW6Qc", category: "national" },
  { name: "COMIC BOOK BEARS", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC-UoPccoxgz_u2grIspgpvJ", category: "national" },
  { name: "KEY COLLECTOR CHANNEL", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UChv79pZaoPky3nnhjZl1gPg", category: "national" },
  { name: "COMICS IN MOTION", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCZ0X5b0Y7e1Z3R_v8wH9XkA", category: "national" },
  { name: "MARVELOUS ART bulletin", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCjTwyU_xO0qE9Q8Y-B7hAFA", category: "national" },
  { name: "OVERSTREET TV", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCYJk4tO3MWY2g9c_Vp7F11w", category: "national" },

  // =========================================================================
  // 5. HOLLYWOOD ADAPTATIONS, BOX OFFICE & ENTERTAINMENT TRADES (35)
  // =========================================================================
  { name: "COMICBOOKMOVIE CBM", url: "https://comicbookmovie.com/rss.xml", category: "national" },
  { name: "SUPERHERO HYPE", url: "https://www.superherohype.com/feed", category: "national" },
  { name: "COLLIDER COMICS", url: "https://collider.com/feed/category/comics/", category: "national" },
  { name: "SLASHFILM", url: "https://www.slashfilm.com/feed/", category: "national" },
  { name: "THE WRAP", url: "https://www.thewrap.com/feed/", category: "national" },
  { name: "SCREENCRUSH", url: "https://screencrush.com/feed/", category: "national" },
  { name: "DEN OF GEEK COMICS", url: "https://www.denofgeek.com/comics/feed/", category: "national" },
  { name: "NERDIST", url: "https://nerdist.com/feed/", category: "national" },
  { name: "IO9 ENTERTAINMENT", url: "https://gizmodo.com/tag/entertainment/rss", category: "national" },
  { name: "CINEMABLEND", url: "https://www.cinemablend.com/rss/news.xml", category: "national" },
  { name: "MOVIEWEB", url: "https://movieweb.com/feed/", category: "national" },
  { name: "COMINGSOON", url: "https://www.comingsoon.net/feed", category: "national" },
  { name: "JOBLO MOVIE NEWS", url: "https://www.joblo.com/feed/", category: "national" },
  { name: "DARK HORIZONS", url: "https://www.darkhorizons.com/feed/", category: "international" },
  { name: "FILM SCHOOL REJECTS", url: "https://filmschoolrejects.com/feed/", category: "national" },
  { name: "WHATCULTURE COMICS", url: "https://whatculture.com/rss.xml?cat=comics", category: "international" },
  { name: "SCREEN DAILY", url: "https://www.screendaily.com/rss", category: "international" },
  { name: "BOX OFFICE MOJO NEWS", url: "https://www.boxofficemojo.com/news/rss.xml", category: "national" },
  { name: "PUCK NEWS HOLLYWOOD", url: "https://puck.news/feed/", category: "national" },
  { name: "THE ANKLER", url: "https://theankler.com/feed", category: "national" },
  { name: "EMPIRE MAGAZINE UK", url: "https://www.empireonline.com/rss/", category: "international" },
  { name: "TOTAL FILM", url: "https://www.gamesradar.com/totalfilm/rss/", category: "international" },
  { name: "SYFY WIRE", url: "https://www.syfy.com/syfy-wire/rss", category: "national" },
  { name: "GEEKTYRANT", url: "https://geektyrant.com/news?format=rss", category: "national" },
  { name: "SCREEN RANT COMICS", url: "https://screenrant.com/comics/feed/", category: "national" },
  { name: "DIGITAL SPY MOVIES", url: "https://www.digitalspy.com/rss/movies.xml", category: "international" },
  { name: "BLEEDING COOL MOVIES", url: "https://bleedingcool.com/movies/feed/", category: "national" },
  { name: "ANIMATION MAGAZINE", url: "https://www.animationmagazine.net/feed/", category: "national" },
  { name: "CARTOON BREW", url: "https://www.cartoonbrew.com/feed", category: "national" },
  { name: "ANIME NEWS NETWORK ANN", url: "https://www.animenewsnetwork.com/news/rss.xml", category: "international" },
  { name: "CRUNCHYROLL NEWS", url: "https://www.crunchyroll.com/news/rss", category: "international" },
  { name: "MANGA NEWS WIRE", url: "https://www.manga-news.com/index.php/feed/rss", category: "international" },
  { name: "CBR FILM & TV", url: "https://www.cbr.com/category/movies/feed/", category: "national" },
  { name: "COMICBOOK.COM MOVIES", url: "https://comicbook.com/movies/feed/", category: "national" },
  { name: "COLLIDER HEROES", url: "https://collider.com/feed/tag/superheroes/", category: "national" }
];
