export interface PresenterAvatar {
  id: string;
  name: string;
  role: string;
  ethnicity: string;
  avatarImage: string;
  videoSampleUrl: string;
  badgeBg: string;
  badgeBorder: string;
  badgeText: string;
}

export const PRESENTERS_REGISTRY: PresenterAvatar[] = [
  {
    id: "alex-morgan",
    name: "Alex Morgan",
    role: "Lead Broadcast Anchor",
    ethnicity: "Black / African-American",
    avatarImage: "/presenters/alex-morgan.png",
    videoSampleUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    badgeBg: "bg-purple-950/60",
    badgeBorder: "border-purple-500/50",
    badgeText: "text-purple-300",
  },
  {
    id: "carlos-mendoza",
    name: "Carlos Mendoza",
    role: "Global Markets Correspondent",
    ethnicity: "Latino / Hispanic",
    avatarImage: "/presenters/carlos-mendoza.png",
    videoSampleUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    badgeBg: "bg-blue-950/60",
    badgeBorder: "border-blue-500/50",
    badgeText: "text-blue-300",
  },
  {
    id: "mei-ling-zhou",
    name: "Mei-Ling Zhou",
    role: "Anime & Manga Desk Chief",
    ethnicity: "East Asian",
    avatarImage: "/presenters/mei-ling-zhou.png",
    videoSampleUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
    badgeBg: "bg-rose-950/60",
    badgeBorder: "border-rose-500/50",
    badgeText: "text-rose-300",
  },
  {
    id: "david-oakley",
    name: "David Oakley",
    role: "Vintage Vault Anchor",
    ethnicity: "Caucasian",
    avatarImage: "/presenters/david-oakley.png",
    videoSampleUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
    badgeBg: "bg-amber-950/60",
    badgeBorder: "border-amber-500/50",
    badgeText: "text-amber-300",
  },
  {
    id: "amara-diop",
    name: "Amara Diop",
    role: "Indie & Small Press Analyst",
    ethnicity: "West African",
    avatarImage: "/presenters/amara-diop.png",
    videoSampleUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
    badgeBg: "bg-emerald-950/60",
    badgeBorder: "border-emerald-500/50",
    badgeText: "text-emerald-300",
  },
  {
    id: "priya-sharma",
    name: "Priya Sharma",
    role: "Hollywood & Streaming Reporter",
    ethnicity: "South Asian",
    avatarImage: "/presenters/priya-sharma.png",
    videoSampleUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
    badgeBg: "bg-cyan-950/60",
    badgeBorder: "border-cyan-500/50",
    badgeText: "text-cyan-300",
  },
  {
    id: "marcus-vance-anchor",
    name: "Marcus Vance",
    role: "Senior Key Speculation Presenter",
    ethnicity: "African-American",
    avatarImage: "/presenters/marcus-vance.png",
    videoSampleUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnTheLoose.mp4",
    badgeBg: "bg-amber-900/60",
    badgeBorder: "border-amber-500/50",
    badgeText: "text-amber-200",
  },
  {
    id: "hannah-lindqvist",
    name: "Hannah Lindqvist",
    role: "CGC Slab & Census Correspondent",
    ethnicity: "Scandinavian",
    avatarImage: "/presenters/hannah-lindqvist.png",
    videoSampleUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
    badgeBg: "bg-teal-950/60",
    badgeBorder: "border-teal-500/50",
    badgeText: "text-teal-300",
  },
  {
    id: "tariq-al-mansoor",
    name: "Tariq Al-Mansoor",
    role: "Tech & Digital Media Presenter",
    ethnicity: "Middle Eastern",
    avatarImage: "/presenters/tariq-al-mansoor.png",
    videoSampleUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
    badgeBg: "bg-purple-900/60",
    badgeBorder: "border-purple-500/50",
    badgeText: "text-purple-200",
  },
  {
    id: "chloe-dubois",
    name: "Chloé Dubois",
    role: "European & BD Comic Specialist",
    ethnicity: "French / European",
    avatarImage: "/presenters/chloe-dubois.png",
    videoSampleUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4",
    badgeBg: "bg-pink-950/60",
    badgeBorder: "border-pink-500/50",
    badgeText: "text-pink-300",
  },
  {
    id: "kenji-takahashi",
    name: "Kenji Takahashi",
    role: "Collectibles & Variant Analyst",
    ethnicity: "Japanese",
    avatarImage: "/presenters/kenji-takahashi.png",
    videoSampleUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    badgeBg: "bg-indigo-950/60",
    badgeBorder: "border-indigo-500/50",
    badgeText: "text-indigo-300",
  },
  {
    id: "seraphina-gomez",
    name: "Seraphina Gomez",
    role: "Breakout Talent Presenter",
    ethnicity: "Latina",
    avatarImage: "/presenters/seraphina-gomez.png",
    videoSampleUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    badgeBg: "bg-rose-900/60",
    badgeBorder: "border-rose-500/50",
    badgeText: "text-rose-200",
  },
  {
    id: "nathaniel-cross",
    name: "Nathaniel Cross",
    role: "Auction House Floor Reporter",
    ethnicity: "African-American",
    avatarImage: "/presenters/nathaniel-cross.png",
    videoSampleUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
    badgeBg: "bg-[#090D16]",
    badgeBorder: "border-slate-600/50",
    badgeText: "text-slate-200",
  },
  {
    id: "leila-farah",
    name: "Leila Farah",
    role: "Publishing & Licensing Analyst",
    ethnicity: "North African",
    avatarImage: "/presenters/leila-farah.png",
    videoSampleUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
    badgeBg: "bg-amber-950/60",
    badgeBorder: "border-amber-400/50",
    badgeText: "text-amber-200",
  },
  {
    id: "samuel-wright",
    name: "Samuel Wright",
    role: "Executive Newsroom Presenter",
    ethnicity: "African-American",
    avatarImage: "/presenters/samuel-wright.png",
    videoSampleUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
    badgeBg: "bg-orange-950/60",
    badgeBorder: "border-orange-500/50",
    badgeText: "text-orange-300",
  },
];
