import Link from "next/link";
import { ArrowLeft, BookOpen, Database, DollarSign, GitBranch, History, Newspaper, Users } from "lucide-react";
import { notFound } from "next/navigation";
import { createAdminServerClient } from "@/lib/supabase/admin";
import { getPpcfComic } from "@/lib/ppcf/queries";
import { RelationshipMap } from "@/components/wiki/relationship-map";
import { PriceObservationTimeline } from "@/components/wiki/price-observation-timeline";
import { CensusDossier } from "@/components/comics/census-dossier";
import { getPpcfCensusDossier } from "@/lib/comics/census";
import { resolveIssueDebuts } from "@/lib/wiki/debut-resolver";

export const dynamic = "force-dynamic";
export const fetchCache = "force-no-store";

export default async function WikiRecordPage({ params }: { params: Promise<{ ppcfId: string }> }) {
  const { ppcfId } = await params;
  const comic = await getPpcfComic(ppcfId);
  if (!comic) notFound();
  const debut = resolveIssueDebuts(comic.series_name, comic.issue_number);
  const censusDossier = await getPpcfCensusDossier(comic.series_name, comic.issue_number, comic.variant_name);
  const db = createAdminServerClient();
  const { data: links } = await db.from("ppcf_source_links").select("source_system,source_record_id,source_role").eq("ppcf_id", ppcfId).order("source_system");
  const { data: priceSummary } = await db.from("ppcf_price_summaries").select("observation_count,source_count,latest_observed_at,min_amount,max_amount,currency_set,grade_set").eq("ppcf_id", ppcfId).maybeSingle();
  const fields: Array<[string, string | number | null]> = [["Series", comic.series_name], ["Issue", comic.issue_number], ["Publication date", comic.publication_date], ["Barcode", comic.barcode], ["ISBN", comic.isbn], ["Issue title", comic.issue_title], ["Variant", comic.variant_name], ["GCD issue reference", comic.gcd_issue_id], ["Edition fingerprint", comic.edition_fingerprint]];

  return (
    <main className="mx-auto w-full max-w-7xl px-4 py-8 sm:px-6 lg:px-8 lg:py-10">
      <Link href="/wiki" className="inline-flex items-center gap-2 text-xs uppercase tracking-[0.14em] text-cyan-400 hover:text-cyan-300"><ArrowLeft className="h-3.5 w-3.5" /> Back to encyclopedia</Link>
      <header className="mt-6 overflow-hidden border border-cyan-500/40 bg-[#0b0f15] shadow-[0_8px_26px_rgba(6,182,212,0.12)]"><div className="grid lg:grid-cols-[220px_1fr]"><div className="flex min-h-[300px] items-center justify-center border-b border-cyan-500/30 bg-[#141923] p-4 lg:border-b-0 lg:border-r">{comic.cover_url ? <img src={comic.cover_url} alt={`${comic.series_name || "Comic"} #${comic.issue_number || ""} cover`} className="max-h-[280px] w-full object-contain" /> : <div className="text-center text-[10px] uppercase tracking-[0.2em] text-slate-600">Cover evidence pending</div>}</div><div className="flex flex-col justify-between gap-5 p-6 sm:p-8"><div><div className="flex items-center gap-2 text-[10px] uppercase tracking-[0.25em] text-cyan-400"><BookOpen className="h-3.5 w-3.5" /> Panel Profits edition</div><h1 className="mt-3 text-3xl text-slate-100 sm:text-5xl">{comic.series_name || "Untitled series"} <span className="text-slate-500">#{comic.issue_number || "?"}</span></h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">{comic.variant_name || "Canonical edition record"} · {comic.identity_status}. This is the opening page for the edition, its history, its creators, and its market evidence.</p></div><div className="flex flex-wrap items-center gap-2 text-[10px] uppercase tracking-[0.14em] text-slate-500"><span className="border border-cyan-500/40 px-3 py-2 text-cyan-300">NON-PRICE ENCYCLOPEDIA</span>{comic.cover_verified_at && <span className="border border-emerald-300/40 px-3 py-2 text-emerald-200">VERIFIED COVER</span>}<Link href={`/comics/${encodeURIComponent(comic.ppcf_id)}`} className="border border-purple-500/50 bg-purple-950/40 hover:bg-purple-900/60 px-3 py-2 text-purple-200 hover:text-white transition-colors inline-flex items-center gap-1.5 font-medium"><DollarSign className="h-3 w-3 text-purple-400" /><span>View Market Trading Dossier</span></Link></div></div></div></header>
      <div className="mt-8 space-y-6"><RelationshipMap ppcfId={comic.ppcf_id} gcdIssueId={comic.gcd_issue_id} seriesName={comic.series_name} issueNumber={comic.issue_number} extraContextText={`${debut?.characters.join(" ") || ""} ${debut?.items?.join(" ") || ""} ${debut?.locations?.join(" ") || ""} ${debut?.creators.join(" ") || ""}`.trim()} sourceLinks={links || []} hasPricing={Boolean(priceSummary)} /><PriceObservationTimeline ppcfId={comic.ppcf_id} /><CensusDossier dossier={censusDossier} /><div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_320px]"><div className="space-y-6">
        <section className="border border-slate-800 bg-[#0b0f15] p-5 sm:p-6"><div className="flex items-center gap-2"><Database className="h-4 w-4 text-cyan-400" /><h2 className="text-sm uppercase tracking-[0.16em] text-slate-200">Identity and edition</h2></div><dl className="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{fields.map(([label, value]) => <div key={label}><dt className="text-[10px] uppercase tracking-[0.14em] text-slate-600">{label}</dt><dd className="mt-1 break-words text-sm text-slate-200">{value || "Not populated"}</dd></div>)}</dl></section>
        <section className="grid gap-6 md:grid-cols-2"><div className="border border-slate-800 bg-[#0b0f15] p-5"><div className="flex items-center gap-2"><DollarSign className="h-4 w-4 text-cyan-400" /><h2 className="text-sm uppercase tracking-[0.16em] text-slate-200">Market history</h2></div>{priceSummary ? <><div className="mt-5 grid grid-cols-2 gap-4"><div><p className="text-[10px] uppercase tracking-[0.14em] text-slate-600">Observations</p><p className="mt-1 text-xl text-slate-100">{priceSummary.observation_count}</p></div><div><p className="text-[10px] uppercase tracking-[0.14em] text-slate-600">Sources</p><p className="mt-1 text-xl text-slate-100">{priceSummary.source_count}</p></div><div><p className="text-[10px] uppercase tracking-[0.14em] text-slate-600">Low</p><p className="mt-1 text-sm text-cyan-300">{priceSummary.min_amount ?? "Not populated"}</p></div><div><p className="text-[10px] uppercase tracking-[0.14em] text-slate-600">High</p><p className="mt-1 text-sm text-cyan-300">{priceSummary.max_amount ?? "Not populated"}</p></div></div><p className="mt-5 text-[10px] uppercase tracking-[0.14em] text-slate-500">Grades: {(priceSummary.grade_set || []).join(", ") || "Not populated"} · Currency: {(priceSummary.currency_set || []).join(", ") || "Not populated"}</p></> : <><p className="mt-5 text-sm leading-6 text-slate-500">No reconciled pricing observations are attached yet. No value is inferred.</p><div className="mt-5 border-t border-slate-800 pt-4 text-[10px] uppercase tracking-[0.14em] text-cyan-400">Pricing layer pending</div></>}</div><div className="border border-slate-800 bg-[#0b0f15] p-5"><div className="flex items-center gap-2"><History className="h-4 w-4 text-cyan-300" /><h2 className="text-sm uppercase tracking-[0.16em] text-slate-200">Financial timeline</h2></div><p className="mt-5 text-sm leading-6 text-slate-500">Historical sales, census observations, and market events will be shown as dated evidence rather than a synthetic price curve.</p><div className="mt-5 border-t border-slate-800 pt-4 text-[10px] uppercase tracking-[0.14em] text-cyan-300">Evidence timeline pending</div></div></section>
        <section className="grid gap-6 md:grid-cols-2"><div className="border border-slate-800 bg-[#0b0f15] p-5"><div className="flex items-center gap-2"><Users className="h-4 w-4 text-green-300" /><h2 className="text-sm uppercase tracking-[0.16em] text-slate-200">Creators, Lore and Landmark Debuts</h2></div>{debut && (debut.characters.length > 0 || debut.creators.length > 0 || (debut.items && debut.items.length > 0) || (debut.locations && debut.locations.length > 0)) ? (<div className="mt-4 space-y-4">{debut.characters.length > 0 && (<div><p className="text-[10px] uppercase tracking-[0.14em] text-cyan-400 font-semibold">1st Appearance Key Debuts ({debut.universe})</p><div className="mt-2 flex flex-wrap gap-1.5">{debut.characters.map((char) => (<span key={char} className="inline-flex items-center px-2 py-0.5 rounded text-xs font-mono bg-cyan-950/60 border border-cyan-500/40 text-cyan-300">★ {char}</span>))}</div></div>)}{debut.items && debut.items.length > 0 && (<div><p className="text-[10px] uppercase tracking-[0.14em] text-emerald-400 font-semibold">Landmark Tech, Weapons & Artifacts</p><div className="mt-2 flex flex-wrap gap-1.5">{debut.items.map((it) => (<span key={it} className="inline-flex items-center px-2 py-0.5 rounded text-xs font-mono bg-emerald-950/60 border border-emerald-500/40 text-emerald-200">⚡ {it}</span>))}</div></div>)}{debut.locations && debut.locations.length > 0 && (<div><p className="text-[10px] uppercase tracking-[0.14em] text-indigo-400 font-semibold">Landmark Cities, Realms & Hideouts</p><div className="mt-2 flex flex-wrap gap-1.5">{debut.locations.map((loc) => (<span key={loc} className="inline-flex items-center px-2 py-0.5 rounded text-xs font-mono bg-indigo-950/60 border border-indigo-500/40 text-indigo-200">📍 {loc}</span>))}</div></div>)}{debut.creators.length > 0 && (<div><p className="text-[10px] uppercase tracking-[0.14em] text-cyan-400 font-semibold">Creator Lineage</p><div className="mt-2 flex flex-wrap gap-1.5">{debut.creators.map((cr) => (<span key={cr} className="inline-flex items-center px-2 py-0.5 rounded text-xs font-mono bg-cyan-950/60 border border-cyan-500/40 text-cyan-200">✍ {cr}</span>))}</div></div>)}</div>) : (<p className="mt-5 text-sm leading-6 text-slate-500">Verified GCD creator credits, character links, and story appearances will resolve into PPCF-linked encyclopedia pages.</p>)}</div><div className="border border-slate-800 bg-[#0b0f15] p-5"><div className="flex items-center gap-2"><GitBranch className="h-4 w-4 text-blue-300" /><h2 className="text-sm uppercase tracking-[0.16em] text-slate-200">Series and publisher context</h2></div><p className="mt-5 text-sm leading-6 text-slate-500">Series lineage, publisher history, country, language, and variant relationships will come from the GCD relational graph.</p></div></section>
      </div><aside className="space-y-6"><section className="border border-slate-800 bg-[#0b0f15] p-5"><div className="flex items-center gap-2 text-sm text-slate-200"><Database className="h-4 w-4 text-cyan-400" /> Source provenance</div><div className="mt-5 space-y-3">{(links || []).map((link) => <div key={`${link.source_system}-${link.source_record_id}`} className="border-b border-slate-800 pb-3"><p className="text-[10px] uppercase tracking-[0.14em] text-cyan-400">{link.source_system}</p><p className="mt-1 break-all text-xs text-slate-400">{link.source_record_id}</p><p className="mt-1 text-[10px] text-slate-600">{link.source_role}</p></div>)}</div><p className="mt-5 text-[11px] leading-5 text-slate-500">Source IDs corroborate the record. PPCF is the Panel Profits identity.</p></section><section className="border border-slate-800 bg-[#0b0f15] p-5"><div className="flex items-center gap-2 text-sm text-slate-200"><Newspaper className="h-4 w-4 text-cyan-400" /> Related reporting</div><p className="mt-4 text-sm leading-6 text-slate-500">News stories will link here when their entities resolve to this PPCF record.</p></section></aside></div></div>
    </main>
  );
}
