export interface CollectibleAssetFamily {
  id: string;
  name: string;
  shortCode: string;
  description: string;
  marketRole: string;
  liquidityTier: "HIGH" | "MEDIUM" | "SPECIALIZED" | "INSTITUTIONAL";
  pricingPremiumFactor: string;
}

export const CANONICAL_16_ASSET_FAMILIES: CollectibleAssetFamily[] = [
  {
    id: "GRADED_UNIVERSAL",
    name: "Certified Universal Slab",
    shortCode: "SOV",
    description: "CGC, CBCS, PSA Universal certified high-grade specimens (9.8 / 9.6 / 9.4). The gold standard for institutional alternative investment.",
    marketRole: "Core Market Baseline",
    liquidityTier: "HIGH",
    pricingPremiumFactor: "1.00x Base Benchmark",
  },
  {
    id: "SIGNATURE_SERIES",
    name: "Witnessed Signature Series",
    shortCode: "SIG",
    description: "Official witnessed creator-signed slabs (Yellow label). Valued based on creator historical stature and inscription provenance.",
    marketRole: "Creator Provenance Alpha",
    liquidityTier: "MEDIUM",
    pricingPremiumFactor: "1.25x – 2.50x",
  },
  {
    id: "PEDIGREE_PROVENANCE",
    name: "Recognized Pedigree Collection",
    shortCode: "PED",
    description: "Certified specimens from landmark historical collections (Edgar Church / Mile High, White Mountain, Kansas City, Pacific Coast).",
    marketRole: "Sovereign Heritage Grail",
    liquidityTier: "INSTITUTIONAL",
    pricingPremiumFactor: "2.00x – 5.00x",
  },
  {
    id: "NEWSSTAND_EDITION",
    name: "Newsstand Distributor Edition",
    shortCode: "NEW",
    description: "Original newsstand barcode distribution copies. Extremely scarce in high grade due to newsstand rack wear and unsold return pulping.",
    marketRole: "Scarcity Multiplier",
    liquidityTier: "HIGH",
    pricingPremiumFactor: "1.30x – 3.00x (Post-1985)",
  },
  {
    id: "PRICE_VARIANT",
    name: "Regional Price Test Variant",
    shortCode: "PRV",
    description: "Regional price test market copies (Canadian 75¢/95¢ variants, Marvel 30¢/35¢ test variants). Highly coveted micro-population rarities.",
    marketRole: "Census Asymmetry",
    liquidityTier: "MEDIUM",
    pricingPremiumFactor: "2.50x – 10.00x",
  },
  {
    id: "RATIO_INCENTIVE_VARIANT",
    name: "Retailer Ratio Incentive Variant",
    shortCode: "RAT",
    description: "Exclusively allocated copies requiring retailer orders of 1:25, 1:50, 1:100, or 1:500 standard copies. Immediate manufactured scarcity.",
    marketRole: "Modern Velocity Float",
    liquidityTier: "HIGH",
    pricingPremiumFactor: "1.50x – 4.00x",
  },
  {
    id: "RAW_UNGRADED",
    name: "Raw / Uncertified Specimen",
    shortCode: "RAW",
    description: "Unslabbed collector copies inspected under standard Overstreet physical guidelines. The primary pool for grading arbitrage.",
    marketRole: "Grading Arbitrage Pipeline",
    liquidityTier: "HIGH",
    pricingPremiumFactor: "0.20x – 0.50x of Slabbed 9.8",
  },
  {
    id: "COVER_ART_VARIANT",
    name: "Cover Art / Foil / Virgin Edition",
    shortCode: "VAR",
    description: "Alternative artistic interpretations, virgin covers, metal foil, and convention exclusives with dedicated collector followings.",
    marketRole: "Aesthetic Collector Demand",
    liquidityTier: "HIGH",
    pricingPremiumFactor: "1.10x – 2.20x",
  },
  {
    id: "DIRECT_EDITION",
    name: "Direct Market Comic Shop Edition",
    shortCode: "DIR",
    description: "Standard specialty comic shop printings sold through non-returnable distribution. The baseline circulation foundation.",
    marketRole: "Circulation Float",
    liquidityTier: "HIGH",
    pricingPremiumFactor: "1.00x",
  },
  {
    id: "QUALIFIED_LABEL",
    name: "Certified Qualified Label",
    shortCode: "QLF",
    description: "Green label copies with significant manufacturing flaws, unwitnessed signatures, or missing coupons that do not affect the main story.",
    marketRole: "Affordable Grail Access",
    liquidityTier: "MEDIUM",
    pricingPremiumFactor: "0.40x – 0.70x of Universal",
  },
  {
    id: "RESTORED_LABEL",
    name: "Certified Restored Specimen",
    shortCode: "RST",
    description: "Purple label copies with professional or amateur color touch, tear seals, piece fill, or spine rebuilds.",
    marketRole: "Conservation Specimen",
    liquidityTier: "MEDIUM",
    pricingPremiumFactor: "0.30x – 0.60x of Universal",
  },
  {
    id: "CONSERVED_LABEL",
    name: "Certified Conserved Specimen",
    shortCode: "CNS",
    description: "Blue/Grey label copies treated exclusively with archival preservation techniques (leaf-casting, rice paper tear reinforcement, solvent wash).",
    marketRole: "Museum Preservation",
    liquidityTier: "MEDIUM",
    pricingPremiumFactor: "0.60x – 0.85x of Universal",
  },
  {
    id: "SUBSEQUENT_PRINTING",
    name: "Subsequent Official Printing",
    shortCode: "PRN",
    description: "Official second, third, or later printings released to satisfy secondary market sellouts. Distinct cover art and trade dress.",
    marketRole: "Secondary Sellout Wave",
    liquidityTier: "HIGH",
    pricingPremiumFactor: "0.50x – 1.80x",
  },
  {
    id: "FOREIGN_TRANSLATION",
    name: "Foreign Market / Translated Edition",
    shortCode: "INT",
    description: "International editions licensed by La Prensa (Mexico), Editora Abril (Brazil), Panini (Europe), or Titan (UK).",
    marketRole: "Global Cult Collectibility",
    liquidityTier: "SPECIALIZED",
    pricingPremiumFactor: "0.40x – 3.00x",
  },
  {
    id: "ERROR_PRINTING",
    name: "Manufacturing Error Copy",
    shortCode: "ERR",
    description: "Certified printing oddities (missing foil, inverted interior, double covers, foil color error). Unique curiosity pieces.",
    marketRole: "Curiosity Niche",
    liquidityTier: "SPECIALIZED",
    pricingPremiumFactor: "1.50x – 5.00x",
  },
  {
    id: "PROTOTYPE_ASHCAN",
    name: "Prototype, Ashcan & Advance Copy",
    shortCode: "ASH",
    description: "Advance promotional black-and-white booklets, ashcans created to secure trademark rights, and preview giveaways.",
    marketRole: "Pre-Publication History",
    liquidityTier: "INSTITUTIONAL",
    pricingPremiumFactor: "2.00x – 8.00x",
  },
];
