import { SURFACE_ORDER, SURFACE_ART_MAP, type SurfaceKey } from "./surfaceConfig";
import type { AssetItem } from "./types";

const RAW_INITIAL_SURFACE_ASSETS: AssetItem[] = [
  // ── 1. Artifacts, Weapons & Gadgets ──
  {
    entryId: "asset-gadget-mjol",
    assetId: "MJOL",
    assetType: "GADGET",
    symbol: "$MJOL",
    displayName: "Thor's Hammer (Mjolnir)",
    description: "Cosmic uru hammer forged in Nidavellir. Worthiness covenant sovereign artifact.",
    universe: "Marvel",
    pricing: { price: 2950.00, delta: 1.45, fmv: 2950.00, production_age: "silver", era: "Silver Age" },
    detailUrl: "/assets/MJOL",
    coverImageUrl: SURFACE_ART_MAP.GADGET || "/surface-art/gadget.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-gadget-batmb",
    assetId: "BATMB",
    assetType: "GADGET",
    symbol: "$BATMB",
    displayName: "The Batmobile",
    description: "Sovereign tactical vehicular asset. Multi-era Wayne Enterprises defense contract.",
    universe: "DC",
    pricing: { price: 5400.00, delta: 1.40, fmv: 5400.00, production_age: "golden", era: "Golden Age" },
    detailUrl: "/assets/BATMB",
    coverImageUrl: SURFACE_ART_MAP.GADGET || "/surface-art/gadget.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-gadget-gant",
    assetId: "GANT",
    assetType: "GADGET",
    symbol: "$GANT",
    displayName: "Infinity Gauntlet",
    description: "Omnipotent cosmic artifact holding six operational infinity stones.",
    universe: "Marvel",
    pricing: { price: 3800.00, delta: 2.10, fmv: 3800.00, production_age: "copper", era: "Copper Age" },
    detailUrl: "/assets/GANT",
    coverImageUrl: SURFACE_ART_MAP.GADGET || "/surface-art/gadget.png",
    coverVerified: true,
    quarantined: false,
  },

  // ── 2. Locations, Sanctuaries & Hideouts ──
  {
    entryId: "asset-loc-frtr",
    assetId: "FRTR",
    assetType: "LOCATION",
    symbol: "$FRTR",
    displayName: "The Fortress of Solitude",
    description: "Kryptonian crystalline sanctuary in the Arctic. Sovereign galactic data archive.",
    universe: "DC",
    pricing: { price: 4100.00, delta: 0.85, fmv: 4100.00, production_age: "silver", era: "Silver Age" },
    detailUrl: "/assets/FRTR",
    coverImageUrl: SURFACE_ART_MAP.LOCATION || "/surface-art/location.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-loc-goth",
    assetId: "GOTH",
    assetType: "LOCATION",
    symbol: "$GOTH",
    displayName: "Gotham City Metropolitan Real Estate",
    description: "Sovereign urban territory index reflecting crime contagion and real estate yields.",
    universe: "DC",
    pricing: { price: 2100.00, delta: 0.70, fmv: 2100.00, production_age: "golden", era: "Golden Age" },
    detailUrl: "/assets/GOTH",
    coverImageUrl: SURFACE_ART_MAP.LOCATION || "/surface-art/location.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-loc-wak",
    assetId: "WAK",
    assetType: "LOCATION",
    symbol: "$WAK",
    displayName: "Wakanda Golden City",
    description: "Sovereign territorial holding backed by isolationist technology covenants.",
    universe: "Marvel",
    pricing: { price: 1680.00, delta: 1.90, fmv: 1680.00, production_age: "silver", era: "Silver Age" },
    detailUrl: "/assets/WAK",
    coverImageUrl: SURFACE_ART_MAP.LOCATION || "/surface-art/location.png",
    coverVerified: true,
    quarantined: false,
  },

  // ── 3. Alternate Realities, Mantles & Characters ──
  {
    entryId: "asset-rel-spid1863",
    assetId: "SPID-1863",
    assetType: "REALITY",
    symbol: "$SPID-1863",
    displayName: "Spider-Man 1863 (Civil War Timeline)",
    description: "Historical divergent timeline reality instrument. Alternate universe timeline float.",
    universe: "Marvel",
    pricing: { price: 890.00, delta: 2.15, fmv: 890.00, production_age: "modern", era: "Modern Age" },
    detailUrl: "/assets/SPID-1863",
    coverImageUrl: SURFACE_ART_MAP.REALITY || "/surface-art/reality.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-char-miles2026",
    assetId: "MILES-2026",
    assetType: "CHARACTER",
    symbol: "$MILES-2026",
    displayName: "Miles Morales 2026",
    description: "Modern mantle flagship asset. Cross-media cultural velocity and Gen-Z liquidity.",
    universe: "Marvel",
    pricing: { price: 1650.00, delta: 3.40, fmv: 1650.00, production_age: "modern", era: "Modern Age" },
    detailUrl: "/assets/MILES-2026",
    coverImageUrl: SURFACE_ART_MAP.CHARACTER || "/surface-art/character.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-char-spid",
    assetId: "SPID",
    assetType: "CHARACTER",
    symbol: "$SPID",
    displayName: "Spider-Man (Peter Parker)",
    description: "Flagship Marvel Universe character instrument. High-velocity institutional liquidity.",
    universe: "Marvel",
    pricing: { price: 1845.50, delta: 1.85, fmv: 1845.50, production_age: "silver", era: "Silver Age" },
    detailUrl: "/assets/SPID",
    coverImageUrl: SURFACE_ART_MAP.CHARACTER || "/surface-art/character.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-dc-bat",
    assetId: "BAT",
    assetType: "DC_CHARACTER",
    symbol: "$BAT",
    displayName: "Batman (Bruce Wayne)",
    description: "Sovereign DC Universe cornerstone. Unparalleled mythic cultural gravity.",
    universe: "DC",
    pricing: { price: 2450.00, delta: 2.10, fmv: 2450.00, production_age: "golden", era: "Golden Age" },
    detailUrl: "/assets/BAT",
    coverImageUrl: SURFACE_ART_MAP.DC_CHARACTER || "/surface-art/dc_character.png",
    coverVerified: true,
    quarantined: false,
  },

  // ── 4. Fictional Municipal Bonds & Sovereign Debt ──
  {
    entryId: "asset-bond-goth",
    assetId: "GOTH-MUNI",
    assetType: "BOND",
    symbol: "$GOTH-MUNI",
    displayName: "Gotham City Municipal Bonds 5.25% 2034",
    description: "Municipal bond yielding 5.25%. Spreads and volatility react to Arkham breakout news events.",
    universe: "DC",
    pricing: { price: 98.40, delta: -0.45, fmv: 98.40 },
    detailUrl: "/assets/GOTH-MUNI",
    coverImageUrl: SURFACE_ART_MAP.BOND || "/surface-art/bond.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-bond-cent",
    assetId: "CENT-MUNI",
    assetType: "BOND",
    symbol: "$CENT-MUNI",
    displayName: "Central City S.T.A.R. Labs 4.80% 2032",
    description: "Civic transit and particle physics municipal bond. Spreads react to rogue gallery activities.",
    universe: "DC",
    pricing: { price: 101.20, delta: 0.25, fmv: 101.20 },
    detailUrl: "/assets/CENT-MUNI",
    coverImageUrl: SURFACE_ART_MAP.BOND || "/surface-art/bond.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-bond-wak",
    assetId: "WAK-SOV",
    assetType: "BOND",
    symbol: "$WAK-SOV",
    displayName: "Wakanda Sovereign Vibranium 3.45% 2040",
    description: "Triple-A rated sovereign treasury bond collateralized by physical vibranium reserves.",
    universe: "Marvel",
    pricing: { price: 104.50, delta: 0.15, fmv: 104.50 },
    detailUrl: "/assets/WAK-SOV",
    coverImageUrl: SURFACE_ART_MAP.BOND || "/surface-art/bond.png",
    coverVerified: true,
    quarantined: false,
  },

  // ── 5. Credit Swaps, Derivatives & Options ──
  {
    entryId: "asset-swap-metr",
    assetId: "METR-CDS",
    assetType: "SWAPS",
    symbol: "$METR-CDS",
    displayName: "Metropolis Credit Swaps",
    description: "Credit default swap insuring LexCorp infrastructure covenants against Brainiac incidents.",
    universe: "DC",
    pricing: { price: 215.00, delta: 1.10, fmv: 215.00 },
    detailUrl: "/assets/METR-CDS",
    coverImageUrl: SURFACE_ART_MAP.SWAPS || "/surface-art/swaps.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-swap-gold",
    assetId: "SWAP-GOLD-SILV",
    assetType: "SWAPS",
    symbol: "$SWAP-GOLD-SILV",
    displayName: "Golden/Silver Sovereign Return Swap",
    description: "Institutional swap contract exchanging Golden Age appreciation against Silver Age volatility.",
    universe: "Derivative",
    pricing: { price: 320.00, delta: 0.75, fmv: 320.00 },
    detailUrl: "/assets/SWAP-GOLD-SILV",
    coverImageUrl: SURFACE_ART_MAP.SWAPS || "/surface-art/swaps.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-opt-asm",
    assetId: "ASM-C-1500",
    assetType: "OPTIONS",
    symbol: "$ASM-C-1500",
    displayName: "ASM #300 CGC 9.8 Call 1500",
    description: "Derivative call option on Amazing Spider-Man #300 9.8 strike $1,500. Delta: 0.642.",
    universe: "Derivative",
    pricing: { price: 145.00, delta: 4.80, fmv: 145.00 },
    detailUrl: "/assets/ASM-C-1500",
    coverImageUrl: SURFACE_ART_MAP.OPTIONS || "/surface-art/options.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-opt-bat",
    assetId: "BAT-P-2000",
    assetType: "OPTIONS",
    symbol: "$BAT-P-2000",
    displayName: "Batman #181 CGC 9.0 Put 2000",
    description: "Derivative put option hedging downside risk on Poison Ivy 1st appearance.",
    universe: "Derivative",
    pricing: { price: 85.00, delta: -2.30, fmv: 85.00 },
    detailUrl: "/assets/BAT-P-2000",
    coverImageUrl: SURFACE_ART_MAP.OPTIONS || "/surface-art/options.png",
    coverVerified: true,
    quarantined: false,
  },

  // ── 6. Benchmark Indexes & Superhero Funds ──
  {
    entryId: "asset-idx-gold",
    assetId: "GOLD-IDX",
    assetType: "INDEX",
    symbol: "$GOLD-IDX",
    displayName: "Golden Age Index",
    description: "Constitutional index tracking pre-1956 high-grade certified holy grail comic equities.",
    universe: "Composite",
    pricing: { price: 3450.00, delta: 0.95, fmv: 3450.00 },
    detailUrl: "/assets/GOLD-IDX",
    coverImageUrl: SURFACE_ART_MAP.INDEX || "/surface-art/index.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-fund-silv",
    assetId: "SILV-FUND",
    assetType: "FUND",
    symbol: "$SILV-FUND",
    displayName: "Silver Age Superhero Fund",
    description: "Actively managed fund tracking Marvel and DC Silver Age key issues and early debuts.",
    universe: "Fund",
    pricing: { price: 1840.00, delta: 1.20, fmv: 1840.00 },
    detailUrl: "/assets/SILV-FUND",
    coverImageUrl: SURFACE_ART_MAP.FUND || "/surface-art/fund.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-etf-xgld",
    assetId: "XGLD",
    assetType: "ETF",
    symbol: "$XGLD",
    displayName: "Golden Age Pure Alpha ETF",
    description: "Diversified index basket tracking high-grade Golden Age comic benchmarks.",
    universe: "Fund",
    pricing: { price: 345.20, delta: 0.85, fmv: 345.20 },
    detailUrl: "/assets/XGLD",
    coverImageUrl: SURFACE_ART_MAP.ETF || "/surface-art/etf.png",
    coverVerified: true,
    quarantined: false,
  },

  // ── 7. Legendary Creators & Master Artists ──
  {
    entryId: "asset-creator-dell",
    assetId: "DELL",
    assetType: "CREATOR",
    symbol: "$DELL",
    displayName: "Gabriele Dell'Otto Creator Index",
    description: "Master painter and cover artist royalty index. Primary and variant cover multiplier benchmark.",
    universe: "Creator",
    pricing: { price: 1280.00, delta: 2.80, fmv: 1280.00 },
    detailUrl: "/assets/DELL",
    coverImageUrl: SURFACE_ART_MAP.CREATOR || "/surface-art/creator.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-creator-krby",
    assetId: "KRBY",
    assetType: "CREATOR",
    symbol: "$KRBY",
    displayName: "Jack Kirby 'The King' Legacy Fund",
    description: "Foundational architect of the Marvel Universe and Fourth World. Unassailable creator legacy fund.",
    universe: "Creator",
    pricing: { price: 5800.00, delta: 1.50, fmv: 5800.00 },
    detailUrl: "/assets/KRBY",
    coverImageUrl: SURFACE_ART_MAP.CREATOR || "/surface-art/creator.png",
    coverVerified: true,
    quarantined: false,
  },

  // ── 8. Secret Identities & Alter Egos (355 Member Firms IPO Support) ──
  {
    entryId: "asset-sec-pprk",
    assetId: "PPRK",
    assetType: "SECRET_IDENTITY",
    symbol: "$PPRK",
    displayName: "Peter Parker (Spider-Man Alter Ego)",
    description: "Alter-Ego Sovereign IPO. Backed by 355 Member Firms voting cohort.",
    universe: "Marvel",
    pricing: { price: 420.00, delta: 1.45, fmv: 420.00, production_age: "silver", era: "Silver Age" },
    detailUrl: "/assets/PPRK",
    coverImageUrl: SURFACE_ART_MAP.SECRET_IDENTITY || "/surface-art/secret_identity.png",
    coverVerified: true,
    quarantined: false,
    parameters: { firmSupport: "355 Firms Enrolled", ipoStatus: "Active Market" },
  },
  {
    entryId: "asset-sec-bway",
    assetId: "BWAY",
    assetType: "SECRET_IDENTITY",
    symbol: "$BWAY",
    displayName: "Bruce Wayne (Batman Alter Ego)",
    description: "Wayne Enterprises billionaire alter-ego sovereign holding. 355 firms approved.",
    universe: "DC",
    pricing: { price: 1250.00, delta: 0.95, fmv: 1250.00, production_age: "golden", era: "Golden Age" },
    detailUrl: "/assets/BWAY",
    coverImageUrl: SURFACE_ART_MAP.SECRET_IDENTITY || "/surface-art/secret_identity.png",
    coverVerified: true,
    quarantined: false,
    parameters: { firmSupport: "355 Firms Enrolled", ipoStatus: "Active Market" },
  },
  {
    entryId: "asset-sec-cknt",
    assetId: "CKNT",
    assetType: "SECRET_IDENTITY",
    symbol: "$CKNT",
    displayName: "Clark Kent (Superman Alter Ego)",
    description: "Daily Planet investigative reporter secret identity instrument. 355 firms approved.",
    universe: "DC",
    pricing: { price: 680.00, delta: -0.30, fmv: 680.00, production_age: "platinum", era: "Platinum Age" },
    detailUrl: "/assets/CKNT",
    coverImageUrl: SURFACE_ART_MAP.SECRET_IDENTITY || "/surface-art/secret_identity.png",
    coverVerified: true,
    quarantined: false,
    parameters: { firmSupport: "355 Firms Enrolled", ipoStatus: "Active Market" },
  },

  // ── 9. Real-World Conglomerates & IP Owners (Unspun Live Market Rates) ──
  {
    entryId: "asset-pub-dis",
    assetId: "DIS",
    assetType: "PUBLISHER_STOCK",
    symbol: "$DIS",
    displayName: "Walt Disney Co (Marvel IP)",
    description: "NYSE: DIS. Real-world corporate parent of Marvel Comics, MCU, and licensing royalties.",
    universe: "Real World",
    pricing: { price: 114.85, delta: 1.15, fmv: 114.85 },
    detailUrl: "/assets/DIS",
    coverImageUrl: SURFACE_ART_MAP.PUBLISHER_STOCK || "/surface-art/publisher_stock.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-pub-sony",
    assetId: "SONY",
    assetType: "PUBLISHER_STOCK",
    symbol: "$SONY",
    displayName: "Sony Group Corp (Spider-Man Film IP)",
    description: "NYSE: SONY. Live trading rate for global Spider-Man theatrical and gaming distribution rights.",
    universe: "Real World",
    pricing: { price: 94.20, delta: -0.40, fmv: 94.20 },
    detailUrl: "/assets/SONY",
    coverImageUrl: SURFACE_ART_MAP.PUBLISHER_STOCK || "/surface-art/publisher_stock.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-pub-wbd",
    assetId: "WBD",
    assetType: "PUBLISHER_STOCK",
    symbol: "$WBD",
    displayName: "Warner Bros Discovery (DC Comics Parent)",
    description: "NASDAQ: WBD. Corporate owner of DC Studios, DC Comics catalog, and character licensing.",
    universe: "Real World",
    pricing: { price: 10.45, delta: 2.30, fmv: 10.45 },
    detailUrl: "/assets/WBD",
    coverImageUrl: SURFACE_ART_MAP.PUBLISHER_STOCK || "/surface-art/publisher_stock.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-pub-para",
    assetId: "PARA",
    assetType: "PUBLISHER_STOCK",
    symbol: "$PARA",
    displayName: "Paramount Global (TMNT Media Rights)",
    description: "NASDAQ: PARA. Live tracking of Teenage Mutant Ninja Turtles global franchise rights.",
    universe: "Real World",
    pricing: { price: 12.80, delta: 0.65, fmv: 12.80 },
    detailUrl: "/assets/PARA",
    coverImageUrl: SURFACE_ART_MAP.PUBLISHER_STOCK || "/surface-art/publisher_stock.png",
    coverVerified: true,
    quarantined: false,
  },

  // ── 10. Volatility, Nemeses & Commodities ──
  {
    entryId: "asset-vix-comic",
    assetId: "VIX-COMIC",
    assetType: "VOLATILITY",
    symbol: "$VIX-COMIC",
    displayName: "Comic Market Implied Volatility Index",
    description: "Expected 30-day volatility index across sovereign certified slab auctions.",
    universe: "Derivative",
    pricing: { price: 18.45, delta: 1.25, fmv: 18.45 },
    detailUrl: "/assets/VIX-COMIC",
    coverImageUrl: SURFACE_ART_MAP.VOLATILITY || "/surface-art/volatility.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-vix-goth",
    assetId: "VIX-GOTH",
    assetType: "VOLATILITY",
    symbol: "$VIX-GOTH",
    displayName: "Gotham Threat Volatility Meter",
    description: "Lore-driven geopolitical risk index measuring villain activity contagion.",
    universe: "Derivative",
    pricing: { price: 42.10, delta: 3.40, fmv: 42.10 },
    detailUrl: "/assets/VIX-GOTH",
    coverImageUrl: SURFACE_ART_MAP.VOLATILITY || "/surface-art/volatility.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-nem-batjkr",
    assetId: "NEM-BATJKR",
    assetType: "NEMESIS",
    symbol: "$NEM-BATJKR",
    displayName: "Batman vs Joker Nemesis Pair",
    description: "Dual-sided antithesis asset with 50/50 split exposure to justice vs chaos.",
    universe: "DC",
    pricing: { price: 3400.00, delta: 2.15, fmv: 3400.00 },
    detailUrl: "/assets/NEM-BATJKR",
    coverImageUrl: SURFACE_ART_MAP.NEMESIS || "/surface-art/nemesis.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-cmdty-vib",
    assetId: "VIB",
    assetType: "COMMODITY",
    symbol: "$VIB",
    displayName: "Vibranium Pure Reserve Ingot",
    description: "Wakandan sovereign strategic metal reserve contract. Physical delivery in Birnin Zana.",
    universe: "Marvel",
    pricing: { price: 425.00, delta: 1.65, fmv: 425.00 },
    detailUrl: "/assets/VIB",
    coverImageUrl: SURFACE_ART_MAP.COMMODITY || "/surface-art/commodity.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-cmdty-adm",
    assetId: "ADM",
    assetType: "COMMODITY",
    symbol: "$ADM",
    displayName: "Adamantium Primary Alloy",
    description: "Indestructible metallurgical compound holding. Restricted industrial transfer.",
    universe: "Marvel",
    pricing: { price: 680.00, delta: -0.50, fmv: 680.00 },
    detailUrl: "/assets/ADM",
    coverImageUrl: SURFACE_ART_MAP.COMMODITY || "/surface-art/commodity.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-crd-wayne",
    assetId: "WAYNE-REV",
    assetType: "CREDIT",
    symbol: "-REV",
    displayName: "Wayne Enterprises Senior Revolver 4.25%",
    description: "Investment-grade corporate revolving credit facility backed by Wayne Enterprises defense and aerospace patents.",
    universe: "DC",
    pricing: { price: 102.5, delta: 0.15, fmv: 102.5 },
    detailUrl: "/assets/WAYNE-REV",
    coverImageUrl: "/surface-art/credit.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-crd-lex",
    assetId: "LEX-FRN",
    assetType: "CREDIT",
    symbol: "-FRN",
    displayName: "LexCorp Industrial Floating Rate Note",
    description: "High-yield corporate debt instrument with floating coupon tied to Metropolis energy grid infrastructure.",
    universe: "DC",
    pricing: { price: 98.8, delta: -0.3, fmv: 98.8 },
    detailUrl: "/assets/LEX-FRN",
    coverImageUrl: "/surface-art/credit.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-wrt-spid",
    assetId: "SPID-WRT",
    assetType: "WARRANT",
    symbol: "-WRT",
    displayName: "Spider-Man 2028 Cinematic Rights Warrant",
    description: "Long-dated equity purchase warrant tied to Sony and Disney theatrical distribution gross milestones.",
    universe: "Marvel",
    pricing: { price: 48.5, delta: 1.85, fmv: 48.5 },
    detailUrl: "/assets/SPID-WRT",
    coverImageUrl: "/surface-art/warrant.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-cvt-strk",
    assetId: "STRK-CVT",
    assetType: "CONVERTIBLE",
    symbol: "-CVT",
    displayName: "Stark Defense 4.5% Convertible Debenture",
    description: "Hybrid security combining senior debt yield with conversion option into Stark Industries corporate float.",
    universe: "Marvel",
    pricing: { price: 145.0, delta: 2.1, fmv: 145.0 },
    detailUrl: "/assets/STRK-CVT",
    coverImageUrl: "/surface-art/convertible.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-fwd-gold",
    assetId: "GOLD-FWD",
    assetType: "FORWARD",
    symbol: "-FWD",
    displayName: "Golden Age Benchmark 12M Forward",
    description: "Over-the-counter forward contract committing to certified physical slab delivery at fixed forward index rate.",
    universe: "Derivative",
    pricing: { price: 3520.0, delta: 0.85, fmv: 3520.0 },
    detailUrl: "/assets/GOLD-FWD",
    coverImageUrl: "/surface-art/forward.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-marb-dis",
    assetId: "MCU-SONY-ARB",
    assetType: "MERGER_ARB",
    symbol: "-SONY-ARB",
    displayName: "Disney / Sony Marvel Rights Consolidation Arb",
    description: "Event-driven arbitrage spread tracking potential buyback and full IP consolidation of Spider-Man cinematic rights.",
    universe: "Real World",
    pricing: { price: 14.2, delta: 0.45, fmv: 14.2 },
    detailUrl: "/assets/MCU-SONY-ARB",
    coverImageUrl: "/surface-art/merger_arb.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-spec-ha",
    assetId: "HA-SPEC",
    assetType: "SPECIAL_SITUATIONS",
    symbol: "-SPEC",
    displayName: "Heritage Signature Auction Liquidity Contract",
    description: "Surge contract pricing volatility spikes during major quarterly premier certified auction sessions.",
    universe: "Derivative",
    pricing: { price: 125.0, delta: 1.65, fmv: 125.0 },
    detailUrl: "/assets/HA-SPEC",
    coverImageUrl: "/surface-art/special_situations.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-mac-liq",
    assetId: "MACRO-LIQ",
    assetType: "MACRO",
    symbol: "-LIQ",
    displayName: "Certified Comic Slab Liquidity Macro Index",
    description: "Macroeconomic barometer measuring aggregate trading volume and clearing velocity across certified sales.",
    universe: "Composite",
    pricing: { price: 104.2, delta: 0.35, fmv: 104.2 },
    detailUrl: "/assets/MACRO-LIQ",
    coverImageUrl: "/surface-art/macro.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-cat-sdcc",
    assetId: "SDCC-CAT",
    assetType: "CATALYST",
    symbol: "-CAT",
    displayName: "San Diego Comic-Con Teaser Reveal Catalyst",
    description: "Short-dated binary option tracking Hall H studio announcements and cinematic slate reveals.",
    universe: "Derivative",
    pricing: { price: 62.0, delta: 4.2, fmv: 62.0 },
    detailUrl: "/assets/SDCC-CAT",
    coverImageUrl: "/surface-art/catalyst.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-reit-towr",
    assetId: "TOWR-REIT",
    assetType: "REIT",
    symbol: "-REIT",
    displayName: "Avengers Tower Midtown Manhattan REIT",
    description: "Prime Manhattan commercial and security real estate investment trust generating quarterly facility yields.",
    universe: "Marvel",
    pricing: { price: 285.0, delta: 0.75, fmv: 285.0 },
    detailUrl: "/assets/TOWR-REIT",
    coverImageUrl: "/surface-art/reit.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-str-cdo",
    assetId: "HERO-CDO",
    assetType: "STRUCTURED",
    symbol: "-CDO",
    displayName: "Superhero Collateralized Debt Obligation",
    description: "Securitized debt tranche pooling certified slab loans and superhero franchise revenue streams.",
    universe: "Derivative",
    pricing: { price: 1020.0, delta: 0.25, fmv: 1020.0 },
    detailUrl: "/assets/HERO-CDO",
    coverImageUrl: "/surface-art/structured.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-trs-latv",
    assetId: "LATV-10Y",
    assetType: "TREASURY",
    symbol: "-10Y",
    displayName: "Latveria Sovereign 10-Year Bond",
    description: "Sovereign sovereign bond backed by the full faith, credit, and technological hegemony of Victor Von Doom.",
    universe: "Marvel",
    pricing: { price: 96.5, delta: -0.1, fmv: 96.5 },
    detailUrl: "/assets/LATV-10Y",
    coverImageUrl: "/surface-art/treasury.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-prv-apok",
    assetId: "APOK-PE",
    assetType: "PRIVATE",
    symbol: "-PE",
    displayName: "Apokolips Darkseid Mining Syndicate",
    description: "Institutional private placement in extraterrestrial fire-pit geothermal energy extraction covenants.",
    universe: "DC",
    pricing: { price: 750.0, delta: 0.8, fmv: 750.0 },
    detailUrl: "/assets/APOK-PE",
    coverImageUrl: "/surface-art/private.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-hdg-beta",
    assetId: "COMIC-HEDGE",
    assetType: "HEDGE",
    symbol: "-HEDGE",
    displayName: "Certified Grail Market-Neutral Hedge Fund",
    description: "Actively hedged vehicle pairing long positions in holy grail key issues with short hedges on modern variants.",
    universe: "Fund",
    pricing: { price: 1420.0, delta: 0.95, fmv: 1420.0 },
    detailUrl: "/assets/COMIC-HEDGE",
    coverImageUrl: "/surface-art/hedge.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-ls-mrv",
    assetId: "LS-MRV-MOD",
    assetType: "LONG_SHORT",
    symbol: "-MRV-MOD",
    displayName: "Long Marvel Silver / Short Modern Fund",
    description: "Quantitative long/short strategy exploiting structural valuation divergence between silver age keys and modern print-runs.",
    universe: "Fund",
    pricing: { price: 152.0, delta: 1.4, fmv: 152.0 },
    detailUrl: "/assets/LS-MRV-MOD",
    coverImageUrl: "/surface-art/long_short.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-mgd-trend",
    assetId: "CTA-TREND",
    assetType: "MANAGED_FUTURES",
    symbol: "-TREND",
    displayName: "Comic CTA Systematic Trend Strategy",
    description: "Algorithmic CTA tracking multi-month price trends across premier auction house realization data.",
    universe: "Derivative",
    pricing: { price: 340.0, delta: 0.65, fmv: 340.0 },
    detailUrl: "/assets/CTA-TREND",
    coverImageUrl: "/surface-art/managed_futures.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-qnt-algo",
    assetId: "QUANT-ALGO",
    assetType: "QUANT",
    symbol: "-ALGO",
    displayName: "Pure Quantitative Valuation Algorithm",
    description: "Statistical arbitrage fund identifying off-market mispricings between CGC, CBCS, and raw auction lots.",
    universe: "Derivative",
    pricing: { price: 520.0, delta: 1.1, fmv: 520.0 },
    detailUrl: "/assets/QUANT-ALGO",
    coverImageUrl: "/surface-art/quant.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-cnc-spid",
    assetId: "SPID-CONC",
    assetType: "CONCENTRATED",
    symbol: "-CONC",
    displayName: "Spider-Man Blue-Chip Concentrated Portfolio",
    description: "Single-character concentrated vehicle holding top 1% surviving copies of Amazing Fantasy #15 through ASM #300.",
    universe: "Marvel",
    pricing: { price: 2100.0, delta: 2.3, fmv: 2100.0 },
    detailUrl: "/assets/SPID-CONC",
    coverImageUrl: "/surface-art/concentrated.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-dst-arch",
    assetId: "DIST-ARCH",
    assetType: "DISTRESSED",
    symbol: "-ARCH",
    displayName: "Bankrupt Publisher Archive Rescue Syndicate",
    description: "Distressed asset workout fund acquiring bankrupt Golden Age publisher inventory, printing plates, and unfiled copyright renewals.",
    universe: "Composite",
    pricing: { price: 180.0, delta: -0.5, fmv: 180.0 },
    detailUrl: "/assets/DIST-ARCH",
    coverImageUrl: "/surface-art/distressed.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-cry-strk",
    assetId: "STRK-NET",
    assetType: "CRYPTO",
    symbol: "-NET",
    displayName: "Stark Industries Decentralized Protocol Token",
    description: "Clean-energy microgrid settlement token backed by Stark Arc-Reactor commercial deployment agreements.",
    universe: "Digital",
    pricing: { price: 42.5, delta: 3.15, fmv: 42.5 },
    detailUrl: "/assets/STRK-NET",
    coverImageUrl: "/surface-art/crypto.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-nft-slab",
    assetId: "SLAB-1OF1",
    assetType: "NFT",
    symbol: "-1OF1",
    displayName: "Certified Slab 1/1 Digital Provenance Ledger",
    description: "On-chain digital twin authenticating chain-of-custody, census registration, and vault storage provenance.",
    universe: "Digital",
    pricing: { price: 1250.0, delta: 0.85, fmv: 1250.0 },
    detailUrl: "/assets/SLAB-1OF1",
    coverImageUrl: "/surface-art/nft.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-ali-wall",
    assetId: "WALL-CRAWL",
    assetType: "ALIAS",
    symbol: "-CRAWL",
    displayName: "The Friendly Neighborhood Wall-Crawler",
    description: "Civic persona mantle index capturing local Queens and Midtown public sentiment and licensing goodwill.",
    universe: "Marvel",
    pricing: { price: 410.0, delta: 1.25, fmv: 410.0 },
    detailUrl: "/assets/WALL-CRAWL",
    coverImageUrl: "/surface-art/alias.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-tm-avng",
    assetId: "AVNG",
    assetType: "TEAM",
    symbol: "",
    displayName: "The Avengers Sovereign Team Index",
    description: "Flagship multi-hero ensemble index tracking aggregate cultural velocity and franchise box office royalties.",
    universe: "Marvel",
    pricing: { price: 2400.0, delta: 1.8, fmv: 2400.0 },
    detailUrl: "/assets/AVNG",
    coverImageUrl: "/surface-art/team.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-dct-jla",
    assetId: "JLA",
    assetType: "DC_TEAM",
    symbol: "",
    displayName: "Justice League of America Sovereign Trust",
    description: "Apex DC superhero collective instrument backed by the founding seven pantheon characters.",
    universe: "DC",
    pricing: { price: 2600.0, delta: 1.45, fmv: 2600.0 },
    detailUrl: "/assets/JLA",
    coverImageUrl: "/surface-art/dc_team.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-vtm-sin6",
    assetId: "SIN6",
    assetType: "VILLAIN_TEAM",
    symbol: "",
    displayName: "Sinister Six Collusion Basket",
    description: "Coordinated antagonist syndicate fund reflecting rogue gallery disruption catalysts.",
    universe: "Marvel",
    pricing: { price: 1100.0, delta: 2.4, fmv: 1100.0 },
    detailUrl: "/assets/SIN6",
    coverImageUrl: "/surface-art/villain_team.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-tup-spidhum",
    assetId: "SPID-HUM",
    assetType: "TEAM_UP",
    symbol: "-HUM",
    displayName: "Spider-Man & Human Torch Dynamic Duos",
    description: "Bilateral superhero alliance contract tracking crossover chemistry and buddy-comic demand.",
    universe: "Marvel",
    pricing: { price: 540.0, delta: 0.9, fmv: 540.0 },
    detailUrl: "/assets/SPID-HUM",
    coverImageUrl: "/surface-art/team_up.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-evt-swr84",
    assetId: "SWR-84",
    assetType: "EVENT",
    symbol: "-84",
    displayName: "Secret Wars 1984 Cosmic Multiverse Event",
    description: "Pioneering mega-crossover event holding tracking classic 12-issue line demand and black suit origin impact.",
    universe: "Marvel",
    pricing: { price: 720.0, delta: 1.3, fmv: 720.0 },
    detailUrl: "/assets/SWR-84",
    coverImageUrl: "/surface-art/event.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-xov-mvdc",
    assetId: "MVDC-82",
    assetType: "CROSSOVER",
    symbol: "-82",
    displayName: "Marvel vs DC Sovereign Compact",
    description: "Inter-publisher historic crossover contract commemorating historic cooperative superhero publications.",
    universe: "Derivative",
    pricing: { price: 890.0, delta: 1.15, fmv: 890.0 },
    detailUrl: "/assets/MVDC-82",
    coverImageUrl: "/surface-art/crossover.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-cos-glct",
    assetId: "GLCT",
    assetType: "COSMIC",
    symbol: "",
    displayName: "Galactus Devourer of Worlds Cosmic Float",
    description: "Cosmic force of nature asset class instrument. Extreme volatility correlated with universal herald sightings.",
    universe: "Marvel",
    pricing: { price: 4500.0, delta: 2.8, fmv: 4500.0 },
    detailUrl: "/assets/GLCT",
    coverImageUrl: "/surface-art/cosmic.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-wpn-shld",
    assetId: "SHLD",
    assetType: "WEAPON",
    symbol: "",
    displayName: "Captain America Vibranium Shield",
    description: "Unbreakable proto-adamantium and vibranium aerodynamic weapon. Sovereign patriotic artifact.",
    universe: "Marvel",
    pricing: { price: 2400.0, delta: 1.1, fmv: 2400.0 },
    detailUrl: "/assets/SHLD",
    coverImageUrl: "/surface-art/weapon.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-sdk-robn",
    assetId: "ROBN",
    assetType: "SIDEKICK",
    symbol: "",
    displayName: "Robin (Boy Wonder) Apprentice Trust",
    description: "Junior superhero apprenticeship trust tracking dynamic sidekick succession and Dick Grayson mantle growth.",
    universe: "DC",
    pricing: { price: 480.0, delta: 0.7, fmv: 480.0 },
    detailUrl: "/assets/ROBN",
    coverImageUrl: "/surface-art/sidekick.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-leg-kirby",
    assetId: "KIRBY-LEG",
    assetType: "LEGACY",
    symbol: "-LEG",
    displayName: "Jack Kirby Fourth World Sovereign Endowment",
    description: "Endowment fund preserving and adjudicating Jack Kirby legendary character architectures and cosmologies.",
    universe: "Creator",
    pricing: { price: 5800.0, delta: 1.5, fmv: 5800.0 },
    detailUrl: "/assets/KIRBY-LEG",
    coverImageUrl: "/surface-art/legacy.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-arc-dpx",
    assetId: "DPX-ARC",
    assetType: "STORY_ARC",
    symbol: "-ARC",
    displayName: "The Dark Phoenix Saga Master Narrative Asset",
    description: "Multi-issue narrative sequence benchmark tracking Claremont and Byrne peak mutant tragedy valuation.",
    universe: "Marvel",
    pricing: { price: 1800.0, delta: 1.95, fmv: 1800.0 },
    detailUrl: "/assets/DPX-ARC",
    coverImageUrl: "/surface-art/story_arc.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-org-bite",
    assetId: "BITE-ORG",
    assetType: "ORIGIN_STORY",
    symbol: "-ORG",
    displayName: "Radioactive Spider-Bite Archetype Origin Trust",
    description: "Foundational origin mythos asset certifying the radioactive genesis event of Peter Parker.",
    universe: "Marvel",
    pricing: { price: 1200.0, delta: 1.35, fmv: 1200.0 },
    detailUrl: "/assets/BITE-ORG",
    coverImageUrl: "/surface-art/origin_story.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-flm-mcu",
    assetId: "MCU-BOX",
    assetType: "FILM",
    symbol: "-BOX",
    displayName: "MCU Avengers Secret Wars Box Office Yield Note",
    description: "Theatrical box office revenue participation note settling against global opening weekend gross receipts.",
    universe: "Real World",
    pricing: { price: 128.5, delta: 2.15, fmv: 128.5 },
    detailUrl: "/assets/MCU-BOX",
    coverImageUrl: "/surface-art/film.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-cur-wak",
    assetId: "WAK-DNR",
    assetType: "CURRENCY",
    symbol: "-DNR",
    displayName: "Wakandan Gold-Backed Dinar",
    description: "Sovereign foreign exchange rate for the sovereign currency of Birnin Zana, backed by physical gold reserves.",
    universe: "Real World",
    pricing: { price: 1.45, delta: 0.05, fmv: 1.45 },
    detailUrl: "/assets/WAK-DNR",
    coverImageUrl: "/surface-art/currency.png",
    coverVerified: true,
  },
];

function interleaveInitialAssets(assets: AssetItem[]): AssetItem[] {
  const result: AssetItem[] = [];
  // Filter for assets meeting the $20.00 floor
  const remaining = assets.filter((a) => (a.pricing?.fmv ?? a.pricing?.price ?? 0) >= 20.00);

  while (remaining.length > 0) {
    let nextIdx = -1;
    const lastItem = result[result.length - 1];

    // Find next item with DIFFERENT coverImageUrl, DIFFERENT assetType, and DIFFERENT universe/title
    for (let i = 0; i < remaining.length; i++) {
      const cand = remaining[i];
      if (
        !lastItem ||
        (cand.coverImageUrl !== lastItem.coverImageUrl &&
          cand.assetType !== lastItem.assetType &&
          cand.displayName !== lastItem.displayName)
      ) {
        nextIdx = i;
        break;
      }
    }

    if (nextIdx === -1) {
      for (let i = 0; i < remaining.length; i++) {
        if (!lastItem || remaining[i].coverImageUrl !== lastItem.coverImageUrl) {
          nextIdx = i;
          break;
        }
      }
    }

    if (nextIdx === -1) nextIdx = 0;
    result.push(remaining.splice(nextIdx, 1)[0]);
  }

  // Ensure track wrap-around boundary doesn't match first item
  if (result.length > 2 && result[result.length - 1].coverImageUrl === result[0].coverImageUrl) {
    const last = result.pop()!;
    result.splice(Math.floor(result.length / 2), 0, last);
  }

  return result;
}

export const INITIAL_SURFACE_ASSETS: AssetItem[] = interleaveInitialAssets(RAW_INITIAL_SURFACE_ASSETS);
