import { SURFACE_ORDER, SURFACE_ART_MAP, type SurfaceKey } from "./surfaceConfig";
import type { AssetItem } from "./types";

export const INITIAL_SURFACE_ASSETS: AssetItem[] = [
  // ── 1. Artifacts, Weapons & Gadgets ──
  {
    entryId: "asset-gadget-mjol",
    assetId: "MJOL",
    assetType: "GADGET",
    symbol: "$MJOL",
    displayName: "Thor's Hammer (Mjolnir)",
    description: "Cosmic uru hammer forged in Nidavellir. Worthiness covenant sovereign artifact.",
    universe: "Marvel",
    pricing: { price: 2950.00, delta: 1.45, fmv: 2950.00, production_age: "silver", era: "Silver Age" },
    detailUrl: "/assets/MJOL",
    coverImageUrl: SURFACE_ART_MAP.GADGET || "/surface-art/gadget.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-gadget-batmb",
    assetId: "BATMB",
    assetType: "GADGET",
    symbol: "$BATMB",
    displayName: "The Batmobile",
    description: "Sovereign tactical vehicular asset. Multi-era Wayne Enterprises defense contract.",
    universe: "DC",
    pricing: { price: 5400.00, delta: 1.40, fmv: 5400.00, production_age: "golden", era: "Golden Age" },
    detailUrl: "/assets/BATMB",
    coverImageUrl: SURFACE_ART_MAP.GADGET || "/surface-art/gadget.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-gadget-gant",
    assetId: "GANT",
    assetType: "GADGET",
    symbol: "$GANT",
    displayName: "Infinity Gauntlet",
    description: "Omnipotent cosmic artifact holding six operational infinity stones.",
    universe: "Marvel",
    pricing: { price: 3800.00, delta: 2.10, fmv: 3800.00, production_age: "copper", era: "Copper Age" },
    detailUrl: "/assets/GANT",
    coverImageUrl: SURFACE_ART_MAP.GADGET || "/surface-art/gadget.png",
    coverVerified: true,
    quarantined: false,
  },

  // ── 2. Locations, Sanctuaries & Hideouts ──
  {
    entryId: "asset-loc-frtr",
    assetId: "FRTR",
    assetType: "LOCATION",
    symbol: "$FRTR",
    displayName: "The Fortress of Solitude",
    description: "Kryptonian crystalline sanctuary in the Arctic. Sovereign galactic data archive.",
    universe: "DC",
    pricing: { price: 4100.00, delta: 0.85, fmv: 4100.00, production_age: "silver", era: "Silver Age" },
    detailUrl: "/assets/FRTR",
    coverImageUrl: SURFACE_ART_MAP.LOCATION || "/surface-art/location.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-loc-goth",
    assetId: "GOTH",
    assetType: "LOCATION",
    symbol: "$GOTH",
    displayName: "Gotham City Metropolitan Real Estate",
    description: "Sovereign urban territory index reflecting crime contagion and real estate yields.",
    universe: "DC",
    pricing: { price: 2100.00, delta: 0.70, fmv: 2100.00, production_age: "golden", era: "Golden Age" },
    detailUrl: "/assets/GOTH",
    coverImageUrl: SURFACE_ART_MAP.LOCATION || "/surface-art/location.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-loc-wak",
    assetId: "WAK",
    assetType: "LOCATION",
    symbol: "$WAK",
    displayName: "Wakanda Golden City",
    description: "Sovereign territorial equity backed by isolationist technology covenants.",
    universe: "Marvel",
    pricing: { price: 1680.00, delta: 1.90, fmv: 1680.00, production_age: "silver", era: "Silver Age" },
    detailUrl: "/assets/WAK",
    coverImageUrl: SURFACE_ART_MAP.LOCATION || "/surface-art/location.png",
    coverVerified: true,
    quarantined: false,
  },

  // ── 3. Alternate Realities, Mantles & Characters ──
  {
    entryId: "asset-rel-spid1863",
    assetId: "SPID-1863",
    assetType: "REALITY",
    symbol: "$SPID-1863",
    displayName: "Spider-Man 1863 (Civil War Timeline)",
    description: "Historical divergent timeline reality instrument. Alternate universe equity float.",
    universe: "Marvel",
    pricing: { price: 890.00, delta: 2.15, fmv: 890.00, production_age: "modern", era: "Modern Age" },
    detailUrl: "/assets/SPID-1863",
    coverImageUrl: SURFACE_ART_MAP.REALITY || "/surface-art/reality.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-char-miles2026",
    assetId: "MILES-2026",
    assetType: "CHARACTER",
    symbol: "$MILES-2026",
    displayName: "Miles Morales 2026",
    description: "Modern mantle flagship equity. Cross-media cultural velocity and Gen-Z liquidity.",
    universe: "Marvel",
    pricing: { price: 1650.00, delta: 3.40, fmv: 1650.00, production_age: "modern", era: "Modern Age" },
    detailUrl: "/assets/MILES-2026",
    coverImageUrl: SURFACE_ART_MAP.CHARACTER || "/surface-art/character.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-char-spid",
    assetId: "SPID",
    assetType: "CHARACTER",
    symbol: "$SPID",
    displayName: "Spider-Man (Peter Parker)",
    description: "Flagship Marvel Universe character equity. High-velocity institutional liquidity.",
    universe: "Marvel",
    pricing: { price: 1845.50, delta: 1.85, fmv: 1845.50, production_age: "silver", era: "Silver Age" },
    detailUrl: "/assets/SPID",
    coverImageUrl: SURFACE_ART_MAP.CHARACTER || "/surface-art/character.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-dc-bat",
    assetId: "BAT",
    assetType: "DC_CHARACTER",
    symbol: "$BAT",
    displayName: "Batman (Bruce Wayne)",
    description: "Sovereign DC Universe cornerstone. Unparalleled mythic cultural gravity.",
    universe: "DC",
    pricing: { price: 2450.00, delta: 2.10, fmv: 2450.00, production_age: "golden", era: "Golden Age" },
    detailUrl: "/assets/BAT",
    coverImageUrl: SURFACE_ART_MAP.DC_CHARACTER || "/surface-art/dc_character.png",
    coverVerified: true,
    quarantined: false,
  },

  // ── 4. Fictional Municipal Bonds & Sovereign Debt ──
  {
    entryId: "asset-bond-goth",
    assetId: "GOTH-MUNI",
    assetType: "BOND",
    symbol: "$GOTH-MUNI",
    displayName: "Gotham City Municipal Bonds 5.25% 2034",
    description: "Municipal bond yielding 5.25%. Spreads and volatility react to Arkham breakout news events.",
    universe: "DC",
    pricing: { price: 98.40, delta: -0.45, fmv: 98.40 },
    detailUrl: "/assets/GOTH-MUNI",
    coverImageUrl: SURFACE_ART_MAP.BOND || "/surface-art/bond.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-bond-cent",
    assetId: "CENT-MUNI",
    assetType: "BOND",
    symbol: "$CENT-MUNI",
    displayName: "Central City S.T.A.R. Labs 4.80% 2032",
    description: "Civic transit and particle physics municipal bond. Spreads react to rogue gallery activities.",
    universe: "DC",
    pricing: { price: 101.20, delta: 0.25, fmv: 101.20 },
    detailUrl: "/assets/CENT-MUNI",
    coverImageUrl: SURFACE_ART_MAP.BOND || "/surface-art/bond.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-bond-wak",
    assetId: "WAK-SOV",
    assetType: "BOND",
    symbol: "$WAK-SOV",
    displayName: "Wakanda Sovereign Vibranium 3.45% 2040",
    description: "Triple-A rated sovereign treasury bond collateralized by physical vibranium reserves.",
    universe: "Marvel",
    pricing: { price: 104.50, delta: 0.15, fmv: 104.50 },
    detailUrl: "/assets/WAK-SOV",
    coverImageUrl: SURFACE_ART_MAP.BOND || "/surface-art/bond.png",
    coverVerified: true,
    quarantined: false,
  },

  // ── 5. Credit Swaps, Derivatives & Options ──
  {
    entryId: "asset-swap-metr",
    assetId: "METR-CDS",
    assetType: "SWAPS",
    symbol: "$METR-CDS",
    displayName: "Metropolis Credit Swaps",
    description: "Credit default swap insuring LexCorp infrastructure covenants against Brainiac incidents.",
    universe: "DC",
    pricing: { price: 215.00, delta: 1.10, fmv: 215.00 },
    detailUrl: "/assets/METR-CDS",
    coverImageUrl: SURFACE_ART_MAP.SWAPS || "/surface-art/swaps.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-swap-gold",
    assetId: "SWAP-GOLD-SILV",
    assetType: "SWAPS",
    symbol: "$SWAP-GOLD-SILV",
    displayName: "Golden/Silver Sovereign Return Swap",
    description: "Institutional swap contract exchanging Golden Age appreciation against Silver Age volatility.",
    universe: "Derivative",
    pricing: { price: 320.00, delta: 0.75, fmv: 320.00 },
    detailUrl: "/assets/SWAP-GOLD-SILV",
    coverImageUrl: SURFACE_ART_MAP.SWAPS || "/surface-art/swaps.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-opt-asm",
    assetId: "ASM-C-1500",
    assetType: "OPTIONS",
    symbol: "$ASM-C-1500",
    displayName: "ASM #300 CGC 9.8 Call 1500",
    description: "Derivative call option on Amazing Spider-Man #300 9.8 strike $1,500. Delta: 0.642.",
    universe: "Derivative",
    pricing: { price: 145.00, delta: 4.80, fmv: 145.00 },
    detailUrl: "/assets/ASM-C-1500",
    coverImageUrl: SURFACE_ART_MAP.OPTIONS || "/surface-art/options.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-opt-bat",
    assetId: "BAT-P-2000",
    assetType: "OPTIONS",
    symbol: "$BAT-P-2000",
    displayName: "Batman #181 CGC 9.0 Put 2000",
    description: "Derivative put option hedging downside risk on Poison Ivy 1st appearance.",
    universe: "Derivative",
    pricing: { price: 85.00, delta: -2.30, fmv: 85.00 },
    detailUrl: "/assets/BAT-P-2000",
    coverImageUrl: SURFACE_ART_MAP.OPTIONS || "/surface-art/options.png",
    coverVerified: true,
    quarantined: false,
  },

  // ── 6. Benchmark Indexes & Superhero Funds ──
  {
    entryId: "asset-idx-gold",
    assetId: "GOLD-IDX",
    assetType: "INDEX",
    symbol: "$GOLD-IDX",
    displayName: "Golden Age Index",
    description: "Constitutional index tracking pre-1956 high-grade certified holy grail comic equities.",
    universe: "Composite",
    pricing: { price: 3450.00, delta: 0.95, fmv: 3450.00 },
    detailUrl: "/assets/GOLD-IDX",
    coverImageUrl: SURFACE_ART_MAP.INDEX || "/surface-art/index.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-fund-silv",
    assetId: "SILV-FUND",
    assetType: "FUND",
    symbol: "$SILV-FUND",
    displayName: "Silver Age Superhero Fund",
    description: "Actively managed fund tracking Marvel and DC Silver Age key issues and early debuts.",
    universe: "Fund",
    pricing: { price: 1840.00, delta: 1.20, fmv: 1840.00 },
    detailUrl: "/assets/SILV-FUND",
    coverImageUrl: SURFACE_ART_MAP.FUND || "/surface-art/fund.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-etf-xgld",
    assetId: "XGLD",
    assetType: "ETF",
    symbol: "$XGLD",
    displayName: "Golden Age Pure Alpha ETF",
    description: "Diversified index basket tracking high-grade Golden Age comic benchmarks.",
    universe: "Fund",
    pricing: { price: 345.20, delta: 0.85, fmv: 345.20 },
    detailUrl: "/assets/XGLD",
    coverImageUrl: SURFACE_ART_MAP.ETF || "/surface-art/etf.png",
    coverVerified: true,
    quarantined: false,
  },

  // ── 7. Legendary Creators & Master Artists ──
  {
    entryId: "asset-creator-dell",
    assetId: "DELL",
    assetType: "CREATOR",
    symbol: "$DELL",
    displayName: "Gabriele Dell'Otto Creator Equity",
    description: "Master painter and cover artist equity. Primary and variant cover multiplier benchmark.",
    universe: "Creator",
    pricing: { price: 1280.00, delta: 2.80, fmv: 1280.00 },
    detailUrl: "/assets/DELL",
    coverImageUrl: SURFACE_ART_MAP.CREATOR || "/surface-art/creator.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-creator-krby",
    assetId: "KRBY",
    assetType: "CREATOR",
    symbol: "$KRBY",
    displayName: "Jack Kirby 'The King' Legacy Equity",
    description: "Foundational architect of the Marvel Universe and Fourth World. Unassailable creator canon.",
    universe: "Creator",
    pricing: { price: 5800.00, delta: 1.50, fmv: 5800.00 },
    detailUrl: "/assets/KRBY",
    coverImageUrl: SURFACE_ART_MAP.CREATOR || "/surface-art/creator.png",
    coverVerified: true,
    quarantined: false,
  },

  // ── 8. Secret Identities & Alter Egos (355 Member Firms IPO Support) ──
  {
    entryId: "asset-sec-pprk",
    assetId: "PPRK",
    assetType: "SECRET_IDENTITY",
    symbol: "$PPRK",
    displayName: "Peter Parker (Spider-Man Alter Ego)",
    description: "Alter-Ego Sovereign IPO. Backed by 355 Member Firms voting cohort.",
    universe: "Marvel",
    pricing: { price: 420.00, delta: 1.45, fmv: 420.00, production_age: "silver", era: "Silver Age" },
    detailUrl: "/assets/PPRK",
    coverImageUrl: SURFACE_ART_MAP.SECRET_IDENTITY || "/surface-art/secret_identity.png",
    coverVerified: true,
    quarantined: false,
    parameters: { firmSupport: "355 Firms Enrolled", ipoStatus: "Active Market" },
  },
  {
    entryId: "asset-sec-bway",
    assetId: "BWAY",
    assetType: "SECRET_IDENTITY",
    symbol: "$BWAY",
    displayName: "Bruce Wayne (Batman Alter Ego)",
    description: "Wayne Enterprises billionaire alter-ego sovereign holding. 355 firms approved.",
    universe: "DC",
    pricing: { price: 1250.00, delta: 0.95, fmv: 1250.00, production_age: "golden", era: "Golden Age" },
    detailUrl: "/assets/BWAY",
    coverImageUrl: SURFACE_ART_MAP.SECRET_IDENTITY || "/surface-art/secret_identity.png",
    coverVerified: true,
    quarantined: false,
    parameters: { firmSupport: "355 Firms Enrolled", ipoStatus: "Active Market" },
  },
  {
    entryId: "asset-sec-cknt",
    assetId: "CKNT",
    assetType: "SECRET_IDENTITY",
    symbol: "$CKNT",
    displayName: "Clark Kent (Superman Alter Ego)",
    description: "Daily Planet investigative reporter secret identity instrument. 355 firms approved.",
    universe: "DC",
    pricing: { price: 680.00, delta: -0.30, fmv: 680.00, production_age: "platinum", era: "Platinum Age" },
    detailUrl: "/assets/CKNT",
    coverImageUrl: SURFACE_ART_MAP.SECRET_IDENTITY || "/surface-art/secret_identity.png",
    coverVerified: true,
    quarantined: false,
    parameters: { firmSupport: "355 Firms Enrolled", ipoStatus: "Active Market" },
  },

  // ── 9. Real-World Conglomerates & IP Owners (Unspun Live Market Rates) ──
  {
    entryId: "asset-pub-dis",
    assetId: "DIS",
    assetType: "PUBLISHER_STOCK",
    symbol: "$DIS",
    displayName: "Walt Disney Co (Marvel IP)",
    description: "NYSE: DIS. Real-world corporate parent of Marvel Comics, MCU, and licensing royalties.",
    universe: "Real World",
    pricing: { price: 114.85, delta: 1.15, fmv: 114.85 },
    detailUrl: "/assets/DIS",
    coverImageUrl: SURFACE_ART_MAP.PUBLISHER_STOCK || "/surface-art/publisher_stock.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-pub-sony",
    assetId: "SONY",
    assetType: "PUBLISHER_STOCK",
    symbol: "$SONY",
    displayName: "Sony Group Corp (Spider-Man Film IP)",
    description: "NYSE: SONY. Live trading rate for global Spider-Man theatrical and gaming distribution rights.",
    universe: "Real World",
    pricing: { price: 94.20, delta: -0.40, fmv: 94.20 },
    detailUrl: "/assets/SONY",
    coverImageUrl: SURFACE_ART_MAP.PUBLISHER_STOCK || "/surface-art/publisher_stock.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-pub-wbd",
    assetId: "WBD",
    assetType: "PUBLISHER_STOCK",
    symbol: "$WBD",
    displayName: "Warner Bros Discovery (DC Comics Parent)",
    description: "NASDAQ: WBD. Corporate owner of DC Studios, DC Comics catalog, and character licensing.",
    universe: "Real World",
    pricing: { price: 10.45, delta: 2.30, fmv: 10.45 },
    detailUrl: "/assets/WBD",
    coverImageUrl: SURFACE_ART_MAP.PUBLISHER_STOCK || "/surface-art/publisher_stock.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-pub-para",
    assetId: "PARA",
    assetType: "PUBLISHER_STOCK",
    symbol: "$PARA",
    displayName: "Paramount Global (TMNT Media Rights)",
    description: "NASDAQ: PARA. Live tracking of Teenage Mutant Ninja Turtles global franchise rights.",
    universe: "Real World",
    pricing: { price: 12.80, delta: 0.65, fmv: 12.80 },
    detailUrl: "/assets/PARA",
    coverImageUrl: SURFACE_ART_MAP.PUBLISHER_STOCK || "/surface-art/publisher_stock.png",
    coverVerified: true,
    quarantined: false,
  },

  // ── 10. Volatility, Nemeses & Commodities ──
  {
    entryId: "asset-vix-comic",
    assetId: "VIX-COMIC",
    assetType: "VOLATILITY",
    symbol: "$VIX-COMIC",
    displayName: "Comic Market Implied Volatility Index",
    description: "Expected 30-day volatility index across sovereign certified slab auctions.",
    universe: "Derivative",
    pricing: { price: 18.45, delta: 1.25, fmv: 18.45 },
    detailUrl: "/assets/VIX-COMIC",
    coverImageUrl: SURFACE_ART_MAP.VOLATILITY || "/surface-art/volatility.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-vix-goth",
    assetId: "VIX-GOTH",
    assetType: "VOLATILITY",
    symbol: "$VIX-GOTH",
    displayName: "Gotham Threat Volatility Meter",
    description: "Lore-driven geopolitical risk index measuring villain activity contagion.",
    universe: "Derivative",
    pricing: { price: 42.10, delta: 3.40, fmv: 42.10 },
    detailUrl: "/assets/VIX-GOTH",
    coverImageUrl: SURFACE_ART_MAP.VOLATILITY || "/surface-art/volatility.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-nem-batjkr",
    assetId: "NEM-BATJKR",
    assetType: "NEMESIS",
    symbol: "$NEM-BATJKR",
    displayName: "Batman vs Joker Nemesis Pair",
    description: "Dual-sided antithesis asset with 50/50 split exposure to justice vs chaos.",
    universe: "DC",
    pricing: { price: 3400.00, delta: 2.15, fmv: 3400.00 },
    detailUrl: "/assets/NEM-BATJKR",
    coverImageUrl: SURFACE_ART_MAP.NEMESIS || "/surface-art/nemesis.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-cmdty-vib",
    assetId: "VIB",
    assetType: "COMMODITY",
    symbol: "$VIB",
    displayName: "Vibranium Pure Reserve Ingot",
    description: "Wakandan sovereign strategic metal reserve contract. Physical delivery in Birnin Zana.",
    universe: "Marvel",
    pricing: { price: 425.00, delta: 1.65, fmv: 425.00 },
    detailUrl: "/assets/VIB",
    coverImageUrl: SURFACE_ART_MAP.COMMODITY || "/surface-art/commodity.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-cmdty-adm",
    assetId: "ADM",
    assetType: "COMMODITY",
    symbol: "$ADM",
    displayName: "Adamantium Primary Alloy",
    description: "Indestructible metallurgical compound holding. Restricted industrial transfer.",
    universe: "Marvel",
    pricing: { price: 680.00, delta: -0.50, fmv: 680.00 },
    detailUrl: "/assets/ADM",
    coverImageUrl: SURFACE_ART_MAP.COMMODITY || "/surface-art/commodity.png",
    coverVerified: true,
    quarantined: false,
  },
];
