import { SURFACE_ORDER, SURFACE_ART_MAP, type SurfaceKey } from "./surfaceConfig";
import type { AssetItem } from "./types";

export const INITIAL_SURFACE_ASSETS: AssetItem[] = [
  // ── 1. Characters & Heroes ──
  {
    entryId: "asset-char-spid",
    assetId: "SPID",
    assetType: "CHARACTER",
    symbol: "$SPID",
    displayName: "Spider-Man",
    description: "Flagship Marvel Universe character equity. High-velocity institutional liquidity.",
    universe: "Marvel",
    pricing: { price: 1845.50, delta: 1.85, fmv: 1845.50, production_age: "silver", era: "Silver Age" },
    detailUrl: "/assets/SPID",
    coverImageUrl: SURFACE_ART_MAP.CHARACTER || "/surface-art/character.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-dc-bat",
    assetId: "BAT",
    assetType: "DC_CHARACTER",
    symbol: "$BAT",
    displayName: "Batman",
    description: "Sovereign DC Universe cornerstone. Unparalleled mythic cultural gravity.",
    universe: "DC",
    pricing: { price: 2450.00, delta: 2.10, fmv: 2450.00, production_age: "golden", era: "Golden Age" },
    detailUrl: "/assets/BAT",
    coverImageUrl: SURFACE_ART_MAP.DC_CHARACTER || "/surface-art/dc_character.png",
    coverVerified: true,
    quarantined: false,
  },

  // ── 2. Alter Egos & Secret Identities (355 Member Firms IPO Support) ──
  {
    entryId: "asset-sec-pprk",
    assetId: "PPRK",
    assetType: "SECRET_IDENTITY",
    symbol: "$PPRK",
    displayName: "Peter Parker (Spider-Man)",
    description: "Alter-Ego Sovereign IPO. Backed by 355 Member Firms voting cohort.",
    universe: "Marvel",
    pricing: { price: 420.00, delta: 1.45, fmv: 420.00, production_age: "silver", era: "Silver Age" },
    detailUrl: "/assets/PPRK",
    coverImageUrl: SURFACE_ART_MAP.SECRET_IDENTITY || "/surface-art/secret_identity.png",
    coverVerified: true,
    quarantined: false,
    parameters: { firmSupport: "355 Firms Enrolled", ipoStatus: "Active Market" },
  },
  {
    entryId: "asset-sec-bway",
    assetId: "BWAY",
    assetType: "SECRET_IDENTITY",
    symbol: "$BWAY",
    displayName: "Bruce Wayne (Batman)",
    description: "Wayne Enterprises billionaire alter-ego sovereign holding. 355 firms approved.",
    universe: "DC",
    pricing: { price: 1250.00, delta: 0.95, fmv: 1250.00, production_age: "golden", era: "Golden Age" },
    detailUrl: "/assets/BWAY",
    coverImageUrl: SURFACE_ART_MAP.SECRET_IDENTITY || "/surface-art/secret_identity.png",
    coverVerified: true,
    quarantined: false,
    parameters: { firmSupport: "355 Firms Enrolled", ipoStatus: "Active Market" },
  },
  {
    entryId: "asset-sec-cknt",
    assetId: "CKNT",
    assetType: "SECRET_IDENTITY",
    symbol: "$CKNT",
    displayName: "Clark Kent (Superman)",
    description: "Daily Planet investigative reporter secret identity instrument.",
    universe: "DC",
    pricing: { price: 680.00, delta: -0.30, fmv: 680.00, production_age: "platinum", era: "Platinum Age" },
    detailUrl: "/assets/CKNT",
    coverImageUrl: SURFACE_ART_MAP.SECRET_IDENTITY || "/surface-art/secret_identity.png",
    coverVerified: true,
    quarantined: false,
    parameters: { firmSupport: "355 Firms Enrolled", ipoStatus: "Active Market" },
  },

  // ── 3. Real-World Conglomerates & IP Owners (Unspun Live Market Rates) ──
  {
    entryId: "asset-pub-dis",
    assetId: "DIS",
    assetType: "PUBLISHER_STOCK",
    symbol: "$DIS",
    displayName: "Walt Disney Co (Marvel IP)",
    description: "NYSE: DIS. Real-world corporate parent of Marvel Comics, MCU, and licensing royalties.",
    universe: "Real World",
    pricing: { price: 114.85, delta: 1.15, fmv: 114.85 },
    detailUrl: "/assets/DIS",
    coverImageUrl: SURFACE_ART_MAP.PUBLISHER_STOCK || "/surface-art/publisher_stock.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-pub-sony",
    assetId: "SONY",
    assetType: "PUBLISHER_STOCK",
    symbol: "$SONY",
    displayName: "Sony Group Corp (Spider-Man Film IP)",
    description: "NYSE: SONY. Live trading rate for global Spider-Man theatrical and gaming distribution rights.",
    universe: "Real World",
    pricing: { price: 94.20, delta: -0.40, fmv: 94.20 },
    detailUrl: "/assets/SONY",
    coverImageUrl: SURFACE_ART_MAP.PUBLISHER_STOCK || "/surface-art/publisher_stock.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-pub-wbd",
    assetId: "WBD",
    assetType: "PUBLISHER_STOCK",
    symbol: "$WBD",
    displayName: "Warner Bros Discovery (DC Comics Parent)",
    description: "NASDAQ: WBD. Corporate owner of DC Studios, DC Comics catalog, and character licensing.",
    universe: "Real World",
    pricing: { price: 10.45, delta: 2.30, fmv: 10.45 },
    detailUrl: "/assets/WBD",
    coverImageUrl: SURFACE_ART_MAP.PUBLISHER_STOCK || "/surface-art/publisher_stock.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-pub-para",
    assetId: "PARA",
    assetType: "PUBLISHER_STOCK",
    symbol: "$PARA",
    displayName: "Paramount Global (TMNT Media Rights)",
    description: "NASDAQ: PARA. Live tracking of Teenage Mutant Ninja Turtles global franchise rights.",
    universe: "Real World",
    pricing: { price: 12.80, delta: 0.65, fmv: 12.80 },
    detailUrl: "/assets/PARA",
    coverImageUrl: SURFACE_ART_MAP.PUBLISHER_STOCK || "/surface-art/publisher_stock.png",
    coverVerified: true,
    quarantined: false,
  },

  // ── 4. Fictional Municipal & State Bonds ──
  {
    entryId: "asset-bond-goth",
    assetId: "GOTH-MUNI",
    assetType: "BOND",
    symbol: "$GOTH-MUNI",
    displayName: "Gotham City Infrastructure 5.25% 2034",
    description: "Municipal bond yielding 5.25%. Yield and credit spread fluctuate based on Arkham breakout news.",
    universe: "DC",
    pricing: { price: 98.40, delta: -0.45, fmv: 98.40 },
    detailUrl: "/assets/GOTH-MUNI",
    coverImageUrl: SURFACE_ART_MAP.BOND || "/surface-art/bond.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-bond-cent",
    assetId: "CENT-MUNI",
    assetType: "BOND",
    symbol: "$CENT-MUNI",
    displayName: "Central City S.T.A.R. Labs 4.80% 2032",
    description: "Civic transit and particle physics municipal bond. Spreads react to rogue gallery activities.",
    universe: "DC",
    pricing: { price: 101.20, delta: 0.25, fmv: 101.20 },
    detailUrl: "/assets/CENT-MUNI",
    coverImageUrl: SURFACE_ART_MAP.BOND || "/surface-art/bond.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-bond-wak",
    assetId: "WAK-SOV",
    assetType: "BOND",
    symbol: "$WAK-SOV",
    displayName: "Wakanda Sovereign Vibranium 3.45% 2040",
    description: "Triple-A rated sovereign treasury bond collateralized by physical vibranium reserves.",
    universe: "Marvel",
    pricing: { price: 104.50, delta: 0.15, fmv: 104.50 },
    detailUrl: "/assets/WAK-SOV",
    coverImageUrl: SURFACE_ART_MAP.BOND || "/surface-art/bond.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-bond-nycs",
    assetId: "NYCS-MUNI",
    assetType: "BOND",
    symbol: "$NYCS-MUNI",
    displayName: "NYC Super-Hero Damage Assessment 6.10%",
    description: "High-yield catastrophe municipal bond insuring Midtown Manhattan against super-battles.",
    universe: "Marvel",
    pricing: { price: 95.80, delta: 1.10, fmv: 95.80 },
    detailUrl: "/assets/NYCS-MUNI",
    coverImageUrl: SURFACE_ART_MAP.BOND || "/surface-art/bond.png",
    coverVerified: true,
    quarantined: false,
  },

  // ── 5. Derivatives, Options, Swaps & Volatility ──
  {
    entryId: "asset-opt-asm",
    assetId: "ASM-C-1500",
    assetType: "OPTIONS",
    symbol: "$ASM-C-1500",
    displayName: "ASM #300 CGC 9.8 Call 1500",
    description: "Derivative call option on Amazing Spider-Man #300 9.8 strike $1,500. Delta: 0.642.",
    universe: "Derivative",
    pricing: { price: 145.00, delta: 4.80, fmv: 145.00 },
    detailUrl: "/assets/ASM-C-1500",
    coverImageUrl: SURFACE_ART_MAP.OPTIONS || "/surface-art/options.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-opt-bat",
    assetId: "BAT-P-2000",
    assetType: "OPTIONS",
    symbol: "$BAT-P-2000",
    displayName: "Batman #181 CGC 9.0 Put 2000",
    description: "Derivative put option hedging downside risk on Poison Ivy 1st appearance.",
    universe: "Derivative",
    pricing: { price: 85.00, delta: -2.30, fmv: 85.00 },
    detailUrl: "/assets/BAT-P-2000",
    coverImageUrl: SURFACE_ART_MAP.OPTIONS || "/surface-art/options.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-swap-gold",
    assetId: "SWAP-GOLD-SILV",
    assetType: "SWAPS",
    symbol: "$SWAP-GOLD-SILV",
    displayName: "Golden/Silver Sovereign Return Swap",
    description: "Institutional swap contract exchanging Golden Age appreciation against Silver Age volatility.",
    universe: "Derivative",
    pricing: { price: 320.00, delta: 0.75, fmv: 320.00 },
    detailUrl: "/assets/SWAP-GOLD-SILV",
    coverImageUrl: SURFACE_ART_MAP.SWAPS || "/surface-art/swaps.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-vix-comic",
    assetId: "VIX-COMIC",
    assetType: "VOLATILITY",
    symbol: "$VIX-COMIC",
    displayName: "Comic Market Implied Volatility Index",
    description: "Expected 30-day volatility index across sovereign certified slab auctions.",
    universe: "Derivative",
    pricing: { price: 18.45, delta: 1.25, fmv: 18.45 },
    detailUrl: "/assets/VIX-COMIC",
    coverImageUrl: SURFACE_ART_MAP.VOLATILITY || "/surface-art/volatility.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-vix-goth",
    assetId: "VIX-GOTH",
    assetType: "VOLATILITY",
    symbol: "$VIX-GOTH",
    displayName: "Gotham Threat Volatility Meter",
    description: "Lore-driven geopolitical risk index measuring villain activity contagion.",
    universe: "Derivative",
    pricing: { price: 42.10, delta: 3.40, fmv: 42.10 },
    detailUrl: "/assets/VIX-GOTH",
    coverImageUrl: SURFACE_ART_MAP.VOLATILITY || "/surface-art/volatility.png",
    coverVerified: true,
    quarantined: false,
  },

  // ── 6. Commodities, Gadgets, Locations, and Artifacts ──
  {
    entryId: "asset-cmdty-vib",
    assetId: "VIB",
    assetType: "COMMODITY",
    symbol: "$VIB",
    displayName: "Vibranium Pure Reserve Ingot",
    description: "Wakandan sovereign strategic metal reserve contract. Physical delivery in Birnin Zana.",
    universe: "Marvel",
    pricing: { price: 425.00, delta: 1.65, fmv: 425.00 },
    detailUrl: "/assets/VIB",
    coverImageUrl: SURFACE_ART_MAP.COMMODITY || "/surface-art/commodity.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-cmdty-adm",
    assetId: "ADM",
    assetType: "COMMODITY",
    symbol: "$ADM",
    displayName: "Adamantium Primary Alloy",
    description: "Indestructible metallurgical compound holding. Restricted industrial transfer.",
    universe: "Marvel",
    pricing: { price: 680.00, delta: -0.50, fmv: 680.00 },
    detailUrl: "/assets/ADM",
    coverImageUrl: SURFACE_ART_MAP.COMMODITY || "/surface-art/commodity.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-cmdty-kryp",
    assetId: "KRYP",
    assetType: "COMMODITY",
    symbol: "$KRYP",
    displayName: "Green Kryptonite Specimen",
    description: "Extraterrestrial radioactive isotope contract with tactical hedge properties.",
    universe: "DC",
    pricing: { price: 310.00, delta: 0.25, fmv: 310.00 },
    detailUrl: "/assets/KRYP",
    coverImageUrl: SURFACE_ART_MAP.COMMODITY || "/surface-art/commodity.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-gadget-mjol",
    assetId: "MJOL",
    assetType: "GADGET",
    symbol: "$MJOL",
    displayName: "Mjolnir (Uru Hammer of Thor)",
    description: "Cosmic enchanted relic artifact. Worthiness covenant collateral.",
    universe: "Marvel",
    pricing: { price: 1950.00, delta: 0.90, fmv: 1950.00, production_age: "silver", era: "Silver Age" },
    detailUrl: "/assets/MJOL",
    coverImageUrl: SURFACE_ART_MAP.GADGET || "/surface-art/gadget.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-gadget-gant",
    assetId: "GANT",
    assetType: "GADGET",
    symbol: "$GANT",
    displayName: "Infinity Gauntlet",
    description: "Omnipotent cosmic artifact holding six operational infinity stones.",
    universe: "Marvel",
    pricing: { price: 3800.00, delta: 2.10, fmv: 3800.00, production_age: "copper", era: "Copper Age" },
    detailUrl: "/assets/GANT",
    coverImageUrl: SURFACE_ART_MAP.GADGET || "/surface-art/gadget.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-gadget-batmb",
    assetId: "BATMB",
    assetType: "GADGET",
    symbol: "$BATMB",
    displayName: "Batmobile (Detective Comics #27 Lineage)",
    description: "Tactical defense vehicular asset with multi-era upgrade provisions.",
    universe: "DC",
    pricing: { price: 5400.00, delta: 1.40, fmv: 5400.00, production_age: "golden", era: "Golden Age" },
    detailUrl: "/assets/BATMB",
    coverImageUrl: SURFACE_ART_MAP.GADGET || "/surface-art/gadget.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-loc-goth",
    assetId: "GOTH",
    assetType: "LOCATION",
    symbol: "$GOTH",
    displayName: "Gotham City Metropolitan Real Estate",
    description: "Sovereign urban territory index reflecting crime contagion and real estate yields.",
    universe: "DC",
    pricing: { price: 2100.00, delta: 0.70, fmv: 2100.00, production_age: "golden", era: "Golden Age" },
    detailUrl: "/assets/GOTH",
    coverImageUrl: SURFACE_ART_MAP.LOCATION || "/surface-art/location.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-loc-wak",
    assetId: "WAK",
    assetType: "LOCATION",
    symbol: "$WAK",
    displayName: "Wakanda Golden City",
    description: "Sovereign territorial equity backed by isolationist technology covenants.",
    universe: "Marvel",
    pricing: { price: 1680.00, delta: 1.90, fmv: 1680.00, production_age: "silver", era: "Silver Age" },
    detailUrl: "/assets/WAK",
    coverImageUrl: SURFACE_ART_MAP.LOCATION || "/surface-art/location.png",
    coverVerified: true,
    quarantined: false,
  },

  // ── 7. Villains, Battles & Nemeses ──
  {
    entryId: "asset-vil-doom",
    assetId: "DOOM",
    assetType: "VILLAIN",
    symbol: "$DOOM",
    displayName: "Doctor Doom",
    description: "Monarch of Latveria. Blue-chip sovereign threat holding.",
    universe: "Marvel",
    pricing: { price: 2100.00, delta: 3.20, fmv: 2100.00, production_age: "silver", era: "Silver Age" },
    detailUrl: "/assets/DOOM",
    coverImageUrl: SURFACE_ART_MAP.VILLAIN || "/surface-art/villain.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-vil-jkr",
    assetId: "JKR",
    assetType: "VILLAIN",
    symbol: "$JKR",
    displayName: "The Joker",
    description: "Clown Prince of Crime. Unhedged pure market anarchy exposure.",
    universe: "DC",
    pricing: { price: 2800.00, delta: 1.80, fmv: 2800.00, production_age: "golden", era: "Golden Age" },
    detailUrl: "/assets/JKR",
    coverImageUrl: SURFACE_ART_MAP.VILLAIN || "/surface-art/villain.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-bat-hvk",
    assetId: "HVK-BAT",
    assetType: "BATTLE_STATS",
    symbol: "$HVK-BAT",
    displayName: "Hulk vs Wolverine (Hulk #181)",
    description: "Historic debut clash collateralized by certified auction transaction records.",
    universe: "Marvel",
    pricing: { price: 4200.00, delta: 3.10, fmv: 4200.00, production_age: "bronze", era: "Bronze Age" },
    detailUrl: "/assets/HVK-BAT",
    coverImageUrl: SURFACE_ART_MAP.BATTLE_STATS || "/surface-art/battle_stats.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-nem-batjkr",
    assetId: "NEM-BATJKR",
    assetType: "NEMESIS",
    symbol: "$NEM-BATJKR",
    displayName: "Batman vs Joker Nemesis Pair",
    description: "Dual-sided antithesis asset with 50/50 split exposure to justice vs chaos.",
    universe: "DC",
    pricing: { price: 3400.00, delta: 2.15, fmv: 3400.00 },
    detailUrl: "/assets/NEM-BATJKR",
    coverImageUrl: SURFACE_ART_MAP.NEMESIS || "/surface-art/nemesis.png",
    coverVerified: true,
    quarantined: false,
  },

  // ── 8. Funds, ETFs & Vehicles ──
  {
    entryId: "asset-etf-xgld",
    assetId: "XGLD",
    assetType: "ETF",
    symbol: "$XGLD",
    displayName: "Golden Age Pure Alpha ETF",
    description: "Diversified index basket tracking high-grade Golden Age comic benchmarks.",
    universe: "Fund",
    pricing: { price: 345.20, delta: 0.85, fmv: 345.20 },
    detailUrl: "/assets/XGLD",
    coverImageUrl: SURFACE_ART_MAP.ETF || "/surface-art/etf.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-etf-xsil",
    assetId: "XSIL",
    assetType: "ETF",
    symbol: "$XSIL",
    displayName: "Silver Age Growth ETF",
    description: "Benchmark ETF capturing Silver Age Marvel & DC institutional market velocity.",
    universe: "Fund",
    pricing: { price: 218.40, delta: 1.25, fmv: 218.40 },
    detailUrl: "/assets/XSIL",
    coverImageUrl: SURFACE_ART_MAP.ETF || "/surface-art/etf.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-fut-bronze",
    assetId: "FUT-BRNZ",
    assetType: "FUTURES",
    symbol: "$FUT-BRNZ",
    displayName: "Bronze Age Dec 2026 Future",
    description: "Standardized futures contract settling against the Bronze Age Sovereign Composite.",
    universe: "Derivative",
    pricing: { price: 185.00, delta: 0.40, fmv: 185.00 },
    detailUrl: "/assets/FUT-BRNZ",
    coverImageUrl: SURFACE_ART_MAP.FUTURES || "/surface-art/futures.png",
    coverVerified: true,
    quarantined: false,
  },

  // ── 9. Prediction Markets ──
  {
    entryId: "asset-pred-mcu",
    assetId: "PRED-MCU-XMN",
    assetType: "PREDICTION",
    symbol: "$PRED-MCU-XMN",
    displayName: "MCU X-Men Film Premiere Before Q4 2027",
    description: "Binary prediction market contract settling to $1.00 upon official theatrical premiere.",
    universe: "Prediction",
    pricing: { price: 0.68, delta: 0.05, fmv: 0.68 },
    detailUrl: "/assets/PRED-MCU-XMN",
    coverImageUrl: SURFACE_ART_MAP.PREDICTION || "/surface-art/prediction.png",
    coverVerified: true,
    quarantined: false,
  },
  {
    entryId: "asset-pred-cgc10",
    assetId: "PRED-CGC-10",
    assetType: "PREDICTION",
    symbol: "$PRED-CGC-10",
    displayName: "First Action #1 CGC 10.0 Graded in 2026",
    description: "Binary event market contract covering census emergence of a Gem Mint Action Comics #1.",
    universe: "Prediction",
    pricing: { price: 0.12, delta: -0.02, fmv: 0.12 },
    detailUrl: "/assets/PRED-CGC-10",
    coverImageUrl: SURFACE_ART_MAP.PREDICTION || "/surface-art/prediction.png",
    coverVerified: true,
    quarantined: false,
  },
];
